### ISSUE TITLE
Segmentation loaded from volume has non-descriptive segment names

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#4733]
## Environment
- Slicer version: Slicer-4.11.0 r28813
- Operating system: Linux

## Steps to reproduce the issue:

Loaded the attached volume file as segmentation.
[4962.Oto-label.nrrd.gz](https://github.com/Slicer/Slicer/files/4340012/4962.Oto-label.nrrd.gz)

## What was expected to happen?

The segment names are expected to contain the original label values (1, 2, 4, 8).

## What happened instead?

The segmentation was loaded with segment names Segment, Segment_1, Segment_2, .... See the screen capture below.

![image](https://user-images.githubusercontent.com/21285140/76792772-fd37f880-6780-11ea-9705-ee2049427730.png)

The segment names did not indicate which original label value they correspond to, which made it difficult to interpret the segmentation.

**Comment by Sunderlandkyl** [comment]
The segment labels generated from importing Segments from nrrd haven't traditionally used the numbering from the label value.

@lassoan Do you have any thoughts on changing imported segment naming?

**Comment by lassoan** [comment]
We could use the names stored in the associated color node. It would be even nicer to look up the corresponding terminology entry.

**Comment by muratmaga** [comment]
I would advise against trying to guess the name or lookup (e.g., these are fish otoliths, I don't think you will have corresponding names for them). The important is to make the behavior consistent between using the segmentations module (which retains the correct label indices assigned in the labelmap) vs direct import via Add Data dialog.

**Comment by lassoan** [comment]
Sorry, I've just figured out what the question is about (it was very confusing to have an extremely long header and very sparse description of the issue).

When you load a labelmap then you can choose a corresponding colormap, but there is no such selector for segmentations. So, when we import a labelmap directly as segmentation, probably the simplest would be to add segment names that contain the label value in the format Segment_N.

We may also need to tune automatic segment name generation so that when we already have segment names such as Segment_1, Segment_2, Segment_3, etc. then adding a new segment would not create a Segment_1 again (but rather Segment_4).

@Sunderlandkyl could you work on this?

**Comment by muratmaga** [comment]
Sorry, I thought screenshot highlighted the issue, but next time I will provide more verbose description (and a shorter title). Thanks.

**Comment by Sunderlandkyl** [comment]
@lassoan ok, I'll work on it.
