### ISSUE TITLE
Improve colors in "Dark mode"

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#4803]
Color of web links in Dark mode has too much contrast.

## Steps to reproduce

Slicer Slicer. Then, observe web links in welcome module or in the help tab of any modules.

For example, here is the welcome module:

![image](https://user-images.githubusercontent.com/219043/78324388-910c1180-7542-11ea-9707-42d1f3a0958b.png)

## Expected behavior

Web links should be represented with a lighter color like the one used on the "stackoverflow" website in dark mode.

Normal: #3ca4ff
Hover: #378ad3

![image](https://user-images.githubusercontent.com/219043/78324477-cd3f7200-7542-11ea-8d7f-e5b4b73b6b62.png)

**Comment by pieper** [comment]
On a related note, the default background of the python console in dark mode needs to be fixed too.

**Comment by pieper** [comment]
@rkikinis also reports:  dark mode: black on dark grey is difficult to read

![image](https://user-images.githubusercontent.com/126077/78926413-0c9e1f00-7a6b-11ea-84d1-629abb12a882.png)

**Comment by pieper** [comment]
Also in the dicom metadata search bar the text is not easy to read:

![image](https://user-images.githubusercontent.com/126077/79462366-62bc1680-7fc5-11ea-8358-431a36d265f3.png)

When the text is selected you can see it:

![image](https://user-images.githubusercontent.com/126077/79462404-6fd90580-7fc5-11ea-8492-40aefadebc54.png)

**Comment by jamesobutler** [comment]
- [ ] Update the base color palette to fix issues such as link text color being difficult to read and the disabled text being dark and unreadable as seen in the "Models" module in images above.
- [ ] Python Console. Update colors when in Dark Slicer to something like ![image](https://user-images.githubusercontent.com/15837524/84601586-49add580-ae4f-11ea-8dae-7a3fd58882e9.png)
- [ ] DICOM Issues: The dicom metadata search box is updating from the dark base color to white again because of these lines which reset the palette of the search box to white when the filter warning is not shown.  Instead it should be restoring the palette used by parent widgets.  The text being white is correct for dark mode as it is on a dark color.
https://github.com/commontk/CTK/blob/17373933b81472450f85cc250cea1380610e09b3/Libs/DICOM/Widgets/ctkDICOMTableManager.cpp#L172-L184

**Comment by lassoan** [comment]
What would you all think about hardcoding Python console colors into the style class (the same way as we do it for all other colors in the application)?

Then, whenever the user changes the style selection, we could retrieve the colors from the style object and set it in the Python console.

**Comment by jamesobutler** [comment]
That seems fine with me. Should the python various color settings be kept or should they just be hardcored and just toggle between some known good set of colors for light and for dark?

**Comment by lassoan** [comment]
So, yes, switching style would switch Python console colors.Since implementing style-specific Python console color customization would not be very easy and probably just a handful of people would ever consider changing these colors, I think we should just remove the possibility of customizing console colors on the GUI.

**Comment by jamesobutler** [comment]
- [ ] @lassoan If I start Slicer and go to the DICOM module, the main table widget is using the correct color palette, but if I then change the application style such as from "Slicer" to "Dark Slicer", it won't change correctly.  If you change it again, then it toggles, but it toggles incorrectly.
![image](https://user-images.githubusercontent.com/15837524/84685285-06fc0400-af08-11ea-9c51-b9fbd8530c21.png)
![image](https://user-images.githubusercontent.com/15837524/84685315-11b69900-af08-11ea-94a4-552befcfd13a.png)

**Comment by lassoan** [comment]
Does it work well if you restart Slicer after changing the style? I saw that the DICOM database widget did not dynamically update its background for some reason.

**Comment by jamesobutler** [comment]
Yes, on start it is always using the style correctly, but when changing style within the session it is one update signal off for some reason resulting in the style being the previous style.

**Comment by jcfr** [comment]
> What would you all think about hardcoding Python console colors into the style class

That makes sense.

@jamesobutler  Thanks for working on this :pray:

**Comment by jamesobutler** [comment]
From @smrolfe there was some appearance issues on macOS.  This seems to be because we now use Qt 5.15 built with the macOS10.14 SDK (based on information from [here](https://discourse.slicer.org/t/2020-06-09-macos-packages-will-not-be-available-until-build-machine-is-updated-to-macos-10-13-6/11935/11)).  With this latest Qt update, dark mode is supported automatically using the macOS dark mode functionality.  

As you can see in https://discourse.slicer.org/t/slicer-preview-mac-view-issues/12077, it automatically displays a dark mode style even when "Slicer" is the selected style in the settings panel.  We should probably let macOS handle the light/dark mode transition and make the Slicer style setting option only available for the other platforms that don’t have system wide controlled dark mode.

**Comment by lassoan** [comment]
@jamesobutler Thanks for your awesome work on this! It would be great if you could add a SlicerLight theme that forces the same light palette (regardless of OS settings) on all platforms, and add a small logic in default Slicer theme to use dark colors on Windows if dark mode is chosen in OS settings (Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize\AppsUseLightTheme registry key).

**Comment by jamesobutler** [comment]
Yes, I will look into doing a "Slicer" (OS defined light/dark), "Light Slicer", and "Dark Slicer". I will probably add this to my open PR #4993.

- [ ] Should also look into https://doc.qt.io/qt-5/qguiapplication.html#platform-specific-arguments. Not sure where this could be set. There is another argument that is "dpiawareness=[0|1|2] Sets the DPI awareness of the process" which I think Slicer is already using?

> darkmode=[1|2] controls how Qt responds to the activation of the Dark Mode for applications introduced in Windows 10 1903 (since Qt 5.15).
> A value of 1 causes Qt to switch the window borders to black when Dark Mode for applications is activated and no High Contrast Theme is in use. This is intended for applications that implement their own theming.
> 
> A value of 2 will in addition cause the Windows Vista style to be deactivated and switch to the Windows style using a simplified palette in dark mode. This is currently experimental pending the introduction of new style that properly adapts to dark mode.

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/commit/566a81923988fd3a3e8443523bd76fe8d50b62ee, https://github.com/Slicer/Slicer/commit/2054a88780bf961bf0b0f4b2f7c74275371170f2, https://github.com/Slicer/Slicer/commit/044c7667ec82ee1b62ed6304f52d96f3915432ce
