### ISSUE TITLE
Add default build support with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#4859]
OpenSSL 1.0.2 support ended at the end of 2019. OpenSSL 1.1.1 is the new LTS and will be supported until September 11th 2023.

Upgrade the External_OpenSSL project and [SlicerOpenSSL](https://github.com/Slicer/Slicer-OpenSSL) to begin using OpenSSL 1.1.1.

https://github.com/Slicer/Slicer/blob/9403adc7ebe768be78a5a5033c39f7424f72adaf/SuperBuild/External_OpenSSL.cmake#L218-L232

Qt 5.12.4 was [released](https://www.qt.io/blog/2019/06/17/qt-5-12-4-released-support-openssl-1-1-1) with support for OpenSSL 1.1.1.
- [X] Update Qt version used in Slicer to Qt 5.12.4 or newer. Preferably latest release.

Python 3.7.4 was [released](https://www.python.org/downloads/release/python-374/) to use OpenSSL 1.1.1.
- [ ] Update Python version used in Slicer to Python 3.7.4 or newer. Preferably latest release.

**Comment by hjmjohnson** [comment]
I think this would also allow a more clean install. See OpenSSL related issue #4857

**Comment by hjmjohnson** [comment]
I get a crash with slicer an Qt on linux.  I am pretty sure the error is related to :+1: 

https://github.com/openssl/openssl/issues/3733, which I think is fixed in OpenSSL 1.1.1

The segfault occurs at:
https://github.com/Slicer/Slicer/blob/master/Base/QTCore/qSlicerCoreApplication.cxx#L265

Here is the stack at the time of failure.
```
__strcmp_sse2_unaligned 0x00007ff8588d1e8a
lh_insert 0x00007ff87e30aadd
OBJ_NAME_add 0x00007ff87e253f5b
<unknown> 0x00007ff841c76e5e
__pthread_once_slow 0x00007ff8682c4827
CRYPTO_THREAD_run_once 0x00007ff8420af8f9
OPENSSL_init_ssl 0x00007ff841c7707b
QSslSocketPrivate::ensureLibraryLoaded 0x00007ff87d86a9f7
qSlicerCoreApplicationPrivate::init qSlicerCoreApplication.cxx:265
qSlicerApplicationPrivate::init qSlicerApplication.cxx:203
qSlicerApplication::qSlicerApplication qSlicerApplication.cxx:357
(anonymous namespace)::SlicerAppMain Main.cxx:40
main qSlicerApplicationMainWrapper.cxx:56
__libc_start_main 0x00007ff858849b97
_start 0x0000558c1b49e88a
```

Now, if I comment-out lines 256-268, then Slicer starts up and seems to work normally

https://forum.qt.io/topic/99869/ssl-problem-on-linux-windows/7 indicates that perhaps a mismatch in openssl versions is to blame.

**Comment by jcfr** [comment]
Thanks for bringing this up.

We need to update OpenSSL, it is also causing issue on the updated macOS build machine.
See http://slicer.cdash.org/testDetails.php?test=10049841&build=1941859

Prior contributions and investigations from @jamesobutler and @hjmjohnson will be very useful to move forward 🙏 

Note that the `malformed mach-o: load commands size` error is independent and will be addressed by shortening the source and build directories (based on suggestions found at https://discourse.slicer.org/t/macos-sierra-10-12-6-dynamic-linker-errors/2339 and https://discourse.slicer.org/t/building-on-mac-10-14-mojave/4554/30)


Blocker is to update the version of python to Python 3.7.4 or newer. Preferably latest release.  It means we would need to finalize integration of these:
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/264
* https://github.com/python-cmake-buildsystem/python-cmake-buildsystem/pull/267

**Comment by jcfr** [comment]
Closing  this issue. 

The OpenSSL issue described above is expected to be fixed by https://github.com/Slicer/Slicer/pull/4992 integrating commit https://github.com/Slicer/Slicer/pull/4992/commits/3d8bc4ae374dcee2274375d23dc28445537d7143

> Update Python version used in Slicer to Python 3.7.4 or newer. Preferably latest release.

Based on test done so far, this wasn't strictly required. Update of python is now tracked in its own issue https://github.com/Slicer/Slicer/issues/5014
