### ISSUE TITLE
Annotation module: Exception thrown in event: std::bad_alloc

### ISSUE THREAD

**Issue by torquil** [Slicer/Slicer#4903]
I am using the latest 3DSlicer nightly on Linux. I have two AnnotationRulers. So the list of annotations in the Annotation module contains four rows in a tree structure with three levels:

All annotations
-Ruler List
--D6
--D

(D6 and D are the names of my AnnotationRulers). If I click on "Select all annotations and hierarchies" (the leftmost button) so that all four lines are highlighted and ticked, and then click on the Annotation Report button, I get a popupwindow entitled "Internal error". Here is the detailed error text:

"Slicer has caught an internal error
You may be able to continue from this point, but results are undefined
.
.
.
.
.
The message detail is:
Exception thrown in event: std::bad_alloc"

Best regards,
Torquil Sørensen

**Comment by pieper** [comment]
> std::bad_alloc

means the program [wasn't able to allocate memory](https://en.cppreference.com/w/cpp/memory/new/bad_alloc), but in this case it could be due to some internal bug in Annotations.

The Annotations module is being replaced with the Markups, so please try the latest nightly preview build and use a Line rather than Ruler and look in the Markups module and not Annotations.

**Comment by lassoan** [comment]
Please use Markups module's "Line" instead and let us know if you encounter any problems or miss any features.

**Comment by lassoan** [comment]
Annotations module is deprecated, no more fixes will be implemented.
