### ISSUE TITLE
Migrate Slicer build instructions to readthedocs adding them to git

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4924]
Build instructions are very tightly linked to the source code, so it should be stored in the repository.

**Comment by jamesobutler** [comment]
@lassoan I believe this issue is complete?

Old Build Instructions: https://www.slicer.org/wiki/Documentation/Nightly/Developers/Build_Instructions

New Build Instructions:
- https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/index.html
- https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/windows.html
- https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/macos.html
- https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html

ReadTheDocs pages generated from content in the repo. As seen from today: https://github.com/Slicer/Slicer/tree/c1d3ac1ba20ab1514ed29ab9c20becabc216d76e/Docs/developer_guide/build_instructions

**Comment by lassoan** [comment]
Yes, indeed, it is done!
