### ISSUE TITLE
Slicer application cannot be uninstalled on Windows

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#4933]
When attempting to uninstall a recent Slicer-4.11 version in Windows settings / Apps & features, the operation fails.

![image](https://user-images.githubusercontent.com/307929/82718256-6b140b00-9c6f-11ea-84a0-af4d2a31ffd4.png)

**Comment by sjh26** [comment]
How recent (pre or post qt 5.14 switch on 5/20) ?

**Comment by lassoan** [comment]
All versions in the past few weeks or even months.

**Comment by sjh26** [comment]
Ooof

**Comment by sjh26** [comment]
Okay, I've been able to replicate this. Will try to narrow down when it started.

**Comment by sjh26** [comment]
Very likely caused by the change in install location: https://github.com/Slicer/Slicer/commit/217fe97d5c52326f88d12f1b1cff6f80feb65808

2019-6-11 installation is fine, 2019-6-12 installation has the bug

**Comment by lassoan** [comment]
I'm quite sure I uninstalled releases successfully after 2019-06-12, so maybe this is also related to some OS changes.

**Comment by jamesobutler** [comment]
Here's some information from my testing. Uninstall was working on my computer through "Control Panel\Programs\Programs and Features" but not "Windows settings / Apps & features".  Based on the error message it is looking in the location of "C:\Users\james\AppData\Local\NA-MIC\Slicer" which is not where the program was installed. The default location is for example at "C:\Users\james\AppData\Local\NA-MIC\Slicer 4.11.0-2020-05-23".  

The directory of "C:\Users\james\AppData\Local\NA-MIC\Slicer" does get created once you launch the Extensions Manager as it contains some cache for Qt QWebEngine.  If you delete this "C:\Users\james\AppData\Local\NA-MIC\Slicer" directory of cache and then try the uninstall of Slicer through "Window settings / Apps & features" it will now work.  Even Slicer 4.10.2 will create this "C:\Users\james\AppData\Local\NA-MIC\Slicer" directory after opening Extensions Manager, so the creation of this directory hasn't changed due to a recently updated Qt version.

**Comment by jamesobutler** [comment]
I am still observing issues with uninstalling through Windows 10 "Apps & Features".
![image](https://user-images.githubusercontent.com/15837524/126910880-36375ecb-6c6e-472d-a08e-7b8f164f5c64.png)

Pressing uninstall opens File Explorer to the following directory and does not proceed to uninstall
![image](https://user-images.githubusercontent.com/15837524/126910923-3ff17639-e61e-44f5-b670-0f74e58d3706.png)

**Comment by lassoan** [comment]
This is a CMake bug, pull request submitted with the fix: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/6517

**Comment by lassoan** [comment]
The fix for the CMake bug is merged now. It is scheduled to be included in the CMake 3.22.0. When this release is out, then CMake should be updated on the Windows factory computer.

**Comment by jamesobutler** [comment]
I can confirm having built Slicer locally and packaging with CMake 3.22.0 downloaded from https://cmake.org/download/ that it successfully uninstalls from Windows settings Apps & Features area. It actually brings up the uninstaller correctly.

![image](https://user-images.githubusercontent.com/15837524/142650976-dadcd5b6-c0b7-4ada-b35c-ed423af0407c.png)

![image](https://user-images.githubusercontent.com/15837524/142650963-5c37b60a-9197-4770-891d-bd04e5db769a.png)

**Comment by lassoan** [comment]
Thanks for testing. I'll update the target release to Slicer-4.13.

**Comment by sjh26** [comment]
Fixed: https://github.com/Slicer/DashboardScripts/commit/c9879876ed337c3c908895628430daf30e7a221a
