### ISSUE TITLE
Add pip_uninstall to slicer.util

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5006]
## Is your feature request related to a problem? Please describe.

Sometimes I want to pip-uninstall a Python package in Slicer and replace it with a local version, but there's only `pip_install` in `slicer.util`.

## Describe the solution you'd like

An equivalent `slicer.util.pip_uninstall`.

## Describe alternatives you've considered

I propose modifying `pip_install` to take, for example, a `uninstall` boolean kwarg. Then there could be a wrapper called `pip_uninstall`. I can work on this.

Also, I don't know why this function is `snake_case`. It's not consistent with Slicer `camelCase`.

**Comment by lassoan** [comment]
Adding a pip_uninstall would be nice, indeed.

We chose `pip_install` over `pipInstall` to be more similar to the usual `pip install` command (`pipInstall` would be also quite hard to read because the uppercase `i` looks like a lowercase `l`). At this point, I would probably keep the snake-case.

It would be great if you could implmement pip uninstall. If you do so, factor out common parts into a new `_executePythonModule` function, which both pip_install and pip_uninstall can use.

**Comment by fepegar** [comment]
> We chose pip_install over pipInstall to be more similar to the usual pip install command (pipInstall would be also quite hard to read because the uppercase i looks like a lowercase l).

I think consistency is more important the function looking like the command. There are many lines in the Python files of the repo where one can find a capital `I` in a camel case variable (`SetInput()`). The difference is very clear in monospace fonts (IlIlIl vs `IlIlIl`), and inferring the letter from the context seems quite obvious in this case. The command hasn't been around for too long, so it shouldn't break too much code. What about changing it for the upcoming release?

By the way, there are other variables in `slicer.util` that don't follow snake case either (e.g. `dest_module_name`).

I'll open a PR in a second.

**Comment by lassoan** [comment]
I agree that consistency is important but somehow I still prefer pip_install over pipInstall.

pip_install is already used at many places, but we could add pipInstall in addition to it if there is an agreement that this would be a better name.

**Comment by pieper** [comment]
Yeah, this inconsistency didn't bother me, probably because it feels like a python system utility and not part of the Slicer API proper.  I agree it's too late to remove `pip_install`.

How about just having a `pip` command so it would be clearer you are just doing the equivalent of passing command line arguments to `python -m pip`.  So you would have `slicer.util.pip("install tensorflow")` and `pip("uninstall tensorflow")`.

**Comment by fepegar** [comment]
If `pip uninstall` is used, `pip` asks the user for confirmation. That's why I added `--yes` to the command for `pip_uninstall`: https://github.com/Slicer/Slicer/commit/4d4bf0e183ae36e2b9286285ba03662019a552dc

A workaround would be to add `--yes` to the command in that `slicer.pip` if the first word is `uninstall`.

**Comment by lassoan** [comment]
Yes, `slicer.util.pip` would be a great solution for the naming issue. However, it could lead problems, such as:
- it would suggest it is just an alias for `python -m pip`, while `pip_install` is declared to be a higher-level function, which uses the same format as the system utility but it may filter out, override, add options, display GUI asking for user confirmation, etc. in the future to ensure correct and consistent behavior within Slicer (https://github.com/Slicer/Slicer/blob/524979a2e91ff25de690909f141e6afbe1b1c6e5/Base/Python/slicer/util.py#L2424-L2426)
- it would suggest that users are welcome to use all pip features (freeze, config, debug, ...), while actually I don't think we are prepared for this (maybe there is no problem using all pip functions in Slicer' Python environment but at least we would need to do some testing and research).

**Comment by lassoan** [comment]
Fixed in https://github.com/Slicer/Slicer/pull/5015
