### ISSUE TITLE
DICOM plugins loading

### ISSUE THREAD

**Issue by spujol** [Slicer/Slicer#5115]
Is there a way to load all the DICOM plugins at once by default?

**Comment by pieper** [comment]
Each of the plugins is given the list of files in the series during the Examine step.  Each plugin examines the files to see if they match something that the plugin can load, and the plugin provides a list of 'loadable' options, each with a numeric confidence about how well the data matches the plugin's abilities.  By default, the loadables with the highest confidence are loaded by the Load button.

In Advanced mode, the user has the option to disable unwanted plugins (e.g. because they take time or give incorrect results) and also the ability to choose different loadables based on knowledge about the data that the plugin couldn't not discover from the headers.

So generally you don't want to load all the plugins since they represent alternative ways to interpret the data (e.g. as a single scalar volume or a sequence).

Does that answer your question?

**Comment by spujol** [comment]
Thank you for the clarification!  

I was wondering if it would make sense to have specific plugins such as DICOMRTImportExportPlugin loaded by default and disabled to save the user the extra step of downloading the extension from the Extension Manager?

**Comment by pieper** [comment]
We could, but to me RT is specific enough that it's not really a core feature.  We migrated Sequences to the core since that is very generic.  Similarly diffusion volume nodes are in the core as a legacy feature, but to me they really should be in SlicerDMRI.  I'd be more inclined to see Quantitative Reporting in the core than RT myself.

In my experience unless there are connection issues, which should be fixed in any case, installing an extension is not a big burden for users.  It's more of a hassle for developers since we need to set up the build, but it's fairly easy to work around.

**Comment by lassoan** [comment]
A good plugin advisor would be a good solution to this problem. Since we already have an issue for that (https://github.com/Slicer/Slicer/issues/4753) I'm closing this issue now.
