### ISSUE TITLE
Colors are washed out in extensions manager on macOS Catalina

### ISSUE THREAD

**Issue by fepegar** [Slicer/Slicer#5118]
Widgets work, though.

![Screenshot](https://user-images.githubusercontent.com/12688084/89281945-b4ef7900-d642-11ea-8e3b-c1867ee9661b.png)

## Environment
- Slicer version: Slicer-4.11.0-2020-08-18
- Operating system: macOS Catalina 10.15.5

**Comment by lassoan** [comment]
Another user reported this issue, too: https://discourse.slicer.org/t/extension-manager-icons-look-faded/14077

**Comment by pieper** [comment]
Everything looks good on my machine with the current Slicer stable and the latest macOS

![image](https://user-images.githubusercontent.com/126077/96268947-b1a83000-0f97-11eb-8f35-28c935cb5496.png)


![image](https://user-images.githubusercontent.com/126077/96268984-bec51f00-0f97-11eb-8833-f5d232043046.png)

**Comment by fepegar** [comment]
It doesn't on mine (macOS `10.15.5` instead of `10.15.7`). I will 1) update my OS and 2) run those lines @lassoan shared on Discourse.

**Comment by lassoan** [comment]
I've tried it on a macOS Mojave 10.14.6 and the page renders correctly, too.

**Comment by fepegar** [comment]
Updating the OS didn't help.

This is what I see after running the first snippet you shared.

<img width="1280" alt="Screen Shot 2020-10-16 at 16 54 38" src="https://user-images.githubusercontent.com/12688084/96280904-7e35c780-0fd0-11eb-9c02-cae4cfa29d5f.png">

All blank (not even washed out), but the widgets are still there (I can click on the buttons and cursor changes).

It happens will al the websites. They work fine on Chrome.

**Comment by jamesobutler** [comment]
Maybe the difference between an older 2014 Mac with integrated intel graphics vs a newer Mac with discrete graphics?

**Comment by jamesobutler** [comment]
The latest info from the user mentioned in https://discourse.slicer.org/t/extension-manager-icons-look-faded/14077, now provides the following information about what configuration does not work and which does work.  I've summarized things below.

Hardware where this issue is observed:
| Model | Graphics |
|--------|------------|
|Macbook Pro Mid 2014 | Intel Iris 1536 MB|
|Macbook Pro Late 2013 | Intel Iris 1536 MB|

Hardware where the issue **has not** been observed:
| Model | Graphics |
|--------|------------|
|Mac Pro 2019 | AMD Radeon Pro W5700X 16 GB|

**Comment by fedorov** [comment]
Also seemingly same problem reported here: https://github.com/Radiomics/SlicerRadiomics/issues/62#issuecomment-719427367

**Comment by lassoan** [comment]
Changing the system to dark mode fixed the issue for one user (https://discourse.slicer.org/t/extension-manager-icons-look-faded/14077/9).

@fepegar could you check if switching to dark mode makes a difference on your system?

**Comment by fepegar** [comment]
Yes! I can see the colors in dark mode. But I don't think it happens at night, when dark mode is enabled automatically.

**Comment by lassoan** [comment]
After adding further data from more user reports:

Hardware where this issue is observed:
| Model  | Graphics   | Manual setting to dark mode fixed the issue |
|--------|------------|---------------------------------------------|
|Macbook Pro Mid 2015 | Intel Iris Pro 1536 MB |
|Macbook Pro Mid 2015 | Intel Iris Pro 1536 MB | yes
|Macbook Pro Mid 2014 | Intel Iris 1536 MB | yes
|Macbook Pro Late 2013 | Intel Iris 1536 MB |

Hardware where the issue **has not** been observed:
| Model | Graphics |
|--------|------------|
|Mac Pro 2019 | AMD Radeon Pro W5700X 16 GB |
|MacBook Air 2017 | Intel HD Graphics 6000 |

**Comment by lassoan** [comment]
If somebody encounters this again, it would be useful if setting environment variables can fix/improved the situation:

-----

Please check if setting chromium browser rendering settings by entering the following in the terminal windows before launching `./Slicer` (in the same terminal) makes any difference in how the extension manager looks:

```
export QTWEBENGINE_CHROMIUM_FLAGS=--blink-settings=darkMode=4,darkModeImagePolicy=2
```

It would be nice if you could try with different values, too: for darkMode try 0, 1, 2, 3, 4; for darkModeImagePolicy try 0, 1, 2 (based on values documented here).

**Comment by lassoan** [comment]
This problem has not come up in recent month, therefore closing it so that we can focus on issues that we plan to work on.

**Comment by lassoan** [comment]
Another user report: https://discourse.slicer.org/t/extension-manager-not-displaying-correctly-in-macos-light-mode/23478
