### ISSUE TITLE
Markups Display Size

### ISSUE THREAD

**Issue by spujol** [Slicer/Slicer#5180]
The default markups display size is very small. 

Would it be possible to increase the default size from 1% to 10% ?

<img width="1680" alt="Screen Shot 2020-09-09 at 7 18 30 PM" src="https://user-images.githubusercontent.com/1847492/92631709-be05e280-f29f-11ea-83fd-6fa402941487.png">

(Slicer4.11.0-2020-09-09 MacOS)

**Comment by lassoan** [comment]
3% looks good to me, maybe 5%. I would not use larger glyph size with a solid circle glyph, as it would occlude too much of the image:

![image](https://user-images.githubusercontent.com/307929/92636230-0378de80-f2a5-11ea-9564-0ac109bd7b45.png)

Maybe we could use up to 10% with a starburst 2D glyph:

![image](https://user-images.githubusercontent.com/307929/92636255-0bd11980-f2a5-11ea-962e-7f2727ce7dcb.png)

Or 2D cross glyph:

![image](https://user-images.githubusercontent.com/307929/92636444-60749480-f2a5-11ea-96ab-e23709a55018.png)

Once there is a consensus, it is very easy to change this - it is just a single line change [here](https://github.com/Slicer/Slicer/blob/master/Modules/Loadable/Markups/MRML/vtkMRMLMarkupsDisplayNode.cxx#L77).

@pieper @fedorov Do you have any preference for default glyph size and style?

We could also fine-tune the cross glyph to leave out the middle of the glyph (similarly to starburst) to not occlude the target position at all.

**Comment by pieper** [comment]
5% feels like a reasonable compromise to me.

if we are thinking of changing those defaults, feedback from the SlicerMorph team was that the default red-ish color for "selected" mode looks less "selected" than the aqua-ish unselected color.  Maybe we should make them a similar color but with different luminance, like this green.  It provides a good contrast to the yellow when you mouse over them.

![image](https://user-images.githubusercontent.com/126077/92637889-771beb00-f2a7-11ea-86ea-58764c001352.png)

**Comment by spujol** [comment]
5% sounds great. A difference luminance could make the distinction selected/unselected more intuitive.

**Comment by lassoan** [comment]
I've updated the crosshair glyph to a hollow crosshair with a dot (actually tiny cross) in the center.

![image](https://user-images.githubusercontent.com/307929/92809177-61332680-f38a-11ea-9ac9-c8d5221d7bf6.png)

It allows much more accurate point placement, looks more professional (like a high-precision tool, not like a toy ball), and it is larger (easier to click on it), and does not occludes the image as a solid disk/ball.

What do you think about using this as the default?

**Comment by pieper** [comment]
I like the crosshairs but not the dot in the middle.  I liked the starburst (old default) since it allows you to see the image data at the spot you are annotating and the eight lines give extra visual cues about exactly where the center is.

**Comment by lassoan** [comment]
Starburst is somewhat unusual (see various crosshair styles [here](https://images.google.ca/search?tbm=isch&q=point+glyph+crosshair) - there are so many but I did not find anything like the starburst). Crosshair with and without centerpoint is quite common.

![image](https://user-images.githubusercontent.com/307929/92813868-1c11f300-f390-11ea-9677-b954c0d0518d.png)

I like the center point very much and find the 8 lines in starburst a bit excessive, but it easy enough to change the default, so I'm fine with either.

I'll commit the change so that people can try the new options and post on discourse to get feedback from more people.

**Comment by fedorov** [comment]
I share @pieper concern about the point in the middle of the crosshairs. Having that point essentially assumes the target is bigger than the point itself, and I am not sure that will always be the case.

**Comment by lassoan** [comment]
I've pushed my changes for improving glyphs and adding the crosshair with dot glyph (https://github.com/Slicer/Slicer/commit/b1e3bdf583af81a79923d5f19c600d11d8ec4037). It will be available in tomorrow's preview release.

I have not updated the default size yet, we can do that when we agreed on which glyph we want to use.

**Comment by jamesobutler** [comment]
Here's what 1/3/5/10% glyph size looks on my standard 15" laptop with 1080p resolution and Windows default 125% scaling with this configuration.
![image](https://user-images.githubusercontent.com/15837524/145038260-7a203d10-58d6-40f6-b607-96ba05b79638.png)

**Comment by sjh26** [comment]
Do we have a consensus for the default size?  I want to get this closed out, so unless anyone has a complaint, I will set it to 5% and close.

**Comment by jamesobutler** [comment]
5% seems pretty large for 1080p. I think there is just an issue with regular vs high DPI screens and there isn't one size that works well for all here.

**Comment by jamesobutler** [comment]
The 5% shown in https://github.com/Slicer/Slicer/issues/5180#issuecomment-689728102 looks different from the 5% shown in https://github.com/Slicer/Slicer/issues/5180#issuecomment-987930147.

**Comment by lassoan** [comment]
I think 3% is acceptable on both hi-dpi and regular screens.

The % value should be relative to the screen (or view, I don't remember), so maybe there is an issue with the computation. The best would be to investigate this before choosing a final scaling value.

**Comment by lassoan** [comment]
I've investigated this and I've found a VTK bug in screen size query, which returned incorrect value on HiDPI screens (returned device-independent size instead of real pixel size, which is about 2-3x smaller). I've submitted a fix: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8956

After this fix is integrated, I will set the default glyph size to 3% (and keep the default sphere glyph for now), as it will look good on all displays. Screenshots taken after the VTK fix is applied:

HiDPI (2256x1504) screen:

![image](https://user-images.githubusercontent.com/307929/156389745-e143fae4-7c9e-4310-ac1e-e89fe0395f90.png)

Non-HiDPI (1920x1080) screen:

![image](https://user-images.githubusercontent.com/307929/156390122-9829465e-d5cd-442c-8e21-659cca6cc609.png)

**Comment by lassoan** [comment]
The VTK fix has been merged. I don't start backporting this, waiting 1-2 days to see if https://gitlab.kitware.com/vtk/vtk/-/merge_requests/8964 can be merged, too, and then will backport both issues (and a few other minor ones) together.
