### ISSUE TITLE
Markups names' consistency

### ISSUE THREAD

**Issue by spujol** [Slicer/Slicer#5196]
When a Markups element is created from the Create menu in the Markups module, the element is named MarkupsElement (e.g. MarkupsFiducial, MarkupsPlane,  etc.). When the same element is created from the top banner in Slicer's main GUI, the element is named 'F' for fiducials, 'P' for planes. (Slicer4.11.0-2020-09-2020 on MacOSX 10.14.6).

Could the names of the markups be harmonized for consistency purpose?

<img width="1680" alt="Screen Shot 2020-09-22 at 4 39 02 PM" src="https://user-images.githubusercontent.com/1847492/93898550-9e38da80-fcf3-11ea-83c0-323011a90701.png">

**Comment by pieper** [comment]
+1. The shorter names are better.

**Comment by jamesobutler** [comment]
The one weird case with the shorter names is that you get "C" and "C_1" when you have mixed open curve markups and closed curve markups. 

I would prefer consistency in the form of default names like "Fiducial", "Line", "Angle", "Curve", "ClosedCurve", "Plane". This is more descriptive than the single letter, but less descriptive by dropping the preceding "Markups" term.

![image](https://user-images.githubusercontent.com/15837524/93944116-fecf1400-fd01-11ea-95e5-7d9675965314.png)

![image](https://user-images.githubusercontent.com/15837524/93944150-11e1e400-fd02-11ea-8091-587b88961ca9.png)

**Comment by lassoan** [comment]
By default, control point label is generated from the node name, so fiducials must have very short (preferably single-letter) node name. For other markup types, longer names are OK (plane, curve, line, angle). To keep things consistent and functional, I don't really see an alternative to very short markup node names. Two-letter node names would probably work, too, so we could use OC and CC if you really think that we must distinguish between open and closed curves.

**Comment by jamesobutler** [comment]
Ok, yes I can see using a very short name for the vtkMRMLMarkupsFiducial node type since there is usually a label for every control point.  The other node types don't have a label for every control point which allows for more descriptive names like "Curve" and "ClosedCurve" to work.

I must say that it has been confusing to users to distinguish that a vtkMRMLMarkupsFiducial node is really an object that contains a list of Fiducials (aka control points).  Where a fiducial node is "F" with control points "F-1", "F-2", but then also a second node of "F_1" that has control points "F_1-1" and "F_1-2".  Something that defines it clearly as a "FiducialList" might help clarify that point.

**Comment by RafaelPalomar** [comment]
This is something that can be done in the pluggable markups PR (#5349). There, we have changed hard-coded names by variables that will make easy to bring naming consistency.
