### ISSUE TITLE
MultiVolume Rendering quality is very low if volume spacing is small

### ISSUE THREAD

**Issue by SlicerMorph** [Slicer/Slicer#5238]
[Give a short summary of what the problem is]
Description from https://discourse.slicer.org/t/multi-volume-rendering-bug/13939/5?u=muratmaga

`The problem is that automatic sampling step computation does not work in the multivolume renderer, so the image spacing has to be approximately 1 to get good-quality rendering. `

## Environment
- Slicer version: Slicer-4.11-2020-09-30
- Operating system: Windows

**Comment by lassoan** [comment]
Slicer always instructed VTK to use adaptive rendering quality, which ended up choosing somewhat lower quality rendering (larger sampling distance) than the default single-volume volume renderer. When I’ve fixed this logic it turned out that the automatic sampling distance computation in the multi-volume renderer computes the sampling distance based on the very first volume. In Slicer, this volume is an empty volume because VTK has a bug that the first volume’s transform is not taken into account. I’ll have to see if it is easier to fix the issues in VTK or develop more complicated workarounds in Slicer.

**Comment by lassoan** [comment]
The issue was reported again on the Slicer forum: https://discourse.slicer.org/t/can-multi-volume-rendering-with-two-volumes-overlapped-imporved-performance/24267/4
