### ISSUE TITLE
Segment Editor: Add warning (overridable) when user hits "Apply" on not-visible segment

### ISSUE THREAD

**Issue by hherhold** [Slicer/Slicer#5259]
I will sometimes inadvertently hit “apply” on an editing operation with a segment that is not visible. This results in a rather long delay, followed by “undo”, to get back to where I was.

It would be nice to have a warning dialog that lets you know the selected segment is not visible, and do you wish to proceed. As noted by @lassoan, this should be a Yes/No dialog with a "Do not show again", as this behavior (being able to modify segments that are not visible) is desired in certain situations.

**Comment by hherhold** [comment]
@lassoan - You mentioned "It would be a helper function in C++ that could be called using a single line from both C++ and Python scripted effects."

Is the idea to add a new dialog in Base/QTApp, similar to qSlicerAboutDialog, qSlicerErrorReportDialog, etc, or something less heavyweight? It's likely to only be called from Segment Editor effects, so it probably makes more sense to implement it somewhere in Modules/Loadable/Segmentations/EditorEffects?

Thanks!

**Comment by lassoan** [comment]
> Is the idea to add a new dialog in Base/QTApp, similar to qSlicerAboutDialog, qSlicerErrorReportDialog, etc, or something less heavyweight?

It is specific to segmentations and it is a widget, so it should be implemented in Modules\Loadable\Segmentations\Widgets. Since confirmation popup dialog with "do not show again" checkbox is already implemented in CTK, we don't need a new class, just a helper function in qMRMLSegmentEditorWidget. Name could be `bool confirmCurrentSegmentVisible()`. This method would show a popup if the current segment is not visible and return with true if the current segment is visible or the user confirmed he wants to operate on a hidden segment. It could be implemented similarly to the scene close confirmation popup (https://github.com/Slicer/Slicer/blob/master/Base/QTApp/qSlicerMainWindow.cxx#L727-L753). The method would be called in "Apply" methods of segment editor effects.

I would also consider having 3 buttons: "Currently selected segment is hidden. Would you like to make it visible? Yes, No, Cancel"

**Comment by hherhold** [comment]
Got it. Thanks!

**Comment by hherhold** [comment]
Hi Andras,

I have everything finished and working. I'm trying to merge HEAD back into my fork before my pull request, but the pre-commit git hook is failing on Docs/user_guide/getting_started.md with lines longer than 80 chars.

Should I fix this file and add it to my pull request?

Thanks!

**Comment by jcfr** [comment]
I gonna push an update to the hook to ignore .md files, once done you should be able to rebase and rerun the setup Development

**Comment by hherhold** [comment]
OK, thanks! So once that is in, I should just do a 'git rebase master'? I'm still very much behind the curve on git...

**Comment by lassoan** [comment]
This sounds great, looking forward to your pull request.

In the meantime, you can just locally modify (or temporarily remove) Slicer\.git\hooks\pre-commit.

**Comment by hherhold** [comment]
OK, pull request is in. Comments/critiques welcome!!

**Comment by jcfr** [comment]
> OK, thanks! So once that is in, I should just do a 'git rebase master'?

```
git checkout master
git pull origin master
./Utilitis/SetupForDevelopment.sh
```

Then

```
git checkout seg-ed-apply-warning-dialog
git rebase master seg-ed-apply-warning-dialog
```
