### ISSUE TITLE
Multi-volume rendering much slower using VTK9

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#5312]
Rendering became much slower in VTK9 using multi-volume. Using 4.11.20200930 the CTChest dataset renders with 35 FPS, and r29477 built with VTK9 only 4 FPS.

## Steps to reproduce

* Use Slicer with VTK9
* Load CTChest sample data
* Turn on Volume rendering with Multi-volume technique
* Rendering is very slow, at 4 FPS (on a 2070 GTX)

## Expected behavior

* Rendering is continuous (CTChest dataset renders with 35 FPS)

## Environment
- Slicer version: r29477 built with VTK9
- Operating system: Windows 10

**Comment by jcfr** [comment]
@cpinter Could you give another try building https://github.com/Slicer/Slicer/pull/5381 ?

**Comment by jcfr** [comment]
> @cpinter Could you give another try building #5381 ?

Looks like there are issues building the PR on windows (see https://github.com/Slicer/Slicer/pull/5381#issuecomment-757349976), could you simply try to buid Slicer master instead ?

**Comment by cpinter** [comment]
I updated and built Slicer master with VTK9. This is what I found:

* Load CTChest
* Show volume rendering using Multi-volume and set the CT-AAA preset
  * FPS = 30
* Switch to standard GPU volume rendering
  * FPS = 35
* Switch back to Multi-volume
  * FPS = 4

If I do the same thing with a VTK8 build it crashes so cannot tell if FPS drops the same way or not. I will investigate some more.

**Comment by jcfr** [comment]
Thanks for the follow up. This is very informative as the first time multi volume is enabled, perf is reasonable.

Maye be relayed to resources clean up ?

**Comment by cpinter** [comment]
> May be relayed to resources clean up ?

Yes this is a reasonable assumption. Maybe it is also why the above steps lead to crash in the VTK8 build (I confirmed it with the latest nightly as well).

**Comment by lassoan** [comment]
Crash at volume rendering switching happy ns due to a missing null-pointer check in VTK. I've fixed in already in VTK master but it is not in Slicer's VTK yet. I don't think it is related to resource cleanup, but of course independently from this cleanup can be broken, too.

@cpinter can you check how GPU memory changes as you switch between volume renderers? In recent Slicer versions you can also enable cleaning up volume rendering actors when you hide the volume (option in Application Settings). You could try to just hide and show a multi-volume rendering and see if you see the same kind of slowdown.

You could also try if enabling/disabling depth peeling has any effect.

**Comment by cpinter** [comment]
> check how GPU memory changes as you switch between volume renderers

There is no increase in GPU memory usage as I switch between methods.

> try to just hide and show a multi-volume rendering and see if you see the same kind of slowdown

Yes the same slowdown happens. It slows down to 4 FPS after the first hide/show, then no matter how many times I do it, it stays 4 FPS.

> You could also try if enabling/disabling depth peeling has any effect.

It does not seem to have any effect (I tried turning if on/off after the slowdown happened)
