### ISSUE TITLE
Linking 3D views breaks after closing scene

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#5406]
After closing the scene, the linked 3D views do not behave correctly. Although the views are synchronized when interacting with the second view, when interacting with the first view it does not.

## Steps to reproduce

* Switch to Dual 3D layout
* Link 3D views
* See that when interacting in either 3D view they are synchronized
* Close the scene
* Link 3D views
* Interacting in the left view does not synchronize

## Expected behavior

Interaction in either 3D view should synchronize.

## Environment
- Slicer version: Slicer-4.13.0-2021-01-25
- Operating system: Windows 10

**Comment by cpinter** [comment]
Same thing happens if you import a scene where the 3D views are linked:

* Switch to Dual 3D layout
* Link 3D views
* Add two fiducials so that after loading the scene a meaningful bounding box is used
* Save scene
* Restart Slicer
* Load scene
* Interaction in left view does not synchronize

**Comment by lassoan** [comment]
Yes, this limitation has been around since the feature was developed. I think this describes the same issue: https://github.com/Slicer/Slicer/issues/4680

@jcfr has rebased one of my old branches that cleans up view creation that might help with this issue. @jcfr can you tell where this branch is? Maybe @cpinter could try if it fixes the problem.

**Comment by jcfr** [comment]
> can you tell where this branch is?

See https://github.com/Slicer/Slicer/pull/5410

**Comment by Punzo** [comment]
Yeah the bug is there from 3 years ago when I implemented at the project week, sorry I should have at least documented somewhere. Unfortunately I never had the time to have a look for fixing it (and I silently avoided it 😬) and i know it can be annoying. If I remember well the bug was related to how the 3d view are initialized, but since the linking system is really similar to the one of the 2d views, it should be possible to fix it. In the next weeks if i find some time, I'll try to dedicate some time.

**Comment by jcfr** [comment]
Good news. Problems described in both https://github.com/Slicer/Slicer/issues/5406#issue-795279113 and https://github.com/Slicer/Slicer/issues/5406#issuecomment-768431980 are addressed by https://github.com/Slicer/Slicer/pull/5410

**Comment by cpinter** [comment]
I confirm that with in the latest version (after fixing the build error, see https://github.com/Slicer/Slicer/pull/5435) both use cases I reported works well. I'm closing this issue.
