### ISSUE TITLE
Add "Update Extension" option under Manage Extensions 

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#5470]
An addition the issue #5469, i think it would be good to have a mechanism to let users know when their installed extensions become stale for the stable versions. Something like this would be a good way:

![image](https://user-images.githubusercontent.com/21285140/108403161-45eb0380-71d3-11eb-8ca3-26cac3d33cbc.png)

**Comment by lassoan** [comment]
This is already implemented:

![image](https://user-images.githubusercontent.com/307929/108404232-9d966880-71ed-11eb-8b6b-f600054d8970.png)

![image](https://user-images.githubusercontent.com/307929/108404244-a0915900-71ed-11eb-89df-3c52faad8425.png)

Previously there was no caching of server answers, which overwhelmed the extension manager and so we did not want to check for updates automatically (which would have further strained the server). Since I've added caching in the extensions manager a few months ago, everything is much faster and robust (see extensions manager in Slicer Preview Release), so maybe now we can enable automatic update check (or even automatic updates). I think the feature is still there, just disabled by default.

**Comment by lassoan** [comment]
Auto-update of extensions at startup (display of a popup that updated extensions are available) is currently disabled, because it caused crashes - see https://github.com/Slicer/Slicer/issues/4641.

I think the crashes do not occur anymore, but to be safe, we could run the check when the extensions manager is opened.

**Comment by muratmaga** [comment]
Didn't know. This is awesome. I would argue against auto-update of extensions. perhaps a check to notify a user, but don't update it without giving them consent. 

Also, is there a similar mechanisms exists for checking whether there are any back ports applied to stable since you install? I do not know how often that's the case, but I think you guys do it from time to time ?

**Comment by lassoan** [comment]
> Also, is there a similar mechanisms exists for checking whether there are any back ports applied to stable since you install? I do not know how often that's the case, but I think you guys do it from time to time ?

We update extensions for latest stable release every night. This is exactly why the "Check for updates" feature is useful.

For preview releases, we only create updated extension packages for the latest version. If Slicer is not changed for a few days then it is possible that you happen to get some updates, but in general if you want to have updated extensions for a preview release then you need to upgrade the Slicer release itself.

**Comment by pieper** [comment]
I think @muratmaga was asking if we notify users of the stable release that there's a new stable available and the answer to that is no, but it's an idea we should revisit.  The "check for updates on startup" idea comes up from time to time in part because it would give us an idea how often the program is being used based traffic to this update check.  We're always concerned about this seeming like spying on the users, so we'd be sure to make it optional.  But opt-in or opt-out?

**Comment by lassoan** [comment]
@jcfr is the new extension manager backend or download page going to have a way to respond to Slicer core update checks and also collect the data as an indication for usage statistics?

**Comment by pieper** [comment]
> We're always concerned about this seeming like spying on the users, so we'd be sure to make it optional. But opt-in or opt-out?

Answering myself here I think we should detect the first time Slicer is run on a machine and put up a dialog asking if they want us to auto-check for updates of the app and of any installed suggestions with the default being yes.  We can include a note that statistics will be collected to help improve Slicer.

The statistics would be very helpful for us, since we'll be able to track how often Slicer is run and what extensions people have installed as well as how quickly they respond to new releases of the main app and each extension.

**Comment by muratmaga** [comment]
It might be best two disentangle these two things. I don't see how they are connected. 

1. Sending usage stats and tracks (which can indeed be like spying, if the user has not opt in)
2. Checking for an updated versions of already installed extensions. There is nothing spying in there, all it needs to do get the latest build number from extension server, compare it to the installed one and notify user. No user information ever transmitted, and it is sort of an expected behavior nowadays.

I am not again #1 above, but perhaps the way to go about it is to ask this question explicitly during the install time and if the user gives permission enable it. Provide a docs page of whats collected, and let them know that they can opt-out anytime via the Application Settings.

**Comment by pieper** [comment]
@muratmaga they are connected because the server logs related to number 2 automatically result in number 1.  We could decide to delete that data regularly, but I think using those logs is a simple way to get some valuable information, like we already do for the downloads themselves.

**Comment by muratmaga** [comment]
> @muratmaga they are connected because the server logs related to number 2 automatically result in number 1. We could decide to delete that data regularly, but I think using those logs is a simple way to get some valuable information, like we already do for the downloads themselves.

But how is this different than any extension install? AFAIK currently, we do NOT inform the user that we will collect any information when user installs an extension. If the permission is implicit (because they chose to download something extra), so should be the check for update. When I refer telemetry (#1), I was thinking of OS build, amount of RAM, processor(s), GPU, screen resolution, amount of space, installed extensions, actively used modules etc... Not the typical footprint one leaves when visiting any website (geolocation, IP, browser etc). 

If these are already being transmitted to the server by the act of installing an extension, I would say we should inform the user.

**Comment by pieper** [comment]
> When I refer telemetry (#1), I was thinking of OS build, amount of RAM, processor(s), GPU, screen resolution, amount of space, installed extensions, actively used modules etc... Not the typical footprint one leaves when visiting any website (geolocation, IP, browser etc).
> 
> If these are already being transmitted to the server by the act of installing an extension, I would say we should inform the user.

Right now the user explicitly initiates the action of checking for updates so the regular IP logging can be expected and that's all we do, not the telemetry data you cite (except installed extensions and OS type).  Automatically checking for updates is a little more intrusive since it de facto tells us how often they run the program, but generally it is expected behavior these days and it provides a user benefit in exchange for the small loss of privacy.  Even though users should be able to deduce that we are gathering these statistics it's still fair to mention it when offering to enable auto update checking.

**Comment by muratmaga** [comment]
>  Automatically checking for updates is a little more intrusive since it de facto tells us how often they run the program, but generally it is expected behavior these days and it provides a user benefit in exchange for the small loss of privacy.

I would suggest not checking every time Slicer opens, but simply have a schedule (weekly, monthly) like many other software does. This would decouple how often the application is used vs update. Personally, I start Slicer about a couple dozen times a day for varying amounts of times, I don't think you want the server to get bogged down with that logs anyways.

**Comment by pieper** [comment]
To me, checking every time is a nice tradeoff of functionality (users know asap when there's something new) and a little bit of data contribution to the statistics (which they can easily opt out of).  Technically, if we disconnect checking for updates from running the app we would need to design some kind of background time-based program and that could be a pain to debug across platforms.

If server load becomes a concern we could just switch to checking every nth time, but realistically I think we could check every time with little impact on the servers relative to the valuable statistics.

**Comment by jcfr** [comment]
@lassoan  Here is the how list of extension for a given revision/arch/os could be retrieved:

```
https://slicer-packages.kitware.com/api/v1/app/5f4474d0e1d8c75dfc705482/extension?app_revision=30493&os=linux&q=&limit=0
```

Metadata are collected within the same call.
