### ISSUE TITLE
SegmentEditor Redo does not restore segment visibility

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#5533]
When undoing segment creation and then redoing, the segment visibility will be off, thus the user does not actually see the action redone.

## Steps to reproduce

https://user-images.githubusercontent.com/1325980/111513282-8b560e80-8748-11eb-8fb5-b58cdd97c70c.mp4

## Expected behavior

Segment visibility should be on so that the redo action is fully successful.

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10

**Comment by lassoan** [comment]
Undo/redo should not manage display settings, so it is normal that redo does not change visibility. The problem is that the segment is recreated as hidden (regardless of what was the visibility of a segment that undo removed; redo should recreate it as a visible segment). This is a regression since Slicer-4.11.20209030 (there segments recreated by redo are always visible).

**Comment by cpinter** [comment]
@lassoan do you have an idea from the top of your head what could cause this? I am happy to look into it but if you have some pointers that would help. Thanks!

**Comment by lassoan** [comment]
I don't have anything specific in mind what could cause it. @Sunderlandkyl fixed issues in segment list widget updates and maybe as a side effect some events are now missed or emitted in a different order. Need to run this in a debugger and see what changes the visibility flag (or why it is not initialized to true)

**Comment by cpinter** [comment]
Thanks, I'll investigate this early next week, probably something relatively simple...

**Comment by lassoan** [comment]
A very similar error has come up when loading .nii.gz files as segmentation. I have a fix that I'll test a bit more and push soon.
