### ISSUE TITLE
Interactive slice intersections

### ISSUE THREAD

**Issue by cpinter** [Slicer/Slicer#5544]
## Is your feature request related to a problem? Please describe.

There are useful features related to slice navigation bound to hotkeys like Shift+drag for moving the 3D cursor, or Ctrl+Alt+drag&drop for rotation of the slice planes when slice intersections are shown. It would be great to have these features available more explicitly that could be used with the mouse.

## Describe the solution you'd like

Add a new checkbox under the `Slice intersections` one on the toolbar for `Interactive slice intersections`:
![image](https://user-images.githubusercontent.com/1325980/112025995-adc39f80-8b2d-11eb-9154-027b03efac4a.png)

## Describe alternatives you've considered

Improving the crosshair.

## Additional context

This feature is needed in a Slicer custom application in terms of a commercial project. I'm creating this ticket so that the core developers and the community has a chance to comment on this new feature before we start implementing it. The ideal would be to reach a consensus about what would be best overall (usability, versatility, robustness, initial development time).

Details:
- Unlike the intersection lines, the interactive slice representation lines will be drawn from one window border to the opposite, with dash line for the part that does not correspond to the intersection of the planes.
- When the mouse is over the line, a widget appears with translation arrows under the mouse and rotation arrows close to it, with the tip of the arrows oriented towards the center of intersection
- If we click on the translation arrows and move the mouse, the line is translated (these are under the mouse so that this basic feature can be done basically by quick drag&drop)
- If we click on the rotation arrows and move the mouse, the 2 lines are rotated to keep the current angle (the user would need to move the mouse to get to these arrows providing the more advanced feature)
  - There is no distinction for the direction of the movement, both sides of the arrows allow to move in both directions
- When the mouse goes close to the intersection center, the widget representation is different (circle at the center, 4 arrows ?) and we can translate both lines (like pressing Shift key)
- When the mouse is over an handle it is highlighted
- When we click on the widget and start moving the mouse, the widget representation is hidden or made mostly transparent (not the lines) to see the underlying image
- We would like to have access to some interaction events, like StartInteractionEvent, ModifiedEvent, EndInteractionEvent at least.

Questions:
- Do we add specific events like StartTranslationEvent, or should we retrieve the widget and get its interactive state, or active handle type?
- Should we restrict the interaction to the window ? for example if we are translating a line, should we pause (not stop) the translation while the mouse goes out of the window and continue it when the mouse enters it again, to avoid loosing the plane far from the volume?

Here is a sketch. Please note that these widgets would not appear all at once, only when hovering the line. Also the lines would resemble more the widgets that are used for markup translation/rotation (we plan to base this on that code).
![image](https://user-images.githubusercontent.com/1325980/112027163-d5ffce00-8b2e-11eb-82fb-6788806d9f19.png)

**Comment by lassoan** [comment]
This will be awesome!

> Do we add specific events like StartTranslationEvent, or should we retrieve the widget and get its interactive state, or active handle type?

Yes, you would add events and states for each mode. Use "offset" term when you move a slice (similarly to the slice offset slider). I would use "translate" when you may also pan the slice.

> Should we restrict the interaction to the window ? for example if we are translating a line, should we pause (not stop) the translation while the mouse goes out of the window and continue it when the mouse enters it again, to avoid loosing the plane far from the volume?

You always need to capture the mouse events during click-and-drag (otherwise you would not get the notification about mouse button release and things would become more complicated for both developers and users).

>  the lines would resemble more the widgets that are used for markup translation/rotation (we plan to base this on that code).

@Sunderlandkyl Please advise on how to refactor markups handles so that they can be used for this slice widget (and later for the 2D and 3D transform widget).

Please keep in mind these future requirements (no need to implement it now but make design decisions that are compatible with these):
- Widget will need to show the slice thickness (rectangle instead of a solid line) and there should be a handle to adjust the slice thickness
- Slicer offset/rotate widget will be needed in 3D views, too (show slice borders with slice color, drag-and-drop the slice by its border to offset or rotate)

@jcfr might add more of these future requirements that he got from Doug Porter (Mayo Clinics).

**Comment by xriobe** [comment]
> You always need to capture the mouse events during click-and-drag (otherwise you would not get the notification about mouse button release and things would become more complicated for both developers and users).
>
The mouse events are still captured but the line could be forced to have the "projected point of the mouse cursor on the line" inside the window (so worst case only the pixel in the corner).

> * Widget will need to show the slice thickness (rectangle instead of a solid line) and there should be a handle to adjust the slice thickness
> 
These are additional features that could come later:
- for the thickness i suggest keeping the center line and display the rectangle with transparency, or only small ones at each extremities of the line
- there could also be a representation for multi-slices if there are some in a layout, with either dashed lines for the first and last, or one small segment for each slice

**Comment by Sunderlandkyl** [comment]
> Please advise on how to refactor markups handles so that they can be used for this slice widget (and later for the 2D and 3D transform widget).

For display, the rendering pipeline for the current Markups interaction handles is in the mostly handled by the MarkupsInteractionPipeline class in vtkSlicerMarkupsWidgetRepresentation (as well as subclasses for specific representations in the same directory), and is controlled by the display options in vtkMRMLMarkupsDisplayNode. To use the same infrastructure, it would probably be enough to move the base class and display options to a lower level.

Widget states (WidgetStateOnTranslationHandle, etc.) and event translations for each of the interaction handle types would need to be moved to a lower level as well (from vtkSlicerMarkupsWidget).

**Comment by lassoan** [comment]
Please also consider fixing this issue: https://github.com/Slicer/Slicer/issues/4383
In short: when slice views are (close to) parallel then slice intersection line display becomes erratic. Instead, when slice views are almost parallel then the slice "intersection" should be displayed as a rectangle.

**Comment by pieper** [comment]
Be sure to try out other implementations for inspiration.  In OHIF the intersections look nice because the handles are subtle.  Follow the link below and click the "2D MPR" button in the toolbar to bring them up.

https://viewer.imaging.datacommons.cancer.gov/viewer/1.3.6.1.4.1.14519.5.2.1.1706.4001.149500105036523046215258942545?seriesInstanceUID=1.3.6.1.4.1.14519.5.2.1.1706.4001.315980779833795710131738723922

**Comment by finetjul** [comment]
You may face some question about what must be done with the view up. Because when you rotate a line, there are an infinite number of rotations you can apply. Should the viewUp be preserved or should it be rotated as well (and how). OHIF has a nice way to handle it. We ended up doing the same in [VTK.JS](https://kitware.github.io/vtk-js/examples/ResliceCursorWidget.html) and recently in VTK (see the recent reslice cursor changes [here](https://gitlab.kitware.com/vtk/vtk/-/commit/ff79a1d567abdb3a740b061d30880e3e6aff4b60)  and [here](https://gitlab.kitware.com/vtk/vtk/-/commit/0e0af1b9a9a96efafcf8ce863ff87a3e67b665e3))

**Comment by lassoan** [comment]
Yes, choosing optimal view-up direction is tricky. There is a simple implementation for Slicer [here](https://slicer.readthedocs.io/en/latest/developer_guide/script_repository.html#set-slice-position-and-orientation-from-a-normal-vector-and-position), but unfortunately the ideal solution depends on the clinical use case (you may have to be similar to C-arm angles, in cardiac ultrasound imaging you need to follow standard ultrasound probe orientation conventions, etc.).

There are a few details, such as if you want to make the view up direction defined by the slice normal direction only (useful if you also want to provide sliders to change the orientation) or if you want it to depend on previous state as well (useful if you want to avoid unnecessary flips). It is also preferable to create smooth transitions instead of sudden flips.

For now, it would be enough to create a separate class that computes the rotated slice directions. Later we can add interface for developers to register their own class and add GUI for users to choose between rotation modes.

**Comment by rbumm** [comment]
It would be great if you could restrict (block) the movements around an axis if the user desires to do so.  This would restrict the 3D image from tumbling. 

Looking forward to the results!

**Comment by lassoan** [comment]
@rbumm this issue is not about rotating the 3D view's camera but about rotation of slice views. You can submit a feature request for adding alternative 3D camera rotation modes.

**Comment by xriobe** [comment]
The OHIF one is good and sober (but the handles sketched here will be too in the final version).

The advantage of the solution presented here is that it avoids the situation like in the following OHIF screenshot where the rotation handles are not present anymore:
![image](https://user-images.githubusercontent.com/66792993/123837486-301ce600-d90b-11eb-9604-f648493d75cc.png)

The drawback is the 2 actions needed to make them appear (hover the line then hover the rotation handle).

We can also argue that in the case of the 2 lines intersection not being in the visible part of the image, the user would not try to rotate anything because he would not know what he is doing ...

So i guess the best choice would be the more evolutive and/or easier to develop/maintain solution, both being acceptable.

**Comment by lassoan** [comment]
>> When in "Place" mouse mode then the translate/rotate arrows either should not show up or they should work (move the slice intersection instead of place a point). Probably it makes more sense to place the point and not show the arrows.

>To solve this issue, I just enable interaction with the handles when the current interaction mode is vtkMRMLInteractionNode::ViewTransform. Therefore, handles will not appear when placing fiducials ("Place" mode) or modifying the window/level ("Select" mode). It makes sense to deactivate the handles when changing the window/level, right?

When you hover over a widget then it is expected to be interactive, regardless of the mouse mode. The handles should be shown when the widget has the focus. When you hover over a widget then typically it gets the focus, except when you are in place mode because then typically the widget that is being placed claims the focus (by returning 0.0 distance from `canProcessEvent` method).

> For the rotation, I kept the hand cursor (VTK_CURSOR_HAND) since I did not find any rotation cursors in VTK. Do you have any experience creating custom VTK cursors? One option is to generate custom cursors using icons, such as the cursor for markups control point placement. What do you think?

I don't think VTK can support custom cursor images. You can use the hand cursor for now. We'll have to update cursor handling to allow defining cursor by a string that will be retrieved from a resource and set as cursor using Qt classes.

> What do you mean by "single Slicer intersection on/off flag"?

I meant that we would have a single checkbox for turning on/off slice intersections. If it is off then no intersection would be shown. If it is on then its appearance (size, thickness) and behavior (interactive or not) would be controlled by additional checkboxes/radio buttons.

> Any ideas on how to detect if a markups control point is being currently dragged?

The solution is the same as for the handles incorrectly appearing in place mode: the handles should be only shown if the widget has the focus.

>> Need a way to rotate a single slice (not all of them). It could be a using a keyboard modifier (e.g., Ctrl+Left-click-and-drag)

> Do you mean something similar to the interaction Ctrl + Left-click-and-drag in the current 3D view? (See image below). If so, the slice could be rotated together with the lines.

I mean that by default all slice intersections should be rotated (so that they remain orthogonal). But sometimes you want to rotate only a single slice - the one that you have clicked on. Since most of the time you want to rotate all, you can make click-and-drag rotate all, and Ctrl + click-and-drag rotate only one.

**Comment by cpinter** [comment]
Pull request https://github.com/Slicer/Slicer/pull/6124 merged. Thank you so much @lassoan and @dgmato !

I'll build, do some testing, and close it if it looks good.

**Comment by lassoan** [comment]
Thank you. Please also create a topic on discourse to announce the feature (in Support category, with the "feature" tag added) with a few screenshots or videos.

**Comment by cpinter** [comment]
@dgmato Can you please make the announcement once your build is finished and you can make some brief captures (gif style) about the main features? Thanks!

**Comment by lassoan** [comment]
If possible, please use mp4 (drag-and-drop the mp4 file into the discourse post), as it is higher quality than gif, yet smaller in size, and replay can be paused and you can seek to any point in the video. Thank you!

**Comment by cpinter** [comment]
Yes. What I said was "gif style" that was supposed to refer to length but it's good to clarify.

**Comment by dgmato** [comment]
@lassoan @cpinter I've just posted the announcement in discourse describing the new feature and including a short video I recorded.

**Comment by cpinter** [comment]
For the record the announcement: https://discourse.slicer.org/t/interactive-slice-intersections/21677

I tested the latest master and this feature works well.

The view grouping seems to do things I wouldn't expect in comparative layouts (like three over three), but it is not related to this work.
The unexpected thing is that if I link the views and set the other volume on the bottom row after switching to the layout, and then moving the mouse over the top row, the view orientations change. In the past I had similar issues but coming from the Slice view controllers module. If needed I can create a ticket for this. I don't thing this should prevent the release of Slicer5 though.

I'm closing this issue. Thanks everyone!
