### ISSUE TITLE
Memory Issue Segment Editor

### ISSUE THREAD

**Issue by tcrnscw** [Slicer/Slicer#5585]
[Using a resampled volume in segment editor, when trying to use the edit islands effect an application error pops up and asks slicer to restart. This follows the same steps]

## Segment Editor, master volume = resampled volume
Threshold - adjust 246 as lower threshold, keep default upper threshold, apply
Scissors - erase outside, select region of interest
Islands - Keep Largest Island - Error message:

_"Slicer has caught an application error, please save your work and restart.

If you have a repeatable sequence of steps that causes this message, please report the issue following instructions available at http://slicer.org

The message detail is:

Exception thrown in event: D:\D\S\Slicer-1-build\ITK\Modules\Core\Common\include\itkImportImageContainer.hxx:192:
Failed to allocate memory for image."_

## Environment
- Slicer version: Slicer-4.11.20210226
- Operating system: Windows 10 Education Version 
![Screenshot 2021-04-13 123736](https://user-images.githubusercontent.com/82449210/114546771-77250480-9c55-11eb-9814-2394cc7ac210.png)
1809

**Comment by pieper** [comment]
Thanks for the report - it seems you have run out of memory for this operation.  I'm assuming this is due to a volume that is larger than usual.  There are several options.  Easiest would be to add more RAM to your computer or enable bigger virtual memory.  Other options include cropping the volume around the segmented area or downsampling the volume.

If I'm wrong and the volume you are working with isn't especially large then please provide an example and reopen the issue.
