### ISSUE TITLE
Max build path length reached on Windows

### ISSUE THREAD

**Issue by jamesobutler** [Slicer/Slicer#5589]
As observed with the factory build machine and also something I experienced locally, the pluggable markups recent work has increased the build path length resulting in a build error.
https://slicer.cdash.org/viewBuildError.php?buildid=2212103

The factory build machine has been using a root of “D:\D\P\Slicer-0-build” and I have been using a root of “C:/S5R-nightly”.

The default Windows configuration doesn’t support path lengths over 260 by default. There is a registry key that can be changed, but that’s a bit of an unusual thing that most people don’t do.

> C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(325,5): error MSB3491: Could not write lines to file "x64\Release\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy\vtkSlice.48543C92.tlog\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy.lastbuildstate". Path: x64\Release\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy\vtkSlice.48543C92.tlog\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy.lastbuildstate exceeds the OS max path limit. The fully qualified file name must be less than 260 characters. [D:\D\P\Slicer-0-build\Slicer-build\Modules\Loadable\Markups\Testing\Cxx\PluggableMarkupsTestModule\VTKWidgets\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy.vcxproj] [D:\D\P\Slicer-0-build\Slicer.vcxproj]

**Comment by sjh26** [comment]
Yeah, shortening this is going to be the best way to go.  I don't think it is feasible to require a registry key change for user/devs to build locally.

Here is the full path it is trying to write:

`D:\D\P\Slicer-0-build\Slicer-build\Modules\Loadable\Markups\Testing\Cxx\PluggableMarkupsTestModule\VTKWidgets\x64\Release\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy\vtkSlice.48543C92.tlog\vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy.lastbuildstate`

so, about 10 characters over?

**Comment by jamesobutler** [comment]
vtkSlicerPluggableMarkupsTestModuleVTKWidgetsHierarchy is quite the long generated name. 

Maybe `Modules\Loadable\Markups\Testing\Cxx\PluggableMarkupsTestModule` could be reduce to `Modules\Loadable\Markups\Testing\Cxx\PMTestModule` or something?

**Comment by jamesobutler** [comment]
Any thoughts on which option to go with so that the Windows build doesn't fail again tonight?

**Comment by pieper** [comment]
Modules\Loadable\Markups\Testing\Cxx\PluggableMarkupsTestModule

Since the path is already explicitly Markups and Testing the final name could be PluggableModule and still be unambiguous and still shorter.

**Comment by lassoan** [comment]
Filenames should be shortened as well. For example, we could replace "PluggableMarkupsTest" by "PMTest" in all filenames (but file contents, class names, etc. the same).

To be consistent with the filenames, we could rename the module folder the same way. This would make the folder name "PMTestModule", which is the same that @jamesobutler suggested, and shorter and I think as clear as "PluggableModule".

So, I would vote for PMTestModule as parent folder and PMTest in filenames.

**Comment by pieper** [comment]
> This would make the folder name "PMTestModule", which is the same that @jamesobutler suggested, and shorter and I think as clear as "PluggableModule".

There's always going to be a tradeoff and we need to make sacrifices to meet the technical constraints, but if I were looking at the code for the first time PM would be completely meaningless whereas seeing a word like Pluggable or Plugin or even just Plug would give me a clue, especially if I'm in a hierarchy that includes Markups and Testing.

We do use long identifiers, sometimes we go overboard, but in general we need them to avoid name clashes when files get installed (like in qt-scripted-modules in install tree where the source context is missing).  We just need to think about these as written communication and not just unique identifiers, so they should be short but meaningful.  Another example is MRML Displayable Managers, which is descriptive but due to space we have directories called MRMLDM which is pretty random to a newcomer.  In retrospect we might have called them Displayers or something.

**Comment by jamesobutler** [comment]
Seems like it should’ve at least been “MarkupsPlugin” considering the word “Plugin” has been used before rather than the term “Pluggable”.

**Comment by jamesobutler** [comment]
What if the directory in question is moved up to the Markups module directory level? It appears that is PluggableMarkupsTestModule more of an example module as it doesn't actually have tests to be run?

`Modules\Loadable\Markups\Testing\Cxx\PluggableMarkupsTestModule` to
`Modules\Loadable\Markups\MarkupsPluginTestModule` (slight name change to "Plugin" term instead of "Pluggable")

**Comment by jcfr** [comment]
> What if the directory in question is moved up to the Markups module directory level? It appears that PluggableMarkupsTestModule is more of an example module as it doesn't actually have tests to be run?

That makes sense.

We could even add it to https://github.com/Slicer/Slicer/tree/master/Utilities/Templates/Modules and run the wizard as part of the test (example [here](https://github.com/Slicer/Slicer/blob/master/CMake/SlicerExtensionTemplatesGenerator.cmake))

**Comment by lassoan** [comment]
It would be nice to make this a template - that would make it easier for developers to create custom markups.

@jcfr, two questions:
Can tests defined in the template be run as part of the regular test suite?
What is the difference between modules in `Utilities\Templates\Modules` and `Extensions\Testing`?

We should add examples of other plugin interfaces similarly. For example, SlicerScriptedFileReaderWriterTest.py could be formulated as a template, too.

**Comment by jcfr** [comment]
> What is the difference between modules in Utilities\Templates\Modules and Extensions\Testing?

* [Utilities/Templates](https://github.com/Slicer/Slicer/tree/master/Utilities/Templates): This directly contains templates for both extension and modules

* [Extensions/Testing](https://github.com/Slicer/Slicer/tree/master/Extensions/Testing): These are "instantiated" templates based of ether the `Default` extension template and `including a selection of modules. They can be regenerated building the target `SlicerGenerateExtensionTemplates` defined in https://github.com/Slicer/Slicer/blob/master/CMake/SlicerExtensionTemplatesGenerator.cmake

**Comment by jcfr** [comment]
> Can tests defined in the template be run as part of the regular test suite?

To support this we would have to "instantiate" the template are configuration time and then called `add_subdirectory` to include the generated directory.

Based on the current infrastructure, using the extension  wizard are configuration  time is not possible because the Slicer executable and `slicerExtensionWizard` module would have to be first configured and built:
* https://github.com/Slicer/Slicer/blob/08789e8f2224f89206b2d6a49d1d452d4e677994/Utilities/Scripts/CMakeLists.txt#L15-L19
* https://github.com/Slicer/Slicer/blob/08789e8f2224f89206b2d6a49d1d452d4e677994/Utilities/Scripts/slicerExtensionWizard.sh.in
* https://github.com/Slicer/Slicer/blob/dd5b27fc7c46eb43225910c0ff3831e5f3d7c41c/Modules/Scripted/CMakeLists.txt#L18

To address this, we could look into:
* transitioning template to use `cookiecutter` convention
* avoid explicit dependency on the extension wizard to simply "instantiate" module templates

**Comment by lassoan** [comment]
I don't understand much of this latest comment, but I would assume that we could instantiate the templates in a prerequisite test in a way that the instantiated modules would make up an extension. Then this extension could be then built and tested similarly to py_cmake_slicer_extensions_index_build* tests.

**Comment by jcfr** [comment]
> I don't understand much of this latest comment

Say differently, the current extension wizard required Slicer to be built. This means that:
(1) it can not be used at configuration time
(2) test listed in the module being "instantiated" from the template can not be run as part of the regular Slicer tests

> in a [...] test

Good point, we could simply have a "proxy" test that would be responsible for:
- use the wizard to instantiate the template
- configure, build and execute relevant tests

**Comment by lassoan** [comment]
We should make a change today that goes towards this direction and allows the nightly build to succeed.

**Should I just move the module to Utilities\Templates\Modules and thus exclude from testing from now?**

According to conventions in that folder, the name of the parent folder would be `LoadableCustomMarkups` and the module name would be `TemplateKey`.

**Comment by jcfr** [comment]
> Should I just move the module to Utilities\Templates\Modules (and thus, for now, exclude the module from testing)?

Moving the module there and renaming it makes sense.

For now, ,we could ensure the code is built by updating https://github.com/Slicer/Slicer/blob/master/Utilities/Templates/CMakeLists.txt and adding the following at the end:

```
# See https://github.com/Slicer/Slicer/issues/5589#issuecomment-820645257
add_subdirectory(Modules/LoadableCustomMarkups)
```

**Comment by lassoan** [comment]
Sounds good to me.

@jamesobutler you have gone through a module renaming already. Would you be willing to do one more rename and moving to https://github.com/Slicer/Slicer/blob/master/Utilities/Templates? (I completely understand if you have had enough of these renames already, I'm just asking because since you have just done it, you may have already figured out a good approach to do it and know what to be careful about)

**Comment by jamesobutler** [comment]
Sure let me take try moving it to that directory as such and will @ you all once I push something.

**Comment by jamesobutler** [comment]
8fe45d4d68456df4e34d617838c3a9d3cc599b4a solved the max build path length issue. Factory build machine was successful https://slicer.cdash.org/viewBuildError.php?buildid=2214527
