### ISSUE TITLE
Mouse icon update

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5599]
The mouse icon is not updated when a segmentation tool is clicked, and then you try to change the Window/level (for instance).

## Steps to reproduce
Load a volume
Create a segment
Click on paint tool
Paint something ... Now you want to change de window/level (paint still active)
Click on Window/level toolbar icon

After clicking on the Window/level toolbar icon, we can effectively change the Window/level  BUT the mouse icon is not correct (default arrow)

## Expected behavior
We should have switched to Window/level interaction mouse icon

**Comment by jamesobutler** [comment]
Indeed I was able to replicate. Using a segment editor effect with its own mouse icon and then clicking to change into a different mouse interaction mode such as WindowLevel or toggling into Placement mode for any of the markups. The mouse icon isn't set to the correct one. It is set to the plain mouse arrow cursor.

Key detail is going into different interaction mode while a Segment Editor effect with a custom mouse icon is active. When toggling to a different interaction mode, the active Segment Editor effect does go to the "None" effect automatically. So that might be a culprit that is resulting in the mouse icon being set to the plain mouse arrow cursor and possibly overriding the new interaction mode cursor icon such as for WindowLevel.

The issue is present in:
- 3D Slicer 4.13.0-2021-04-15 (Current Nightly)
- 3D Slicer 4.11.20210226
- 3D Slicer 4.11.20200930 

so seemingly has been an issue for awhile now.

**Comment by jamesobutler** [comment]
> Using a segment editor effect with its own mouse icon and then clicking to change into a different mouse interaction mode such as WindowLevel or toggling into Placement mode for any of the markups. The mouse icon isn't set to the correct one. It is set to the plain mouse arrow cursor.

Testing with Slicer 4.13.0-2021-11-05 which includes dd8d8a5650af40601cd85091f23c3f66b86b8ccc, I was not able to see this issue when switching to WindowLevel mouse mode using the toolbar in the UI, but I do still see the issue if I have my segment editor effect icon in the slice view and then I call to switch to AdjustWindowLevel mode programmatically without moving the mouse. 
```python
interaction_node = slicer.app.applicationLogic().GetInteractionNode()
interaction_node.SetCurrentInteractionMode(interaction_node.AdjustWindowLevel)
```
I also still see this issue when going from active segment editor effect icon, to going into control point placement mode using the Markups toolbar or the mouse interaction toolbar.
