### ISSUE TITLE
Segment editor, copy contour to adjacent slice

### ISSUE THREAD

**Issue by ferdymercury** [Slicer/Slicer#5604]
## Is your feature request related to a problem? Please describe.
It is not easy to draw the same contour on adjacent slices.

## Describe the solution you'd like
I would like a tool that allows to copy the segment in the current into the adjacent one using CTRL+C CTRL+V, or something similar. Maybe with some special options / modifiers to add / cut / overwrite what was already there before in the adjacent slice. And with an option to copy to N adjacent slices instead of manually going one by one and pressing CTRL+V

## Describe alternatives you've considered
Fill between slices Tool, but it is too manual.

**Comment by lassoan** [comment]
We experimented with this feature in the past and found that the outcome was:
- First the users fixed the copied contours meticulously. This increased the segmentation time, because fixing a contour is harder and takes more time than creating a new contour from scratch (especially when simple manual tools, such as paint or draw is used).
- When the users started to realize that just how tedious fixing up the contours was, they started to tolerate more errors. They only fixed the propagated contours where they significantly deviated from the underlying image. This resulted in large step artifacts (no change at all for several slices then a big correction).

The result was slower and/or lower quality segmentation than a full manual segmentation without contour propagation.

Reducing segmentation effort by leveraging similarity between neighbor slices is a good idea, but instead of propagating in only one direction and only at a fixed (single slice) distance, we offer a much better method:
- two-way propagation: we propagate segmentation to empty slices from segmentation on both sides, which makes segmentation more accurate by reduces bias
- propagation from arbitrary distances: you can skip as many slices as you want, making segmentation faster
- higher-order interpolation: instead of copying (zero-order interpolation), we use higher-order interpolation function for the propagation, which allows inherently smooth contours in all 3 dimensions (no step artifacts), no follow-up smoothing is necessary, therefore increasing accuracy and preserves all important details
- preview and automatic updates in 3D: if preview shows non-negligible deviation on any slice then the user can segment that slice and the result is updated automatically on all the interpolated slices in a few seconds

This wonder method is the morphological contour interpolation method implemented in "Fill between slices" effect. If you find that this effect is "too manual" then maybe you have not explored all of its features. It is much less manual than propagation of adjacent slices.

If there are contrast differences between structures of interest then there are even more efficient tools, such as Grow from seeds, Local thresholding, Watershed, Fast marching. I would recommend to post your segmentation problem on the Slicer forum (https://discourse.slice.org) to get specific advice.

**Comment by ferdymercury** [comment]
Thanks so much for the thorough reply.

I agree with your point about "real segmentation". But my use case was not for segmenting, but rather for creating a support structure (cradle) that I want to be with the exact same contour on each slice (namely for the 'wall' of the cradle). In principle, I could use the "Scissor tool" by predefining the number of slices to propagate.

However, there is a problem with this approach. I might think that I first want 25 slices. Once I am done with all the drawing, then I turn on the 3D viewer, and I consider that 30 slices would have been better. In other tools like MIM, this is easily achieved using CTRL+C and CTRL+V. In Slicer, I think it would be more intuitive to first use the Draw effect, and than with a "Copy To Adjacent" tool.

What about adding a "checkbox" in the Fill Between slices method, which first creates a virtual extrapolated slice at N slices from where you are, and then interpolates the rest? Then the effect of the algorithm would be similar as having copied N times in adjacent slices the current contour.

**Comment by lassoan** [comment]
This is an interesting use case that other community members need, too, and may have already developed good workflows or dedicated modules for. Instead of discussing this hidden in a feature request, please describe your use case in a new torz on the Slicer forum (discourse.slicer.org). Thank you.

I'll close this issue now and when we converge to a solution based on the forum discussion then we can reopen this issue or create a new one if needed.

**Comment by ferdymercury** [comment]
Thanks. Here a link to the forum post https://discourse.slicer.org/t/copy-contour-to-adjacent-slices/17239
