### ISSUE TITLE
Lost handle interaction after some user actions 

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5607]
When the user interacts with the handle of a markup, some of its actions may stop the interaction. 
## Steps to reproduce

- Create a vtkMRMLMarkupsPlaneNode and activate the interaction option
- Left click and drag the plane node. While maintaining the left click (user is still interacting with the plane node), press the right click  
- Interaction with the plane node is lost

Note: This is the case for all other buttons on the mouse and for the following keys of the keyboard: r,f,g,v.

## Expected behavior

If left mouse click is still active we should not lose the interaction behavior.

## Environment
- Slicer version: Slicer-4.13-0-2021-03-21
- Operating system:  Linux 20.04

**Comment by lassoan** [comment]
The behavior that you described is how things are expected to work. You can only interact with one widget at a time. If you operate one widget (plane node) and you activate a feature in another widget (the [view manipulation shortcuts](https://slicer.readthedocs.io/en/latest/user_guide/user_interface.html#slice-views) are processed by the slice widget) then that new widget takes over and the previously active widget gets deactivated.

Is there a specific task that this behavior makes harder to accomplish?

If you wanted to trigger some actions while dragging a markups widget interaction handle, then you need to process those actions in the same markups widget. This can be done with minimal code changes, as you can specify arbitrary keyboard shortcut -> widget event mapping on any markups (even in Python, without changing any source code), and then assign any operation to that widget event (this currently requires implementing a custom markup or modification of a markup, but this is a small change and if there is a good reason then we can add this custom event handling to all markups in Slicer core).

**Comment by riep** [comment]
For instance when zoomIn or zoomOut other mouse buttons are disabled as long as the right click button is clicked.
I would have expected the same behavior for the left click when position a markupNode.

**Comment by lassoan** [comment]
If a user interface event is handled by the active widget then the active widget decides what to do with it. If the active widget is already in non-idle state then typically it ignores the new user interface event.

However, if a user interface event is triggered that a non-active widget can process but the active widget cannot, then the current widget gets deactivated (therefore finishing whatever it was doing) and the other widget gets active.

This is implemented to give developers flexibility in adding new widgets, while preventing them from interfering with each other. This also allows concurrent manipulation of multiple widgets in multiple context (e.g., one widget is edited by mouse and keyboard, another one is moved by thee left-hand virtual reality controller, and something else is moved by the right-hand virtual reality controller). 

The user does not know what widgets can process what events, so I understand that the behavior is not completely transparent for the user. However, since you cannot perform multiple actions at the same time in the same context anyway, **users just need to know that they may need to finish the current action before they start a new one**.

**Comment by riep** [comment]
Sure I understand. Thanks you Andras for the details. I close this.

**Comment by riep** [comment]
@lassoan I would like to reopen. If losing the interaction is the right behavior, we should at least received a slicer.vtkMRMLMarkupsPlaneNode.PointEndInteractionEvent. For now, nothing is triggered, we just lose the interaction. 
What do you think about it?

**Comment by lassoan** [comment]
PointStartInteraction/PointEndInteraction events are for control points, not for interaction handles. I don't think there are events for interaction handles. If this is what you need (I can see that it could be useful) then please create a feature request for it.

**Comment by riep** [comment]
I am sorry to insist, Andreas. 
Imaging, you are interacting with a planeNode.  PointStartInteraction is triggered, when moving the plane PointModifiedEvent is triggered. 
Then you press a key on your keyboard or right mouse click (while left click still pressed) => No PointEndInteraction is triggered.
Do you think it is the right behavior? If it is, I close this issue.
Pierre

**Comment by lassoan** [comment]
Invocation of PointEndInteractionEvent was indeed missed. I've added it now.
