### ISSUE TITLE
Markups rendering very slow, reading z-buffer and re-uploading data to GPU

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#5618]
I created a scene with a 94 markups lines and it runs at only about 11 FPS.  Measured with Rock mode turned on, but feels the same when interacting.

## Steps to reproduce

[mrb for testing](https://www.dropbox.com/s/6h3076k6i981wa2/slow-markups-2021-04-25-Scene.mrb?dl=0)

## Expected behavior

It should be a very lightweight rendering operation, but some of the features appear to use extra resources.

## Environment
- Slicer version: Slicer-4.13-2021-04-12
- Operating system: Mac + big sur 11.2.3

## Other info

Profiling indicates a big hit is in `vtkSlicerLineRepresentation3D::RenderOverlay` which reads back the Zbuffer with `vtkSelectVisiblePoints` which basically breaks the GPU pipelining.

Also the vtk pipeline that gets triggered by `vtkOpenGLRenderer::UpdateGeometry` during the `vtkOpenGLRenderer::DeviceRender`. takes a chunk of time too and seems to be re-uploading data every frame, although that may be unavoidable.

Time sample file is [here](https://www.dropbox.com/s/d7w4f3c5el5vf5w/Sample%20of%20Slicer%204.13.0-2021-04-12.txt?dl=0).

Turning off the PropertyLabel improves performance to about 14 FPS.

If there is only one markup performance is 60 FPS.

If I put the same number of control points into a single `MarkupNode` there is no obvious slowdown.

Suggestion: we should find a way to only update `vtkSelectVisiblePoints` once per render frame.

**Comment by pieper** [comment]
@Sunderlandkyl @lassoan

**Comment by lassoan** [comment]
Yes, we know about this slowdown and I agree that z buffer should be only retrieved once per rendering. Maybe vtkSelectVisiblePoints could be improved to have a singleton cache that would store the last result for each render window on would only retrieve from the GPU again if needed.

**Comment by lassoan** [comment]
We have run into a similar problem in SlicerHeart, too. It seems that markups cannot widely adopted until we this performance issue is fixed.

@Sunderlandkyl Could you investigate this? First we would need to confirm that the issue is indeed due to vtkSelectVisiblePoints and if that's the case then figure out a way to retrieve the z buffer only once after each rendering and then just use that in all subsequent calls? We could try to collect all the points in a single point set and have one vtkSelectVisiblePoints filter, but it would be probably much simpler if we created a modified version of vtkSelectVisiblePoints that could share the last z buffer.

**Comment by Sunderlandkyl** [comment]
I did some testing on RelWithDebInfo (50 control points):

- Labels hidden: 142fps
- Labels visible, no vtkSelectPoints: 85fps
- Labels visible, only update vtkSelectPoints once per frame: 55fps

Moving vtkSelectPoints update from within RenderOverlay to a post-render callback did not seem to affect the fps.

**Comment by lassoan** [comment]
Have you added one markup with many points? That works well. Rendering slows down enormously when you add many markups.
Try adding 100 markups lines.

**Comment by Sunderlandkyl** [comment]
I think that the performance hit from 142 to 55 fps for 50 control points in a single markup is also quite bad.

It's true that the 100 line markups is quite a bit worse:

- vtkSelectPoints enabled: 9fps
- vtkSelectPoints disabled, property labels shown: 17fps
- vtkSelectPoints disabled, property labels hidden: 20fps

**Comment by lassoan** [comment]
@Sunderlandkyl your changes have been made a huge improvement!

Before we move on, it would be great if you could check a few more things (to ensure that rendering of markups for reasonable-size scenes is feasible - something like 500 markups should be fluid to render even with interaction and label display enabled).

1. vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition

When I attach VerySleepy to a release-mode version (which is not totally reliable) then I keep seeing vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition as a performance bottleneck. Computing the scale factor should be a very inexpensive operation (essentially multiplication with a 4x4 matrix). However, how we compute the scale now (using Renderer->WorldToDisplay) is very costly.

![image](https://user-images.githubusercontent.com/307929/121597353-9b5f5080-ca0e-11eb-8422-bca2831f060f.png)

Making vtkSlicerMarkupsWidgetRepresentation3D::GetViewScaleFactorAtPosition return a fixed value (instead of actually computing the scale) seem to make a significant difference. Could you verify this and if you confirm that this has significant impact, could you think about a solution? Either fixing inefficiency of WorldToDisplay or by implementing a fast/batch version of it.

2. Reduce the number of actors

We added a separate actor for displaying almost identical things, just with different colors. We could modulate the color (and even the markup type) using point properties.

Could you try to merge the Unselected+Selected+Active pipeline and the Project+ProjectBack pipeline? That would allow us to go from 5 actors to 2 actors per control point, which could be a significant improvement.

3. Check if profiling RelWithDebInfo brings up anything else

For example, would disabling `vtkDebugLeaks` make a difference? It is quite expensive now (collects call stack, etc.) and I think it is enabled for release-mode builds on the factory.

**Comment by lassoan** [comment]
The original issue has been resolved. The remaining performance improvement ideas are tracked in https://github.com/Slicer/Slicer/issues/5752
