### ISSUE TITLE
Request volume rendering for segment labelmap 3D preview in Segment Editor

### ISSUE THREAD

**Issue by morgan-bc** [Slicer/Slicer#5623]
## Change the labelmap rendering mode in "Show 3D"

In the Segment Editor, the 3D preview of segment label cannot be real-time. In the current version, when the button "Show 3D" is pressed, the program will first compute a closed surface for the segment label. I think it might be to do marching cubes or something else similarily. This course could take 10sec for a big volume. Why do not show the label in a volume rendering mode just like in the module "Volume Rendering" ?

**Comment by lassoan** [comment]
We developed segmentation module from the very beginning with keeping this display option in mind. However, until recently this was not a feasible option, because VTK did not support multi-volume rendering.

Now that multi-volume rendering works in VTK quite well, we could add the option of rendering segments as volumes. However, simply rendering labelmaps would result in terrible-looking rendering. You can try it yourself by exporting the segmentation to labelmap and enable volume rendering.

Example: labelmap volume rendering (left), surface rendering (right)

![image](https://user-images.githubusercontent.com/307929/116501045-de5dce00-a87d-11eb-975d-ffc7c698f920.png)

To render acceptable quality surfaces (where you can actually recognize surfaces), you need to estimate a smooth surface normal from a discrete labelmap, while taking the color from the labelmap. Doing this estimation in CPU would be comparable (or may be even slower) than surface smoothing. Therefore, this should be implemented in the GPU by a new shader.

Implementing this shader is feasible but this task has not been very high on our priority list because there are many ways to get around this slow 3D update issue. First of all, surface smoothing is 40x faster in the Slicer-4.13 compared to 4-11, which means about 2-3x faster surface updates. Also, you can often make meshing and smoothing about 5-10x faster by applying slight smoothing to the labelmap. You can also split the segment to smaller pieces and just work on one piece at a time.

If someone is interested in implementing labelmap volume rendering with GPU-accelerated surface normal smoothing then we would be happy to integrate it as a new display mode for segmentations.
