### ISSUE TITLE
PETCTFusion

### ISSUE THREAD

**Issue by lcj09** [Slicer/Slicer#5630]
Hello! I did not find the PETCTFusion module in version 4.11, only SUV, but it is available in version 3.6. Is the module name changed in version 4.11? Is there still no PETCTFusion module?

**Comment by pieper** [comment]
A lot has changed since Slicer 3.6.  Now, the [PET DICOM](https://www.slicer.org/wiki/Documentation/4.10/Extensions/PETDICOM) extension is probably all you need.  It will convert to SUV normalized units if the dicom header is compatible.  You can use regular slicer visualization tools to do the fusion operations.

**Comment by pieper** [comment]
FYI, probably discourse.slicer.org is a better place for questions like this.
