### ISSUE TITLE
SetAndObserveColorToDisplayNode failed: invalid Colors module logic

### ISSUE THREAD

**Issue by geoffkflee** [Slicer/Slicer#5665]
Hello everyone, I hope this post finds you well.

I have the following function that performs fine and spits out an OBJ.
The input of this function is a scalar volume node.

```
slicer.vtkSlicerVolumesLogic().CreateLabelVolumeFromVolume(slicer.mrmlScene, labelVolumeNode, loadedScalarNode)
```

My output on Windows 10 is that of a properly formed OBJ file that loads properly in all kinds of viewers.
In Linux however, I am triggering the following error:

```
WriteData: removing old version of file /root/output/52591e24-6ccd-4ae5-afd9-b689d1375291/4_ISOCENTER_VERIFICATION.nrrd

SetAndObserveColorToDisplayNode failed: invalid Colors module logic.

unable to open .obj files
```

From combing over issues and search engine results, I am unable to find even a lead as to why the Colors module is broken. I am hoping someone else has seen this before, and if what could be causing such an issue.

## Expected behavior

The output directory should contain a new OBJ based on the segmentation created in the code regardless of environment.

## Environment
- Slicer version: Slicer-4.11.20210226-linux-amd64
- Operating system: Windows 10, Linux

**Comment by geoffkflee** [comment]
Closing this for now - I wanted to give this more time to properly build a report.

**Comment by lassoan** [comment]
> SetAndObserveColorToDisplayNode failed: invalid Colors module logic.

You get this error because you instantiate new module logics. Instead, you need to use the existing, properly initialized module logic. For example: `colorLogic = slicer.modules.colors.logic()`.

> WriteData: removing old version of file /root/output/52591e24-6ccd-4ae5-afd9-b689d1375291/4_ISOCENTER_VERIFICATION.nrrd

This is because you don't have write access to that file. It is either because you don't have write access to that folder or something locks that particular file. On linux a common issue was that sharing a single slicer instance between multiple users could result in having a read-only temporary folder. You can set the temporary folder path manually to fix this, or use the latest Slicer Preview Release, which automatically requests a new temporary folder from the operating system if the current folder is read-only.

**Comment by geoffkflee** [comment]
Thanks for the pointers @lassoan ! Your advice pointed me in the right direction:

- Using already instantiated logic modules avoided the invalid Colors module logic error.
- Using the newest build / ensuring that the folders being used are writable avoided the issue where the temporary folder was read-only.

Cheers!
