### ISSUE TITLE
Crash saving sequence browser node if SetSaveChanges is set on a non-synchronized sequence node

### ISSUE THREAD

**Issue by mikebind** [Slicer/Slicer#5671]
Reproducible Slicer crash using sample data when the following code snippet is run in the interactor.

## Steps to reproduce
```
import SampleData    
sequenceNode = SampleData.downloadSample('CTCardioSeq')
sequenceBrowserNode = slicer.modules.sequences.logic().GetFirstBrowserNodeForSequenceNode(sequenceNode)
newSeq = slicer.mrmlScene.AddNewNodeByClass('vtkMRMLSequenceNode')
# this is the change that causes the crash:
sequenceBrowserNode.SetSaveChanges(newSeq,True) 
sceneSaveFilename = slicer.app.temporaryPath + "/saved-scene-crashes.mrb" 
# crash occurs while executing this line:
slicer.util.saveScene(sceneSaveFilename)
```
Running the above code leads to a reproducible Slicer crash when saving the scene.  If the following line is added before the `SetSaveChanges` line, then there is no crash. 

```
sequenceBrowserNode.AddSynchronizedSequenceNode(newSeq)
```

## Expected behavior
I would have expected an error to be raised when trying to SetSaveChanges on a sequence which is not associated with the browser.  

## Environment
- Slicer version: Slicer-4.13.0-2021-05-29  (same thing happens on 4.11.20210226)
- Operating system: Windows 10

**Comment by lassoan** [comment]
The crash caused because sequence's browsing properties were attempted to be modified in an unrelated browser node (newSeq was not added as a synchronized node to sequenceBrowserNode).

The invalid request created an empty sequence node reference in the browser, which cause the crash when you attempted to save the browser node. The application should not crash if the API is slightly misused, so I'll implement more checks and logging of meaningful error message.
