### ISSUE TITLE
qSlicerBaseQTCoreExport.h file not found

### ISSUE THREAD

**Issue by jahnavi0801** [Slicer/Slicer#5681]
qSlicerBaseQTCoreExport.h file not found in the directory

## Steps to reproduce

- Wanted to access funtions of `qSlicerApplication` in `qMRMLThreeDViewControllerWidget` class, so included `qSlicerApplication.h` file (`#include "../../../Base/QTGUI/qSlicerApplication.h"`) in `qMRMLThreeDViewControllerWidget.cxx`.

- It showed an error that `Cannot open include file: 'qSlicerCoreApplication.h': No such file or directory`. So I replaced this line `#include "qSlicerCoreApplication.h"` with `#include "../QTCore/qSlicerCoreApplication.h` in `qSlicerApplication.h` file and built it.

- Later it raised an error that `Cannot open include file: 'qSlicerBaseQTCoreExport.h': No such file or directory` in `qSlicerCoreApplication.h`. I searched for `qSlicerBaseQTCoreExport.h` in the entire source code I couldn't find it

## Files
1. qMRMLThreeDViewControllerWidget.cxx :  Slicer\Libs\MRML\Widgets\qMRMLThreeDViewControllerWidget.cxx
2.  qSlicerApplication.h                                 :  Slicer\Base\QTGUI\qSlicerApplication.h
3. qSlicerCoreApplication.h                             :  Slicer\Base\QTCore\qSlicerCoreApplication.h 

## Environment
- Slicer version: Slicer- 4.11.20210226
- Operating system: Windows 10

**Comment by lassoan** [comment]
This behavior is intentional. To minimize dependencies between libraries and keep the design of the application clear and maintainable (e.g., separate GUI from logic) not all classes are available from everywhere. In some cases you can just add a library to the CMakeLists.txt file but in some other cases you need to come up with a different design (such as using events instead of direct method calls) to avoid prohibited dependencies. You can ask on the [Slicer forum](https://discourse.slicer.org) for more explanation or specific advice for your case. Include a link to your source code repository or to a minimal example that reproduces your problem.
