### ISSUE TITLE
3D rendering action box 

### ISSUE THREAD

**Issue by riep** [Slicer/Slicer#5720]
The action box used to activate or not the 3D rendering of a node has a wrong behavior 

## Steps to reproduce

- Load a volume.
- Right-click on the eye and click on "show in 3D views as volume rendering".
- Redo the same thing to uncheck : Right click on the eye and click on "show in 3D views as volume rendering".
- Click on the eye to hide the volume.
- Click on the eye to show it again.

## Expected behavior
MPR and the volume rendering are visible.

[describe what you expected to happen]
The volume rendering should not be visible as we have disabled it.  

## Environment
- Slicer version: Slicer-4.13.0-2021-06-27 (personal build)
- Operating system: Linux 20.04

**Comment by lassoan** [comment]
This is how it is expected to work (clicking the icon displays the volume in all views). We initially don't display volume rendering for historical reasons and because showing volume rendering by default can be quite resource-intensive. However, I can see how this may look unintuitive for users.

For now, you can persistently enable/disable visibility using this code snippet:

```
slicer.modules.volumerendering.logic().GetFirstVolumeRenderingDisplayNode(getNode('MRHead')).SetVisibility3D(False)
```

We could probably change the behavior to use this Visibility3D flag to indicate that the user never wants to see this the volume in 3D views (even if the eye icon is clicked to show the volume in all views).

**Comment by riep** [comment]
Yes, I was personally expecting  that. 
We can close this issue
