### ISSUE TITLE
Disable DICOM import from "Add data" dialog

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5726]
DICOM import via "Add data" dialog has many limitations, such as cannot deal with varying slice spacing, 4D volumes, cannot import any other objects than images, etc. and has issues, such as potentially loading the image in incorrectly slice order.

DICOM loading this way should be disabled and preferable replaced by importing via the DICOM module. To match the previous functionality more closely, the import should be done via a temporary DICOM database and should be fast (at least time to first image should be quick and simple).

## Environment
- Slicer version: Slicer-4.11 and later
- Operating system: all

**Comment by pieper** [comment]
This could be an inconvenient change in workflow for people.  A better option could be to detect dicom in the Add Data dialog and route it to the DICOM module in a temp database that doesn't change their existing database.  Putting the dicom data into the main database could retain PHI and people may not realize they need to delete it if they are used to using Add Data.

**Comment by cpinter** [comment]
+1 for Steve's comment. Instead of disabling the feature itself, re-routing to the more robust and comprehensive solution would be preferable in my view. Using a temporary database is a good idea as well. I agree though that the code that loads the DICOMs via Add data currently should be deprecated.

**Comment by jamesobutler** [comment]
Users are still using "Add Data" for some DICOM data and running into issues since it isn't using the DICOM module
https://discourse.slicer.org/t/merging-different-dicom-files-together/4345/10

**Comment by jamesobutler** [comment]
In general I’ve seen multiple users still struggle with this idea of dragging/dropping on slice views or directly clicking the button to Add Data of a DICOM dataset and then reporting issues with loading that would otherwise be solved by using the DICOM loading techniques of the DICOM module.

Addressing this issue would be very welcome by users in the idea of making simple things simple. It’s unclear to users that they have to use a different loading technique to load DICOM files. They must always read documentation to know what to do which indicates that things aren’t intuitive.

**Comment by pieper** [comment]
A related topic (probably requires it's own issue): when in the DICOM module any drop is interpreted as DICOM.  So dropping a nrrd or nii.gz is rejected with no feedback.  I think we should change this so that DICOM is expected only when the browser is shown.  When the browser is not shown the DICOM view looks a lot like the regular Data module but the drag-n-drop behavior is unexpectedly different.

**Comment by lassoan** [comment]
> A related topic (probably requires it's own issue): when in the DICOM module any drop is interpreted as DICOM. So dropping a nrrd or nii.gz is rejected with no feedback. I think we should change this so that DICOM is expected only when the browser is shown. When the browser is not shown the DICOM view looks a lot like the regular Data module but the drag-n-drop behavior is unexpectedly different.

This commit removed this direct drag-and-drop behavior completely, because it led to unexpected results (as you described), and now we don't need it anymore because the Data module now properly imports DICOM files by default.
