### ISSUE TITLE
Re-home data organized in `NA-MIC/Public/SampleData`

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#5796]
Dataset organized in the folder `NA-MIC/Public/SampleData` should be reviewed and relocated if still relevant to support our community.

See https://slicer.kitware.com/midas3/folder/1118

## Motivation

Around September 15th, the associated server will be shutdown.

## Related issues

* https://github.com/Slicer/Slicer/issues/4602

## Notes

* Some of the dataset have already been migrated following this two commits:
  * https://github.com/Slicer/Slicer/commit/59a5cac20c163618f7d7532c11ead051a11bd5ad: ENH: Update CLI buildsystem to download input and baseline using ExternalData
  * https://github.com/Slicer/Slicer/commit/80870c3c2c0b2d937e19e5b6a9ed7845871bbbdc: ENH: Update SampleData to use checksum
  * https://github.com/Slicer/Slicer/commit/0335d0380e29e17074cd76485f11b95a88fbcec6: ENH: Update sample data URLs to use GitHub instead of Midas

* Link `http://slicer.kitware.com/midas3/download/item/93008/SiemensTrioTim2.tar.gz` referenced in [Docs/user_guide/modules/dwiconvert.md](https://github.com/Slicer/Slicer/blob/ae2e56b493138eaa9d9082951f49bb3d693a2a9d/Docs/user_guide/modules/dwiconvert.md) should be used to reference the dataset corresponding to https://github.com/BRAINSia/BRAINSTools/blob/master/TestData/DWI_TestData_TARBALLS/SiemensTrioTim2.tar.gz.sha512

## Proposed solution

* Review datasets

* Upload to a different server. Based on the type of data, these could be sensible new home:
  * https://github.com/Slicer/SlicerDataStore/releases/tag/SHA256
  * https://github.com/Slicer/SlicerTestingData/releases

###  `NA-MIC/Public/SampleData` 

![image](https://user-images.githubusercontent.com/219043/129469197-668f3637-85cd-4dc0-af69-83bb6878a805.png)

**Comment by jcfr** [comment]
cc: @lassoan

**Comment by jcfr** [comment]
On a related note, @sjh26 recently uploaded the `DataStore` datasets to a collection of the same name at https://slicer-packages.kitware.com/#collection/6124ffb8342a877cb3b8afdd/folder/6125487e342a877cb3b8b6ed

Since these datasets were already uploaded at https://github.com/Slicer/SlicerDataStore/releases/tag/SHA256, I suggest we delete the collection and upload the discourse post https://discourse.slicer.org/t/downloading-extensions-for-older-releases/19256#download-data-sets-that-were-previously-hosted-on-the-datastore-2

**Comment by lassoan** [comment]
A big problem with content-based retrieval using github releases is that end-users cannot use the downloaded files, because they have invalid name (just the git hash). This is not a problem for test data that is retrieved using SampleData module, but it is a blocking point for users. I also like that girder features such as possibility to organize data into folders and download an entire folder at once.

So, if possible, it would be great if we could keep the girder collection at least until we figure out an alternative storage that allows convenient data browsing and download for end users.

**Comment by lassoan** [comment]
@sjh26 @jcfr Where this data set go?
http://slicer.kitware.com/midas3/download/item/157189/small-mr-eye-moving.nrrd

This is needed for the Landmark registration test (https://slicer.cdash.org/test/19477622) but I cannot find it anywhere.

I've checked:
- https://slicer-packages.kitware.com/#collection/6124ffb8342a877cb3b8afdd/folder/6125487e342a877cb3b8b6ed
- https://github.com/Slicer/SlicerTestingData/releases

There may be many other data sets that are not available anywhere anymore.

**Comment by jcfr** [comment]
While working on removing midas 3 support from the corde base, I also noticed that.

Since the instance is still accessible internally, I will list the remaining dataset here and push then in the SlicerDataStore github repo. See https://github.com/Slicer/SlicerDataStore

**Comment by lassoan** [comment]
Thank you @jcfr!

SlicerDataStore github repository cannot fully replace the old server, as there are no download links that can be directly used from a web browser. If the user clicks on the download link, the retrieved file name is the hash, so the user manually would need to rename it manually, which is more than what most users would be capable to (or want to) do.

Do you have any idea how to use a github repository for file storage that allows both hash-based download and download with proper filename? We could add a `latest` milestone (if that's not a reserved keyword), which would result in download link such as `https://github.com/Slicer/SlicerDataStore/releases/download/latest/something.nrrd`, which would not look bad. It would mean yet another duplication, but we already duplicate a lot of data sets between the MD5 and SHA256 releases, so it would not be that bad. It would also require improving the data management script, because manually maintaining this would be very hard (the script could automatically update the data set based on timestamps).

**Comment by lassoan** [comment]
I'm trying to fix [Landmark registration test](https://slicer.cdash.org/test/20015471) that fails because it [tries to download test data from Midas](https://github.com/Slicer/LandmarkRegistration/blob/290d481ffc1a378a8756e83d437b150aa6c7e30d/LandmarkRegistration.py#L1161-L1165). However, I cannot fix it because I can find small-mr-eye-fixed.nrrd data set but the `small-mr-eye-moving.nrrd` is not available anywhere.

@jcfr @sjh26 could you check what happened with this file and the four other files described in the previous commit?

**Comment by jcfr** [comment]
Here are the files (with `.txt` extension added to allow drag and drop here):
* [small-mr-eye-fixed.nrrd.txt](https://github.com/Slicer/Slicer/files/7486567/small-mr-eye-fixed.nrrd.txt)
* [small-mr-eye-moving.nrrd.txt](https://github.com/Slicer/Slicer/files/7486568/small-mr-eye-moving.nrrd.txt)

Could you upload then to https://github.com/Slicer/SlicerTestingData ?

**Comment by lassoan** [comment]
Yes, thank you, I'll upload them!

Have you found the 4 other files that I've mentioned [above](https://github.com/Slicer/Slicer/issues/5796#issuecomment-938636218), too?

**Comment by jcfr** [comment]
All datasets originally associated with `slicer.kitware.com` have been archived on [slicer-packages.kitware.com/](https://slicer-packages.kitware.com/#collection/6124ffb8342a877cb3b8afdd)

See https://slicer-packages.kitware.com/#collection/6124ffb8342a877cb3b8afdd

![image](https://user-images.githubusercontent.com/219043/155443664-81a955ab-8c14-4bfe-8530-bccae94313b4.png)

**Comment by lassoan** [comment]
@jcfr thanks for uploading the additional files. Some of the long-lost files are now recovered. There are still files that I cannot find, for example where are the registration case library images?

**Comment by jcfr** [comment]
Considering all MRB files are already available at https://github.com/Slicer/SlicerDataStore/releases/tag/SHA256, are there any other registration case library images we are missing ?



| `slicer.kitware.com/midas3/folder/959` | `github.com/Slicer/SlicerDataStore/releases/tag/SHA256` |
|--|--|
| ![image](https://user-images.githubusercontent.com/219043/155572583-bc0426a2-c0e3-45bc-a1cb-190ed18e213c.png) | ![image](https://user-images.githubusercontent.com/219043/155572329-c1ebcba2-1be7-4b9f-b152-68251c5b5b4f.png) | 



> There are still files that I cannot find, for example

Despite of the registration case libraries, which other files are missing ?

**Comment by jcfr** [comment]
As of 2022.07.13, the collection https://slicer-packages.kitware.com/#collection/6124ffb8342a877cb3b8afdd/folder/6125487e342a877cb3b8b6ed has been removed and datasets are available in https://github.com/Slicer/slicer.kitware.com-midas3-archive#readme
