### ISSUE TITLE
Using erase tool outside of segmentation crashes slicer

### ISSUE THREAD

**Issue by nathanbmnt** [Slicer/Slicer#5812]
If using the erase tool outside of a specific segmentation Slicer crashes.

## Steps to reproduce
[SegmentationEraseCrashExample.zip](https://github.com/Slicer/Slicer/files/7034356/SegmentationEraseCrashExample.zip)
Load FusedVolume.mha and then Markup_2.seg.nrrd from SegmentationCrashExample.zip into Slicer.
Go to the Segment Editor and click Erase, "Edit in 3D views". The sphere to edit the segmentation appears even when the mouse is not over the segmentation. Maybe the bounds are corrupted? If the mouse is clicked here, outside of the segmentation Slicer crashes.
![image](https://user-images.githubusercontent.com/40271210/130503043-dff72767-2518-4225-a6eb-4acd011485b5.png)
This also happens when erasing the segmentation in a slice view.

The following is printed to the command line for Slicer built with command line visible:

> The update extent specified in the information for output port 0 on algorithm vtkTrivialProducer(000001D3B471D190) is 9 17 80 80 0 0, which is outside the whole extent 9 17 83 80 0 0.
> 
> This data object does not contain the requested extent.
> 
> GetScalarPointer: Pixel (9, 80, 0) not in memory.
> Current extent= (9, 17, 83, 80, 0, 0)
> 
> GetScalarPointer: Pixel (9, 80, 0) not in memory.
> Current extent= (9, 17, 83, 80, 0, 0)

## Expected behavior

After clicking with the erase tool the segmentation is not changed and Slicer does not crash.

## Environment
- Slicer version: Slicer-4.13.0-2021-08-19
- Operating system: Windows 10

**Comment by jamesobutler** [comment]
@nathanbmnt I'm unable to replicate this issue with the specific data that you've provided.

**Comment by lassoan** [comment]
After lots attempts I was able to reproduce it:

https://user-images.githubusercontent.com/307929/130617335-3501c015-7de1-4920-95a3-1eb394799369.mp4

The problem is that `vtkSegmentationModifier::GetExtentIntersection` returns an invalid intersection (resampledSegmentLabelmap = 0,39, 83,193, 0,0; extent = 0,39,  0,13,  0,0; -> updateExtent = 0,39,  83,13,  0,0 !! 83>13) and the vtkImageThreshold crashes if it gets an invalid UpdateExtent instead of just not doing anything.

Corrective action: we should add check the extent before passing to `threshold->UpdateExtent` and not run the filter if the extent is invalid. @Sunderlandkyl I would prefer if you implemented this, because I'm not completely sure if we can simply skip the operation or we should fill with "outside" value.

Preventive action: we should report this error to VTK, because VTK should probably not do anything (or may report a warning) but should definitely not crash.
