### ISSUE TITLE
Slicer development environment issues

### ISSUE THREAD

**Issue by charuu** [Slicer/Slicer#5869]
I am trying to setup 3d slicer development environment . One of the pre requisite requires me to install QT5 ,where I need to point to the .make file. for QT5_dir. In order to do so I need to install all the components which makes the installation heavy. Is there any workaround for this?

## Environment
- Slicer version: Slicer-4.13 ?-YYYY-MM-D
- Operating system:Mac + 10.13

**Comment by lassoan** [comment]
You don't need to install _all_ components of Qt, only those that are selected by default and a few in addition (those that are listed in the build instructions). That said, Qt is certainly not small, but its size is similar to most other SDKs for GUI development. On Windows, the minimum size is 2GB, but I would recommend to install debug symbols and source code (which adds 8GB more) because it helps when you are trying to understand how Qt works.

**Comment by charuu** [comment]
If i dont have to use QT for development and only work on Slicer API, then how do I switch off slicer config which looks for CMake files from QT?

  Could not find a package configuration file provided by "Qt5" with any of
  the following names:

    Qt5Config.cmake
    qt5-config.cmake

  Add the installation prefix of "Qt5" to CMAKE_PREFIX_PATH or set "Qt5_DIR"
  to a directory containing one of the above files.  If "Qt5" provides a
  separate development package or SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMake/SlicerBlockFindQtAndCheckVersion.cmake:67 (__SlicerBlockFindQtAndCheckVersion_find_qt)
  CMakeLists.txt:638 (include)


Because of this I need to compile all components which takes a long time

**Comment by lassoan** [comment]
To build Slicer, you must install the Qt SDK. You don't need to build Qt. Installing Qt takes about 5-10 minutes (may take a bit more if you have very slow internet connection). 

Building Slicer is faster on Linux and macOS than on Windows. On a gaming desktop (Intel core i9 CPU, building on 20 threads) entire Slicer (including ITK, VTK, SinpleITK, etc) is built in 30 minutes. On Windows, it takes about 2-3 hours in a gaming desktop computer, and takes about 15 hours on an ultrabook.

So, if build time is extremely important for you then get a new desktop computer and run Linux on it. But normally build time does not matter, because even the worst case, you can build Slicer in a day, and when you make modifications and build again then it completes within a minute. 

If you don't want to bother with building anything then you can use all Slicer features from Python. There are lots of APIs that allow extending and customizing the application.

**Comment by charuu** [comment]
OS: MAC 10.13
All default components installed in QT except android and IOS
Developer tool Cmake 3.21 and Ninja 1.10.2 installed.

On compiling Slicer and providing the path to QT_DIR I get the following error:
-- Could NOT find Qt5Sql (missing: Qt5Sql_DIR)
-- Could NOT find Qt5WebEngine (missing: Qt5WebEngine_DIR)
-- Could NOT find Qt5WebEngineWidgets (missing: Qt5WebEngineWidgets_DIR)
CMake Warning at CMake/SlicerBlockFindQtAndCheckVersion.cmake:22 (find_package):
  Found package configuration file:

    /Users/charujain/Qt/5.15.2/wasm_32/lib/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "Sql" config file at
  "/Users/charujain/Qt/5.15.2/wasm_32/lib/cmake/Qt5Sql/Qt5SqlConfig.cmake"

  Failed to find Qt5 component "WebEngine" config file at
  "/Users/charujain/Qt/5.15.2/wasm_32/lib/cmake/Qt5WebEngine/Qt5WebEngineConfig.cmake"


  Failed to find Qt5 component "WebEngineWidgets" config file at
  "/Users/charujain/Qt/5.15.2/wasm_32/lib/cmake/Qt5WebEngineWidgets/Qt5WebEngineWidgetsConfig.cmake"

Call Stack (most recent call first):
  CMake/SlicerBlockFindQtAndCheckVersion.cmake:67 (__SlicerBlockFindQtAndCheckVersion_find_qt)
  CMakeLists.txt:638 (include)

What is the solution to this?

**Comment by charuu** [comment]
I have turned off webengine req and disabled module SQL in QT. I am thinking I might not need these anyways.

**Comment by lassoan** [comment]
Please follow the [build instructions](https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/macos.html). More specifically,

> download and execute qt-unified-mac-x64-online.dmg, install Qt 5.15.2, make sure to select qtscript and qtwebengine components
