### ISSUE TITLE
packaging and making the installation package

### ISSUE THREAD

**Issue by LuPingChina** [Slicer/Slicer#5975]
After packaging and making the installation package, I found a problem: the console window will be displayed when the application starts, which is different from the official downloaded installation package. How can I configure it to not display the console window when the application starts

**Comment by lassoan** [comment]
You can configure such application options using CMake variables defined in SlicerApplicationOptions.cmake.

In recent Slicer master version the console is hidden by default and can be enabled using `Slicer_BUILD_WIN32_CONSOLE_LAUNCHER` CMake option as described [here](https://slicer.readthedocs.io/en/latest/developer_guide/debugging/overview.html#console-output-on-windows).

In the current Slicer Stable Release, the console was shown by default and `Slicer_BUILD_WIN32_CONSOLE` CMake variable could be used to hide it. Since we have made hundreds of fixes and improvements since this release and will soon create a new stable release from the current Slicer master, so I would recommend to use the latest Slicer master version for any developments.

**Comment by LuPingChina** [comment]
Thankyou very much
