### ISSUE TITLE
Make displayed markup node type names more user-friendly

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#5976]
It is not clear for users that "Fiducial node" means a "fiducial list". It is not nice that a closed curve is referred to as "ClosedCurve node" on the GUI.

## Describe the solution you'd like

Use a different string for markup type in code and files (simple machine-readable string, such as `Fiducial`, `ClosedCurve`) and on the GUI (human-readable, translatable string, such as `fiducial list`, `closed curve`).

## Describe alternatives you've considered

Automatic conversion from CamelCase to space separators could work, but would not be translatable to different languages.

## Additional context

https://discourse.slicer.org/t/delete-control-point-delete-fiducial-pop-up-confirm-box/20430/14

**Comment by jamesobutler** [comment]
“Create new Fiducial node” -> “Create new fiducial list”

https://github.com/Slicer/Slicer/blob/a15cbacbb91a3f187a8cd80c00bbb232e881f48b/Modules/Loadable/Markups/Widgets/qMRMLMarkupsToolBar.cxx#L468

In the context menu and markups module button it would be “Fiducial List” instead of simply “Fiducial”.
https://github.com/Slicer/Slicer/blob/a15cbacbb91a3f187a8cd80c00bbb232e881f48b/Modules/Loadable/Markups/SubjectHierarchyPlugins/qSlicerSubjectHierarchyMarkupsPlugin.cxx#L706-L710
https://github.com/Slicer/Slicer/blob/a15cbacbb91a3f187a8cd80c00bbb232e881f48b/Modules/Loadable/Markups/qSlicerMarkupsModuleWidget.cxx#L771-L773
