### ISSUE TITLE
Cropping image by 3D slicer

### ISSUE THREAD

**Issue by MohHu** [Slicer/Slicer#6092]
Dear developer,

I am using 3D slicer for cropping CT image. It works fine. When I display cropped images in 3D slicer GUI, there is no problem, but when I imported image to another software, the image is reversed. So the superior becomes interior and vise versa.

Is there any suggestion to solve this problem?

Yours sincerely

**Comment by lassoan** [comment]
There are many equivalent mappings between voxel space and physical space. The other software assumes a certain mapping instead of reading the actual mapping from the image header. If you need further information or help please post to the [Slicer forum](https://discourse.slicer.org/), describing your overall goal and providing more details about the software you are trying to use.
