### ISSUE TITLE
No hardcoded directory paths and class names in Python scripted modules

### ISSUE THREAD

**Issue by CsatiZoltan** [Slicer/Slicer#6149]
## Problem

During the development of my Python-based scriptable module, I am restricted by the naming conventions and the directory structure imposed by the superclasses (`ScriptedLoadableModule`, `ScriptedLoadableModuleWidget`, `ScriptedLoadableModuleLogic`). This is caused by the fact that the [icon path](https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Base/Python/slicer/ScriptedLoadableModule.py#L30) and the Qt Designer's [.ui file path](https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Base/Python/slicer/ScriptedLoadableModule.py#L156) are both hardcoded in the superclass. Moreover, I am [enforced to name my subclasses in a certain way](https://github.com/Slicer/Slicer/blob/3edd84ddba681786be9e916124126fc858592598/Base/Python/slicer/ScriptedLoadableModule.py#L81). These issues are inconvenient for me because they make this module not conform to the rest of the code I write.

## Solution I would like

I would like freedom, specifically be able to
1. give whatever name to the directories where I store my icons and my .ui file (e.g. not `UI/` but `ui/`)
2. give Pythonic class names

## Alternatives

Here are some solutions I can think of.
1. Accept the current situation.
2. Do not subclass `ScriptedLoadableModule`, `ScriptedLoadableModuleWidget` and `ScriptedLoadableModuleLogic`, rather copy their codes into mine. However, I would like to avoid code replication.
3. Allow passing user-defined paths as arguments to the superclass methods, and not requiring the`my_module_nameWidget` syntax.

**Comment by lassoan** [comment]
Thanks for bringing this up. As a general guideline, we follow conventions of the language and framework that we use or extend: we use C++ conventions for C++ classes, Qt conventions for Qt classes, VTK conventions for VTK classes, etc.

There are often conflicting conventions, for example when we implement a C++ class in Python (such as ScriptedLoadable* classes) or when we use VTK in a Qt class. In these cases there is no perfect solution, the best we can do is to decide which convention takes precedence in which case and try to be as consistent as possible.

To answer your questions specifically:

> give whatever name to the directories where I store my icons and my .ui file (e.g. not UI/ but ui/)

If you have specific recommendations for additional path hints then it should be no problem to add those (e.g., search in both ui and UI folder; or use a different "resources" folder name).

If you want to use _any name_ then auto-discovery would not support it. But since it is just a convenience feature, so it is fine if you don't use it. You can instead use `self.parent.icon = qt.QIcon(...)` and `slicer.util.loadUI(...)` - these functions do not have any assumptions about folder names.

> give Pythonic class names

Since `ScriptedLoadableModule` and `ScriptedLoadableModuleWidget` classes are Python implementation of Qt classes, there will always be inconsistency of naming conventions somewhere. We could push these inconsistencies into layers where Python developers see it less. However, I'm not sure how much that would help, because you would still need to use with VTK and Qt conventions everywhere else. Implementation might not be trivial either and since the new class and method names would need to live together with the current ones for at least a few years, it would bring significant complexity and maintenance burden. This overall does not seem to have a very good cost/benefit ratio.

There are other things that could be improved to make life of Python developers much better, for example generating stubs for C++ classes (so that Python IDEs offer documentation and auto-complete for Python-wrapped C++ classes outside of debugging see [here](https://discourse.vtk.org/t/auto-compeletion-in-vs-code/7728/2)), or factoring out libraries (such as MRML, SegmentationCore, ...) to make them pip-installable and usable from a Python application and not just from Slicer. We could use some help in these, if you are interested and have time.

There are also small things that could be improved without breaking changes, such as make Python source code formatting more closely follow Python Style Guide, or change private and local variable names to be more Pythonic, etc. Contributions are welcome!

**Comment by CsatiZoltan** [comment]
> If you have specific recommendations for additional path hints

To me, *resources* (or *Resources*), and within it *ui* and *icons* would be satisfying. In fact, one could search for case-insensitive folder names.

> I'm not sure how much that would help, because you would still need to use with VTK and Qt conventions everywhere else.

This makes sense, as you demonstrated above with `QIcon` and `loadUI`.

> it would bring significant complexity and maintenance burden. This overall does not seem to have a very good cost/benefit ratio.

I agree that scientists who are neither paid for such software architecture development nor profit from them in form of publications should not bother about it. When I brought up this issue, I thought of this aspect, but was unsure of how much work it would entail.

> generating stubs for C++ classes

I have no experience in generating stubs for C++, but I worked on stub generation for the FreeCAD project using [Mypy](https://mypy.readthedocs.io/en/stable/stubs.html). The process I followed was to install `mypy` to the Python environment of FreeCAD (it is based on `conda`, but 3D Slicer can install packages via `pip`, so not a problem), and then call Mypy to generate the stubs. If this is OK for the Slicer community, I could have a look at it (though I may need help because I am not yet very familiar with the module and class structure of 3D Slicer).

> so that Python IDEs offer documentation and auto-complete for Python-wrapped C++ classes outside of debugging

Yes, I would love that since I cannot attach a debugger to a running Slicer process (I tried all three IDEs). As of now, code completion works for pure Python codes in PyCharm, but `slicer.modules` or `slicer.mrmlScene` are not found.

> factoring out libraries (such as MRML, SegmentationCore, ...) to make them pip-installable and usable from a Python application and not just from Slicer.

A bit off-topic, but I would be very happy if I could use the Python-wrapped CTK (and MRML) widgets without Slicer. That way, I would be able to harness many useful widgets from CTK for my own projects.

**Comment by lassoan** [comment]
Thanks for offering the help with stubs generation.

VTK uses its own Python wrapper and already offers some stub generation (see discussion here: https://discourse.vtk.org/t/auto-compeletion-in-vs-code/7728/2), but we would need to test how it all works in Slicer's Python environment (where the stubs are generated, how they could be generated for all VTK-based classes in Slicer, etc.).

I don't know how stubs could be generated for Qt classes (Python-wrapped using [PythonQt](https://github.com/MeVisLab/pythonqt)). Since it applies to all CTK classes, you could explore that completely independently from Slicer.

> Yes, I would love that since I cannot attach a debugger to a running Slicer process (I tried all three IDEs).

Python debugging works well for me using PyCharm, Visual Studio Code, and Visual Studio on Windows and many people set them upon other operating systems. You can get help for setting it up on the Slicer forum.

> A bit off-topic, but I would be very happy if I could use the Python-wrapped CTK (and MRML) widgets without Slicer. That way, I would be able to harness many useful widgets from CTK for my own projects.

Yes, this the long-term goal. This would allow many people to use Slicer features without requiring them to use the Slicer application as Python executable (which many Python developers are not comfortable with).

CTK is already Python-wrapped and you could submit to PyPI to make it conveniently available for many users. It is probably not a trivial task, though, especially if you want continuous integration servers to generate the packages automatically.

Our current focus (@jcfr is working on it) is creating a good framework for building, continuous integration, PyPI submissioon for VTK-based packages (such as vtkAddon, VMTK, vtkbool, MRML, SegmentationCore a.k.a. PolySeg).

---

I'm not sure if there is any specific things that this ticket should track, so maybe we can close it, and you can follow up with pull request on improving icon and ui file auto-discovery, questions on discourse, etc.

**Comment by CsatiZoltan** [comment]
> use Slicer features without requiring them to use the Slicer application as Python executable

By using the Slicer application as Python executable, do you mean that we launch `/bin/PythonSlicer`? If so, that is what I did. I pointed PyCharm to that executable, then it automatically recognized all the site-packages.
![SlicerPython](https://user-images.githubusercontent.com/12742890/152249275-33fdeef2-37fd-46f4-9053-82416ed8ca26.png)

> If you have specific recommendations for additional path hints then it should be no problem to add those (e.g., search in both ui and UI folder; or use a different "resources" folder name).

Then I would open a PR for that, as it seems to be easy to implement (handling case-sensitivity, etc.). Maybe close this issue with that PR?

> questions on discourse

Yes, that is what I plan. As you explained, generating Python stubs is much more involved than additional path hints, and is not strictly related to this GitHub issue.

**Comment by lassoan** [comment]
As I understand this issue can be closed now. Please reopen or create new ones or start discussions on the Slicer Forum for further requests or ideas.
