### ISSUE TITLE
Slicer logo fix

### ISSUE THREAD

**Issue by swirlsky** [Slicer/Slicer#6157]
I think that the current Slicer logo:
https://www.slicer.org/assets/img/3D-Slicer-Mark.svg

has a little glitch at one of its corners:
![slicer](https://user-images.githubusercontent.com/27681171/152646841-4d310492-bfa2-45bb-a00d-5f9f67062454.png)

So I fixed it, here it is:
https://filebin.net/ayp6wvsd9ty5sppz

Please decide which one you like better.

**Comment by lassoan** [comment]
Thanks for taking the time to investigate this.

I cannot reproduce the appearance that you show in the image above using any SVG renderer. I've tried Inkscape, Adobe Illustrator, Chrome, Firefox, Gimp, [rapidtables](https://www.rapidtables.com/web/tools/svg-viewer-editor.html), [svgviewer.dev](https://www.svgviewer.dev/), [svgeditoronline.com](http://www.svgeditoronline.com/) - they all render logo without the protruding edge. Therefore, most likely the current svg file is all right.

For example, the current svg rendered by Gimp:
![image](https://user-images.githubusercontent.com/307929/152702973-bfaaffd7-abed-413c-8623-013a6fae1cba.png)

What software rendered the logo as you show in the image above?

**Comment by swirlsky** [comment]
Hmm.. strange. the "ugly corner" I see in gimp, inkscape and also in brave web browser on ubuntu, as well as in opera on android. Can it be that it's platform-dependent? Under windows and mac I can't try. Do you use one of those? Right now I'm writing this on my android phone and this is what I see if I zoom in on the logo on the slicer website:
![Screenshot_20220206-232617](https://user-images.githubusercontent.com/27681171/152704094-58f25c01-7165-4dfa-8bb7-4324e418723a.png)

**Comment by pieper** [comment]
It must be something about the version on the slicer.org website.  I can reproduce the ugly corner effect on windows, mac, and linux with chrome and/or firefox and/or edge.  But not with the one in `./Docs/_static/images/3D-Slicer-Mark.svg`.

**Comment by lassoan** [comment]
@pieper your have solved the mystery!

@jcfr do you know where that glitchy https://www.slicer.org/assets/img/3D-Slicer-Mark.svg file comes from?

**Comment by jcfr** [comment]
Looking at the history [here](https://github.com/Slicer/slicer.org/commits/main/assets/img/3D-Slicer-Mark.svg)

The glitch seems to have been introduced when by the commit [bc48de2b8](https://github.com/Slicer/slicer.org/commit/bc48de2b885e9bb4a725a24ab44b86273014f0ea) `ENH: Use bolded outline Slicer logo`

| commit [4d84e36ff7](https://github.com/Slicer/slicer.org/commit/4d84e36ff723bbe007e902ca40fad92fbc34f4ea) | commit [bc48de2b8](https://github.com/Slicer/slicer.org/commit/bc48de2b885e9bb4a725a24ab44b86273014f0ea)  |
|--|--|
| `Update the logo. from placeholder to real logo.` | `ENH: Use bolded outline Slicer logo`  |
| ![](https://raw.githubusercontent.com/Slicer/slicer.org/4d84e36ff723bbe007e902ca40fad92fbc34f4ea/assets/img/3D-Slicer-Mark.svg) | ![](https://raw.githubusercontent.com/Slicer/slicer.org/bc48de2b885e9bb4a725a24ab44b86273014f0ea/assets/img/3D-Slicer-Mark.svg) |


Since July 27th 2020, the icons originally designed by @SteveJordanKW are organized in this public [google folder](https://drive.google.com/drive/u/0/folders/1dh7O6PNdh5EkePtwyjFREfjUdsaxrrai).

There also been a lot of discussion related to the stroke associated with SVG starting with [this Discourse post](https://discourse.slicer.org/t/proposed-new-slicer-logo/11295/110?u=jcfr) from  August 2020 with led to the creation of pull request updating the readthedocs logo to be png instead of svg. See https://github.com/Slicer/Slicer/pull/5173. Note that in this pull request, @finetjul also suggested to use `shape-rendering="crispEdges"` to lines in SVG to improve results but it seems this hasn't been considered.


Last, I also created an new issue to discuss the creation of dedicated repository for organizing the logos. See https://github.com/Slicer/Slicer/issues/6161

**Comment by lassoan** [comment]
>  @finetjul also suggested to use shape-rendering="crispEdges" to lines in SVG to improve results but it seems this hasn't been considered

I've tried it and a few similar options and they did not make any perceivable difference.

**Comment by lassoan** [comment]
This is an error on the slicer.org website, I've created an issue for this on the website's repository: https://github.com/Slicer/slicer.org/issues/143
