### ISSUE TITLE
SimpleITK  build error

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6163]
Mentioning SimpleITK windows build issues, I just tested the very latest Slicer with a custom app (https://github.com/Slicer/Slicer/commit/015fa17a5715863052cda5dae2a14098589b01ae) and I get the following error:

```
  -- SimpleITK: E:/t3/tR/python-install/bin/PythonSlicer.exe;setup.py;install
  CMake Error at E:/t3/tR/slicersources-src/CMake/ExternalProjectForNonCMakeProject.cmake:104 (message):
    SimpleITK: install step failed with exit code '1'. 
```
In `SimpleITK_install_step_error.txt`:
```
Traceback (most recent call last):
  File "E:\t3\tR\SimpleITK-build\SimpleITK-build\Wrapping\Python\setup.py", line 14, in <module>
    from SimpleITK._version import __version__
  File "E:\t3\tR\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITK\__init__.py", line 18, in <module>
    from SimpleITK.SimpleITK import *
  File "E:\t3\tR\SimpleITK-build\SimpleITK-build\Wrapping\Python\SimpleITK\SimpleITK.py", line 13, in <module>
    from . import _SimpleITK
ImportError: DLL load failed while importing _SimpleITK: The specified procedure could not be found.
```
Could this be related? Any suggestions? Thank you!

_Originally posted by @cpinter in https://github.com/Slicer/Slicer/issues/5954#issuecomment-1028143789_

**Comment by jcfr** [comment]
When Slicer was recently upgraded to a newer Python version in https://github.com/Slicer/Slicer/commit/34e48e8aef5dad19ec8a955d6f48a1940846e3f3, it required follow-up commit https://github.com/Slicer/Slicer/commit/a1c44fab014a6be93e5917fe63ffee3a98dba597 to fix a SimpleITK build issue. Is your custom app including this bug fix?

Using current Slicer `master` I don't believe I have seen SimpleITK build issues. The SimpleITK build issues mentioned in https://github.com/Slicer/Slicer/pull/5954#issuecomment-1020162123 were specifically from using latest ITK and latest SimpleITK without setting `-DSimpleITK_INT64_PIXELIDS:BOOL=ON`.

_Originally posted by @jamesobutler in https://github.com/Slicer/Slicer/issues/5954#issuecomment-1028148449_

**Comment by jcfr** [comment]
Yes, as I wrote the custom app is on the very latest Slicer, hash linked in my previous comment.

I did a completely clean build.

_Originally posted by @cpinter in https://github.com/Slicer/Slicer/issues/5954#issuecomment-1028151718_

**Comment by jcfr** [comment]
It does look like a non-clean build issue where SimpleITK wasn't built cleanly. As I remember potentially that exact same issue when building as of https://github.com/Slicer/Slicer/commit/34e48e8aef5dad19ec8a955d6f48a1940846e3f3. However, if you say it was a clean build, then I'm not sure. I haven't seen such issues on my own builds with current latest.

_Originally posted by @jamesobutler in https://github.com/Slicer/Slicer/issues/5954#issuecomment-1028154414_

**Comment by lassoan** [comment]
"The specified procedure could not be found" error means that the searched DLL was found by name but it is the wrong version. So, I would double-check if there is anything related to SimpleITK dependencies in your path. For example, "d:\OneDrive\Utils\dcmtk-3.6.5-win64-dynamic\bin" can cause this (if your dcmtk build is incomplete).  

Sometimes you can find more information about DLL leading errors in the Windows event log. If it tells which DLL failed to load that allows you to search for all those DLL instances on your system and figure out which one is found instead of the correct one. 

If you don't find any details in the event log then you can use procmon to trace DLL loading.

**Comment by fbordignon** [comment]
Try inspecting _SimpleITK.pyd to the dependency walker and adding all the paths from LibraryPaths to its search path as well (Options->Configure Module Seach Order->Add Directory). Then, highlight all found dlls on the Module lower panel and press F9 to show full paths. Check if they are all from the build path. I've noticed a DCMTK on a foreign path `d:\OneDrive\Utils\dcmtk-3.6.5-win64-dynamic\bin` on your build.

**Comment by cpinter** [comment]
Wow @lassoan amazing catch with the old DCMTK in the path! I renamed the folder to try and the configure step `cmake -P E:/t3/tR/SimpleITK_install_step.cmake` suggested by @jcfr succeeded! Doing the superbuild now. Thanks a lot!

**Comment by fbordignon** [comment]
lol andras beat me to it. Good chance it is solved then. great!

**Comment by lassoan** [comment]
Additional extra paths should not have caused problems if your DCMTK build was available and complete in a path that is listed before. Maybe your DCMTK build was incomplete or DCMTK did something fragile (such as searching the path for additional DLLs that were not found in your DCMTK folder but they were found in the additional folder). It might still make sense to check with procmon what happened, because if DCMTK does some questionable things then they may cause problems at runtime, too.

**Comment by lassoan** [comment]
The issue has been resolved, so I close this now. We can reopen later if we find that it comes up again.

**Comment by cpinter** [comment]
I was going to report back first about the superbuild but it succeeded so all is good with this. Thank you!
