### ISSUE TITLE
Unable to start Designer application with Slicer launcher

### ISSUE THREAD

**Issue by gatangen** [Slicer/Slicer#6174]
Trying to start Designer to edit .ui files in Slicer build. The Designer application crashes when launched from terminal.

## Steps to reproduce
>Slicer-build/Slicer --designer 
or
>Slicer-build/Slicer --launch ~/dev_tools/5.15.2/clang_64/bin/Designer.app/Contents/MacOS/Designer

=> The Designer application crashes at startup

When starting Designer from Slicer GUI menu: Edit - Application Settings - Developer - Qt Designer - launch,
the Designer starts ok, but without the custom CTK/Slicer MRML Widgets.

When running Slicer from Qt Creator after defining QT_PLUGIN_PATH (/opt/s/Slicer-build/bin:/opt/s/CTK-build/CTK-build/bin) in Qt Creators "Run Settings" , the Designer starts and the custom CTK widgets are available. But, the other custom widgets are still missing. 
 
## Expected behavior
In all these cases, Designer should start and have all the custom Widgets available.
I suspect that both the crash and the missing widgets are caused by faulty handling of variable QT_PLUGIN_PATH in the Slicer launcher.

## Environment
- Slicer version: Slicer-4.13.0-2022-02-10
- Operating system: MacOS 10.14.6
![Screenshot 2022-02-10 at 16 19 33](https://user-images.githubusercontent.com/506211/153439503-981260f1-3e0d-4c27-b467-d10d4f7e1f4b.png)
![Screenshot 2022-02-10 at 16 31 05](https://user-images.githubusercontent.com/506211/153440664-1031013b-330d-4305-b4aa-5a38faedbc8e.png)

**Comment by jamesobutler** [comment]
Hi @gatangen this may have been fixed just recently in https://github.com/Slicer/Slicer/commit/9766f4f1f8fd85ed4d33e8f7ea39235b0334502d which was solving a Designer crash at startup. This commit is currently the latest commit on the Slicer `master` branch but since it was merged after the nightly factory Slicer Preview build was started the fix is not available in Today's preview. It will be available in tomorrow's Slicer Preview build, or if you build Slicer from source you can use the latest `master`.

**Comment by lassoan** [comment]
@gatangen Thanks for the detailed, high-quality test report. Please test it tomorrow and report back here.

**Comment by lassoan** [comment]
Most likely the same issue as https://github.com/Slicer/Slicer/issues/6174
