### ISSUE TITLE
Building with ITK python wrapping does not work

### ISSUE THREAD

**Issue by ebrahimebrahim** [Slicer/Slicer#6194]
Superbuild fails when enabling ITK python wrapping.

I am just transferring my comment from [here](https://github.com/Slicer/Slicer/pull/5954#issuecomment-1029507877) to an issue.

## Steps to reproduce

- Edit cmake to enable the variable `Slicer_BUILD_ITKPython`
- Start the superbuild process

```
In file included from /home/ebrahim/Slicer-SuperBuild2/ITK-build/Wrapping/itkImageToVTKImageFilter.cxx:16:
/home/ebrahim/Slicer-SuperBuild2/ITK/Modules/Bridge/VtkGlue/include/itkImageToVTKImageFilter.h:22:10: fatal error: 'vtkImageImport.h' file not found
#include "vtkImageImport.h"
         ^~~~~~~~~~~~~~~~~~
1 error generated.
make[5]: *** [Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGlueCastXML.dir/build.make:65: Wrapping/itkImageToVTKImageFilter.xml] Error 1
make[4]: *** [CMakeFiles/Makefile2:36492: Wrapping/Modules/ITKVtkGlue/CMakeFiles/ITKVtkGlueCastXML.dir/all] Error 2
make[3]: *** [Makefile:152: all] Error 2
make[2]: *** [slicersources-build/CMakeFiles/ITK.dir/build.make:118: slicersources-build/ITK-prefix/src/ITK-stamp/ITK-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:877: slicersources-build/CMakeFiles/ITK.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

## Environment
- Slicer version: Slicer-4.13-2022-02-17 probably, after the merge of #5954
- Operating system: Ubuntu 20.04.3

**Comment by jcfr** [comment]
The error is associated with the `VtkGlue` module.

After having an initial look, it turns out there are two implementation:
* [Modules/Bridge/VtkGlue](https://github.com/InsightSoftwareConsortium/ITK/tree/master/Modules/Bridge/VtkGlue): within the ITK source tree 
* [InsightSoftwareConsortium/ITKVtkGlue](https://github.com/InsightSoftwareConsortium/ITKVtkGlue): an independent ITK remote module

Consolidating has been discussed in this post https://discourse.itk.org/t/proposal-remove-vtkglue-from-itk-and-add-itkvtkglue-as-a-remote-module/4791

The logic integrating with VTK is quite intricate. That said, the corresponding implementation in both is mostly similar.

**Comment by jcfr** [comment]
Since ITK Python wheels are now available and can be used in the context of Slicer, we will remove the `Slicer_BUILD_ITKPython` option.
