### ISSUE TITLE
Scissors circle effect change/improvement drawing it by the borders

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#6203]
Hey guys, I want to run by you an idea that I had to perhaps improve the circle scissors effect.
I am always frustrated when I need to segment a perfect circle, since I need to guess the center of the circle to pick it with the scissors.

If we change the following two lines https://github.com/Slicer/Slicer/blob/e5c5ad7801b81c99a0e37b44ce570e9acbfdb7f0/Modules/Loadable/Segmentations/EditorEffects/qSlicerSegmentEditorScissorsEffect.cxx#L418-L419

to 

```cpp
          position[0] = (eventPosition[0] + this->DragStartPosition[0])/2 + radius/2 * sin(angle);
          position[1] = (eventPosition[1] + this->DragStartPosition[1])/2 + radius/2 * cos(angle);
```

The circle center will be the midpoint between the start drag position and the current position. Effectively, the creation of the circle will be controlled by its borders. I find it easier to segment circles that way. Is the original way better for the medical imaging users? Drawing softwares such as inkscape uses shift to modify the behavior between those two options. Here is a quick vid showing how it would be. With the old option, I needed several tries to guess the center of the circle correctly. Appreciate your input on this.

https://user-images.githubusercontent.com/4790289/154724391-3d8c21bd-fc45-4bdd-83b9-fdaa35f287b5.mp4

**Comment by lassoan** [comment]
For approximate segmentation the current "centered" approach usually works better, but it is certainly not good for circle fitting.

Adding a "centered" checkbox would be easy (it could be added as a fourth item to "Shape" list). It would make the GUI a tiny bit more complex, but it should be fine.

However, if you have very specific needs, such as segmenting a cylindrical core then you can do much better. You could ask the user to just place the centerpoint and use that to position a cylinder (you could accept numeric input for the diameter). The user could then conveniently adjust the position and would not be forced to get everything right with a single drag-and-drop. If you the user specifies two centerpoints (on two different slices) and then you can define an entire 3D cylindrical core with a few clicks. If this is a frequent operation then you can even go further and automate it so that the user would not need to click at all but the large inner circle would be extracted fully automatically.

**Comment by lassoan** [comment]
The [Gel dosimetry](https://www.slicer.org/wiki/Documentation/Nightly/Modules/GelDosimetry) module works with a cylindrical ROI, you might get some useful ideas there.

**Comment by lassoan** [comment]
Having a checkbox seems to make the most sense - it could improve convenience in certain cases and would not make the effect's GUI much more complicated than it already is.

**Comment by jamesobutler** [comment]
This issue can be closed now that https://github.com/Slicer/Slicer/commit/93c64bb8cb2062ba921cf35f0b524024aa8562aa is in Slicer core?
