### ISSUE TITLE
Mechanism to customize the location of Slicer-XXXXX.ini

### ISSUE THREAD

**Issue by muratmaga** [Slicer/Slicer#6288]
As explained in this [discourse thread](https://discourse.slicer.org/t/slicer-ini-file-locations/22766), we would like to Slicer-XXXXX.ini to a persistent storage so that it is retained between different docker sessions. Slicer installation is baked into container (e.g., /home/docker/Slicer/, which is where the Slicer-XXXXX.ini is saved . 

M

**Comment by lassoan** [comment]
If the user is allowed to install extensions then a couple of folders need to be retained in the application home folder (Python site-packages, etc. - see details in the discourse thread), which cannot be moved. To reduce the number of folders to retain, the Slicer.ini file can be moved into the application home folder.

Since relocating the Slicer.ini file is already possible (just need to create a Slicer.ini file where the Slicer-NNN.ini file is), I don't think any further customization of ini file locations would be necessary.

**Comment by lassoan** [comment]
> If the base install need to be immutable while allowing extensions and settings to be manager externally, Slicer could be built in the container with `Slicer_STORE_SETTINGS_IN_APPLICATION_HOME_DIR` set to `OFF`.

This worked in the past but not anymore (only in special cases). Since now extensions may pip-install Python packages (and those are installed in site-packages folder in the application home folder) having an immutable application home folder is not a viable anymore. It can only work if users never need to install any extensions that may pip-install Python packages.
