### ISSUE TITLE
Problem loading labelmap color table with lots of labels

### ISSUE THREAD

**Issue by fbordignon** [Slicer/Slicer#6354]
A labelmap with 50k labels loads but the color table is messed up.
I figure it is because of:
https://github.com/Slicer/Slicer/blob/5b87a6abf59bc37d0d4baf7362a91e9e8dd4f188/Libs/MRML/Core/vtkMRMLColorTableStorageNode.cxx#L34-L35
Why this limit was imposed? Was it taking too long to load an invalid color table file?
I guess the error check to be done here is to prevent overflowing the `vtkMRMLColorTableNode` number of colors (int). Am I correct in assuming that?

**Comment by pieper** [comment]
You'd need to look into the implementation to know for sure.  It may be an arbitrary limit or it might have been driven by a (possibly out of date) limit in the underlying VTK implementation.  Unfortunately the original developer of that part of the code isn't with the project at this point.

**Comment by lassoan** [comment]
The limit was introduced in this commit:

```
Revision: 8af2668b09584ce33c5166041fc1378c2c056804
Author: Nicole Aucoin <nicole@bwh.harvard.edu>
Date: 2010-03-22 1:38:06 PM
Message:
BUG: added a lot of error checking and breaking loops when find errors. When reading in a color file, check that the max id is < 1 million to try and avoid parsing text files and getting huge max id values
svn-url: http://viewvc.slicer.org/viewvc.cgi/Slicer4?view=revision&revision=12423
git-svn-id: http://svn.slicer.org/Slicer4/trunk@12423 3bd1e089-480b-0410-8dfb-8563597acbee
```

Since drag-and-dropping a text file makes Slicer read it as a color table by default, it makes sense to have some kind of limit to make sure that having some large numbers in a text file will not make Slicer hang or crash with out-of-memory error.

The 32768 value is not very small, I find it reasonable as a maximum number, but we could increase it. @fbordignon what is that maximum value that would work for you?

We could remove the check if we made file validity check smarter. For example, we could reject the file if a line is too long, RGB values are missing, or RGBA values are out of range.

We could also change the behavior so that the maximum number is only limited for .txt files, and only for those that does not start with `# Color table file`, because that makes it quite likely that it is not a valid color table file.

In the long term, we should move away from this format (it does not even support space in the label name) and use some standard csv or json-based format instead.

**Comment by fbordignon** [comment]
I am not sure what a reasonable limit should be. 2^20 should probably work for all cases I got. I've changed the maximum for our version. I am raising the issue because Slicer can save a ctbl file with more than 32k colors but cannot load it.

We are using porespy and other libs to [partition ](https://porespy.org/examples/filters/tutorials/snow_partitioning.html) pores and grains. Hence, for big images it generates labelmaps with lots of labels, one for each pore. I've reached the 32k limit with a 2D thin section image, for 3D images things get uglier faster.

**Comment by lassoan** [comment]
I've created a PR that increases maximum color entries for color tables to 1million. Also improved loading time for sparse color tables that have very large color IDs: loading time was several minutes before the optimization, now it is a few seconds.

https://github.com/Slicer/Slicer/pull/6358
