### ISSUE TITLE
Download a module

### ISSUE THREAD

**Issue by 1191620** [Slicer/Slicer#6436]
how can I download and use [BrainTissuesExtension](https://www.slicer.org/wiki/Documentation/4.8/Extensions/BrainTissuesExtension)

**Comment by lassoan** [comment]
The extension has not been ported to the latest Slicer versions. You have already contacted the maintainers - https://github.com/CSIM-Toolkits/BrainTissuesExtension/issues/5 - you will see if they are willing to do it. If they update their extension then it will appear in the Extensions Manager.

If they don't update it then you can do it yourself, by building Slicer and that extension, and fix any errors that come up (usually trivial issues due to API and  C++ syntax changes). You may also consider using alternative solutions - see https://discourse.slicer.org/t/anatomical-brain-segmentation/17778 and https://discourse.slicer.org/t/automated-brain-segmentation-into-white-matter-volume-gmv-and-csf-vol/19322 and https://discourse.slicer.org/t/whole-brain-automate-segmentation/21225

If you want to further discuss automatic brain segmentation options, please post your questions on the Slicer Forum. This issue tracker is for keeping track of problems in Slicer core.

**Comment by 1191620** [comment]
> The extension has not been ported to the latest Slicer versions. You have already contacted the maintainers - [CSIM-Toolkits/BrainTissuesExtension#5](https://github.com/CSIM-Toolkits/BrainTissuesExtension/issues/5) - you will see if they are willing to do it. If they update their extension then it will appear in the Extensions Manager.
> 
> If they don't update it then you can do it yourself, by building Slicer and that extension, and fix any errors that come up (usually trivial issues due to API and C++ syntax changes). You may also consider using alternative solutions - see https://discourse.slicer.org/t/anatomical-brain-segmentation/17778 and https://discourse.slicer.org/t/automated-brain-segmentation-into-white-matter-volume-gmv-and-csf-vol/19322 and https://discourse.slicer.org/t/whole-brain-automate-segmentation/21225
> 
> If you want to further discuss automatic brain segmentation options, please post your questions on the Slicer Forum. This issue tracker is for keeping track of problems in Slicer core.

thanks for your help.
