### ISSUE TITLE
fail to build master branch due to fatal error: QSignalSpy: No such file or directory

### ISSUE THREAD

**Issue by hubutui** [Slicer/Slicer#6437]
## Summary

fail to build master branch:
```
/build/3dslicer-git/src/3dslicer/Base/QTCore/qSlicerExtensionsManagerModel.cxx:31:10: fatal error: QSignalSpy: No such file or directory
   31 | #include <QSignalSpy>
      |          ^~~~~~~~~~~~
compilation terminated.
```
see also the complete build log [here](https://github.com/Slicer/Slicer/files/8934955/log.txt.tar.gz). You could jump to the line 72251 for the error messages.

Maybe we forget to add `testlib` according to Qt official [doc](https://doc.qt.io/qt-5/qsignalspy.html)?

## Steps to reproduce

I build 3dslicer with this [PKGBUILD](https://github.com/archlinuxcn/repo/blob/8c62f8b6aca24634780329e42c49286236610ebf/archlinuxcn/3dslicer-git/PKGBUILD) on ArchLinux with minor modification. I use
```
make -C "build" VERBOSE=1 
```
to print more information.

## Environment
- Slicer version: the master branch, date 20220619
- Operating system: ArchLinux

**Comment by pieper** [comment]
Yes, I ran into this too, and it's because `QSignalSpy` was added in Qt 5.14 but some linux distributions have an older Qt by default (ubuntu 20.04 is on Qt 5.12 for instance).

These instructions describe how to build on linux with the latest Qt:

https://slicer.readthedocs.io/en/latest/developer_guide/build_instructions/linux.html#any-distribution

As a workaround, I just commented out the `QSignalSpy` for a local developer build since extensions aren't needed anyway.  

I don't know about Qt>=5.14 on ArchLinux, but hopefully we'll all move to Qt6 before too long.

https://github.com/Slicer/Slicer/issues/6388

I'm going to close this since I don't believe we should do anything about it, but if others feel differently we could reopen.  Perhaps an ifdef version check so the code still compiles by default would be worth it.

**Comment by hubutui** [comment]
ArchLinux provides [qt 5.15.5+kde+r163](https://archlinux.org/packages/extra/x86_64/qt5-base/). The qt source upstream is https://invent.kde.org/qt/qt.
Qt 6.3.1 is also available. I would follow the workaround until we could build with Qt 6.

**Comment by jamesobutler** [comment]
@pieper @lassoan Thoughts on setting Qt 5.15 as the minimum required version for all platforms? For the transition to Qt6 the recommendation is to go to 5.15 first and solve deprecations (https://doc.qt.io/qt-6/portingguide.html).

We had set the minimum to Qt 5.15 in https://github.com/Slicer/Slicer/commit/117185ded4709017ec6b2c43d54bc0e1c2d053d9 for all platforms, but then had relaxed it back down to Qt 5.12 for Linux in https://github.com/Slicer/Slicer/commit/35ef5e41cb04a31a2b873adcdcf3475d1a88817d.

**Comment by pieper** [comment]
In my experience this one use of `QSignalSpy` in the extensions is the only thing that needs Qt>5.12 except for testing.  I would be fine requiring 5.15 everywhere so that people get an issue at cmake time instead of a build error.  People with older Qt could build with `Slicer_BUILD_EXTENSIONMANAGER_SUPPORT` turned off.  As much as I'd like Slicer to build out of the box on a wide range of systems, putting effort into Qt6 is a better investment.

**Comment by jamesobutler** [comment]
cc: @chir-set based on https://discourse.slicer.org/t/fyi-small-patch-to-build-slicer-on-arch-linux/23961

**Comment by lassoan** [comment]
I'm working on an alternative method for waiting on a signal (using QEventLoop instead of QSignalSpy). QSignalSpy is a test class, so it may not be nice to use it in application code anyway.

That said, QSignalSpy has been around for a really long time and the `wait` method that we use was added in Qt-5.0. So, I'm not exactly sure why it was not found in Qt-5.12.

**Comment by lassoan** [comment]
Good point, I'll look into using qRestAPI::sync.

**Comment by jcfr** [comment]
> That said, QSignalSpy has been around for a really long time and the wait method that we use was added in Qt-5.0. So, I'm not exactly sure why the class is not found when using Qt-5.12.

Until recently, we have been using the `QSignalSpy` class only in testing code, and the dependency to the Qt `Test` library is only added when `BUILD_TESTING` is `ON`. This likely explained what we started to see the see only with the extension refactoring.
 
https://github.com/Slicer/Slicer/blob/82a22594db5b67720cae772da1d2b63a27d8fea6/CMakeLists.txt#L627-L629

**Comment by pieper** [comment]
Ah, yes, makes sense, thanks for sorting this out.  Better to avoid using testing classes in a non-testing builds.  I was misled by [this method](https://doc.qt.io/qt-6/qsignalspy.html#QSignalSpy-2) only being around since 5.14.
