### ISSUE TITLE
Did a GPA and now cannot restore 3D viewer to normal

### ISSUE THREAD

**Issue by danielleswasserman** [Slicer/Slicer#6450]
![image](https://user-images.githubusercontent.com/18664216/175754756-dff8c802-5341-41a3-b0df-8e58e722b5ef.png)

Dear Community,
I did a GPA (was a test, have not gotten them to work properly yet) and now, despite having cleared the field for data entry in the GPA tool of Slicermorph module, I cannot get the bounding box back to focusing on my models and markups.

Is there a node here that I can safely delete that will fix the problem? I have been reading the node information and some language does seem to be GPA related but I am not sure and cannot afford to ruin this project file. So far I have been unable to successfully export my data or save it properly so that my markups do not merge across specimens. I'm working on that. Here is a snap that includes some of the possibly-safe nodes to delete. I would include a link to a zipped project file but like I said, I don't have a handle on doing that right yet. I've had to re-position landmarks several times now. Does anyone know what to do about the bounding box?
![image](https://user-images.githubusercontent.com/18664216/175755093-1467fd1a-722b-4d5e-84d5-1dfda79bb9a0.png)
 

Sincerely,
Danielle

**Comment by lassoan** [comment]
Everything looks OK here, except that you have two nodes in the scenes that are very, very far from each other. When you reset the field of view in the 3D view, you include everything in that purple box, and so the box becomes very big, and the useful content is relatively small compared to that.

Most data sets are defined in a coordinate system where the origin is near the center or one of the corners of the data set. In your case, either the origin was really far off, or GPA created some data with coordinates very far from the origin. Either way, you can fix this by removing nodes that are far from your region of interest (or transform them to bring them closer to the region of interest).

Since this question is not related to Slicer core but to the SlicerMorph extension, I close this issue here. Please open an [issue in the SlicerMorph repository](https://github.com/SlicerMorph/SlicerMorph/issues) or start a discussion on the [Slicer forum](https://discourse.slicer.org) if you continue to have problems.
