### ISSUE TITLE
Add support for VRD format from VINNO equipment

### ISSUE THREAD

**Issue by alvarosg** [Slicer/Slicer#6512]
The only reference to the format I found is from [here](https://www.sonoportal.com/api/files/download?code=a203eecc-df5e-4d69-83ee-ccdf5e1d693b). Based on that it should be possible to convert it to DICOM, but the software seems to be proprietary and not readily available.

I would be happy to provide some examples files I got from a scan, and/or take any help/advice to figure out how to parse the files (it was not obvious from a Hex dump).

Thanks in advance!

**Comment by lassoan** [comment]
I would recommend to export to DICOM format. Slicer already has many DICOM import plugins and they can be enhanced to extract all relevant information. If there are some extra information in private fields then for example you can add some more special cases to the DICOM ultrasound plugin in https://github.com/SlicerHeart/SlicerHeart/tree/master/DicomUltrasoundPlugin to use those.

If VINNO ultrasound's DICOM export completely misses some information (e.g., you cannot export 3D volume as DICOM at all) then you can add a file I/O plugin, most conveniently implemented in Python. First you need to get the file specification from the vendor or reverse-engineer the file format. You can find a basic tutorial for medical image file format reverse engineering [here](https://github.com/PerkLab/PerkLabBootcamp/blob/master/Doc/Appendix/MedicalImageResearchFileFormats.pptx). You may also reach out for help (either find other developers who are interested in this or you can contract) at the [Slicer forum](https://discourse.slicer.org).

Since such custom file readers are not implemented in Slicer core, but in extensions, and this issue tracker is for Slicer core, I'm closing this issue.
