### ISSUE TITLE
Fix commit check

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#6692]
## Summary

Check seems to incorrectly report error even when the associated message should be correct. 

## Steps to reproduce

Commit with the following title:

```
BUG: slicer.util.plot: If no title, use column name as series names 
```

is report failure:

```
Error: Error: The first line has to start with the type (e.g "ENH: Add support for awesome feature"). For more details, see https://slicer.readthedocs.io/en/latest/developer_guide/style_guide.html#commits
```

See https://github.com/Slicer/Slicer/actions/runs/3525070397/jobs/5911316779

## Expected behavior

Check should pass

## Environment

NA

**Comment by jamesobutler** [comment]
@jcfr re https://slicer.readthedocs.io/en/latest/developer_guide/style_guide.html#commits, the subject line is not capitalized because after the commit prefix it is `slicer` and not `Slicer`. However this specific commit title is weird in that a specific method of `slicer.util` is being used which is not `Slicer.util`, therefore I would suggest a re-worded message that doesn't include the method as the start of the subject line after the commit prefix.

Here it describes the commit prefix, followed by a colon, followed by a space, followed by a capitalized A-Z character.
https://github.com/Slicer/Slicer/blob/44d626d08b5c675523ce9793c532c647dc9506bf/.github/workflows/commit-message.yml#L21
