### ISSUE TITLE
can we open a folder of nifti files inside slicer by subprocess command of external python file

### ISSUE THREAD

**Issue by kmordhwaj** [Slicer/Slicer#6787]
I am facing this issue.
I am trying running an external python file (not in python shell of slicer) where I am automating the process to open 3d slicer and place NIFTI files present inside a folder.
But able to open only a file at a time but facing an error while uploading the folder.
Can you guys help me find the way to open a 3d slicer with a folder directory?

**Comment by pieper** [comment]
Hi - I guess you are also user kmordhwaj on Slicer discourse - welcome to the community 👍 

To make it more efficient for everyone, please only post the question once and if you don't get a response in a few days post a follow up on the same thread perhaps adding more context or information so that people can better understand what you are asking.  Please understand that we want to help but our resources are limited.

**Comment by jamesobutler** [comment]
Support help to be provided on this thread on the Slicer discourse:
https://discourse.slicer.org/t/can-we-upload-more-than-50-nifti-files-at-a-time-with-a-link-or-can-we-upload-a-folder-of-these-much-nifti-files-through-script-in-3d-slicer/27359
