### ISSUE TITLE
Toggle markups toolbar option is not visible

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#6830]
## Summary

"Toggle markups toolbar" option is not visible in the dropdown menu of the place mode button in the mouse mode toolbar.

@jamesobutler could you check? It might be related to https://github.com/Slicer/Slicer/commit/32675b18cb60123a7a873889f8c7383549e3ad27

## Steps to reproduce

- Click Toggle markups toolbar to show the toolbar
- Create a new point list, drop a point in a view
-> ERROR: Cannot show/hide the markups toolbar by clicking on the down-arrow button of the place mode button ("Toggle markups toolbar" option is not visible)

This error is displayed in the Python console: `[Qt] QWindowsWindow::setMouseGrabEnabled: Not setting mouse grab for invisible window QWidgetWindow/'PlaceWidgetMenuWindow'`

## Expected behavior

When placing points, clicking the down-arrow button of the place mode button should show "Toggle markups toolbar" action in the dropdown menu.

## Environment
- Slicer version: Slicer-5.3.0-2023-02-10
- Operating system: Windows

**Comment by jamesobutler** [comment]
The change made in https://github.com/Slicer/Slicer/commit/0ad10f0cb406d25c8d2ea62058b31dcc33173bdf appears to be the cause. Prior to that commit when placing a point list and dropping a point in the view, the "Toggle Markups Toolbar" action was removed from the MouseModeToolBar (it was its own QToolButton) and added as an action to the Place Toolbutton's PlaceWidgetMenu. The action was added/removed between these 2 locations as it switched between various states.

https://github.com/Slicer/Slicer/commit/0ad10f0cb406d25c8d2ea62058b31dcc33173bdf was aiming to remove this adding/removing of the action so that I could appropriately remove the action as part of a custom application that hides the markups toolbar. It appears I changed the action to show/hide instead, but decided to show/hide the Toggle Markups Toolbar QToolButton, while the same reference of the action is used in the PlaceWidgetMenu. That is why we observe the PlaceWidgetMenu not showing the toggle markups action because the action associated with it's own QToolButton is set to not be visible. 

For the "Toggle Markups" action to be both
- visible in the PlaceWidgetMenu, but hidden as its own QToolButton in the MouseModeToolbar 
- hidden in the PlaceWidgetMenu, but visible as its own QToolButton in the MouseModeToolbar

it appears that it would need 2 action objects that both toggle markups toolbar, but that each have their visibility flipped relative to the other. @lassoan What do you think?
