### ISSUE TITLE
Text 

### ISSUE THREAD

**Issue by Dr-Arakeep90** [Slicer/Slicer#7081]
## Summary

when I tried to write a text on my model using text tool the text was sooo bad and I will attach a screen shoot
![111](https://github.com/Slicer/Slicer/assets/110288025/17364b8d-a35c-4f77-8455-a6f5ada1d601)

## Steps to reproduce

I tries to write a text simply on my produced model but couldn't do that
## Expected behavior

I expected adequate mean of writing either by emboss or engrave.

## Environment
- Slicer version: Slicer-5.2.2
- Operating system
Windows 11
![111](https://github.com/Slicer/Slicer/assets/110288025/41c789c0-9296-4f60-b83d-86648cfc1c97)

**Comment by lassoan** [comment]
When you are editing segments in Segment Editor, the source representation of the data is a binary labelmap. Level of details is limited by the resolution of this underlying binary labelmap. You can make the text larger to make it readable at the current resolution, or increase the resolution (reduce the spacing) of the binary labelmap using the "Specify geometry" button (next to the "Source volume" selector).

If you have questions about using Slicer, please post it on the Slicer forum instead of submitting as a bug report, as many more community members are available there to help and users can find answered questions there more easily..
