### ISSUE TITLE
Support adjusting the Thick Slab Reconstruction (TSR) thickness directly from slice views

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7083]
## Is your feature request related to a problem? Please describe.

Support adjusting slab reconstruction thickness directly from the slice views.

## Describe the solution you'd like

* Represent slab thickness in 2D view using a center line representing the slice, and two slab marker lines
  * Distance between the two lines represents the current slab thickness
  * This could be done in a new displayable manager called `vtkMRMLSlabReconstructionDisplayableManager`
* Add support for adjusting slab thickness by updating the location of any of the slab marker lines.
  * By symmetry, updating the position of one marker line will lead to an update update the position of the other ones.
  * To separate concern, a new "Slicer VTK widget" may have to be integrated.

## Describe alternatives you've considered

NA

## Additional context

* https://github.com/Slicer/Slicer/issues/6965

_Originally posted by @jamesobutler in https://github.com/Slicer/Slicer/issues/6965#issuecomment-1577441236_

> For generating Volume Projections for users without scripting our group created the following module based implementation (not currently public):
> 
> We utilize a module that upon pressing a checkable "View Projection" button, a vtkMRMLMarkupsROI appears for defining the region for generating the MIP. The thickness used is therefore set by the size of the Markups ROI. By default the ROI is set to the full bounds of the volume. In the example below the projection is shown in the green slice (coronal) viewer. It will automatically updated when the ROI is manipulated in the various slice viewers. We define what volume node to act upon in a different area, but you could imagine specifying a input volume node as well.
> 
> | View Projection Off | View Projection On (MIP shown in green slice)|
> |-----------------------|---------------------|
> |![image](https://github.com/Slicer/Slicer/assets/15837524/0e05fbe1-83ef-494d-8039-1bad3011d4d7)|![image](https://github.com/Slicer/Slicer/assets/15837524/506dbd66-92c4-4332-9f44-9bf7f9e84d43)|
> 
> | Volume Projection Module | Projection Types| Axis of Projection |
> |-------------------------------|-------------------|--------------------|
> |![image](https://github.com/Slicer/Slicer/assets/15837524/c6cac56e-76b6-4bd9-b07a-ce035ea70090)|![image](https://github.com/Slicer/Slicer/assets/15837524/8c81dade-d1c3-4348-ae9a-50c8835e12d4)|![image](https://github.com/Slicer/Slicer/assets/15837524/9e806fb4-97a8-47ee-b6b0-a3299b1fc289)|

            
cc: @lassoan

**Comment by tao558** [comment]
A question about how we should display the thick slab lines when we are using different slice intersection options.

When we are viewing the slice intersection lines in interactive mode without any kind of thick slab reconstruction lines, you can view either the full lines, or skip the line crossings. In the "skip line crossings" mode, a circle around the intersection point of the two lines erodes the line segments. I've attached two example images (`full_lines.png` and `skip_crossings.png`) with this option on / off (note the checked option in the intersection widget)

How should we handle this option when the thick slab reconstruction is enabled? Should those lines also be eroded, or should the full lines also be displayed? I attached two additional images (`full_lines_with_tsr.png` and `skip_lines_with_tsr.png`) for how the feature currently works with / without "skip line crossings" enabled. Currently the full line is always displayed
![full_lines](https://github.com/Slicer/Slicer/assets/26352734/2023b972-2c8b-442a-9882-21fc8beb1367)
![skip_crossings](https://github.com/Slicer/Slicer/assets/26352734/259ebc5d-9305-4606-b3e1-8d5eb9489701)

![full_lines_with_tsr](https://github.com/Slicer/Slicer/assets/26352734/a0dfe2da-6df0-4758-9c20-659d9be1545c)
![skip_lines_with_tsr](https://github.com/Slicer/Slicer/assets/26352734/b4d84e9c-4b66-4458-85e9-3d4c2ab9d7f2)

**Comment by pieper** [comment]
The current behavior doesn't look too bad to me.

**Comment by jamesobutler** [comment]
Is the center (non-slab) intersection necessary when viewing the slab? If not then just having the 2 seems to make more sense then the 3. 

Otherwise the "thick slab" lines being some X number of pixels thicker than the regular slice intersection current thickness could help identify them as being something different.

**Comment by jcfr** [comment]
> having the 2 yellow lines seems to make more sense then the 3 yellow lines.

Until we can have dashed line working, that seems like a sensible path forward.

**Comment by tao558** [comment]
Thanks all for the responses. 

> having the 2 yellow lines seems to make more sense then the 3 yellow lines.

If I'm understanding correctly, the user wouldn't be able to adjust the slab thickness __and__ interactively move the slice at the same time. They'd need to remove the TSR, move the slice, then re-enable the TSR. This might make sense anyway, since when I add interactivity, the handles for moving the slice / the handles for adjusting the thick slab lines might overlap a bit.

If you don't mind this toggling on / off, I can remove the center line when TSR is enabled. Just wanted to point this out!

**Comment by jcfr** [comment]
What about updating the following:

<img width=30% src="https://github.com/Slicer/Slicer/assets/219043/995fd741-f12c-4111-92f5-e393a08baa40"/>

to include:

* [ ] Interaction


That way the user decide if both `slice intersection` and `TSR` should be visible and interactive.

**Comment by tao558** [comment]
@jcfr and I just got off a call discussing this.

In short, the TSR options and the slice intersection options are going to be totally independent / in separate UI elements. All TSR options are going to be in the dropdown menu for each slice view (see below), instead of in the slice intersection widget. I'll add another option
* [ ] Interaction

to the menu


![tsr_ui](https://github.com/Slicer/Slicer/assets/26352734/248ab95e-3dd6-4a88-88a1-a35c9ca2b72f)

This includes options for toggling the display and interactivity. The slice intersection widget will only contain options for the slice intersection interactivity / display.

Thanks everyone for the input.
