### ISSUE TITLE
Support for 3D Clipping of segmentation representation

### ISSUE THREAD

**Issue by jcfr** [Slicer/Slicer#7494]
## Is your feature request related to a problem? Please describe.

In the context of 3D visualization where segmentation are represented as surfaces, we often need to be able to also visualize the underlying structures.

Depending on the workflow and application, there are a few approaches to support this:
1. Adjust opacity of the surface
2. Convert the segment to a model, hide the segment (or segmentation), and enable `3D clipping`[^1]

In the context of workflow where clipping is preferred, this requires multiple steps that can either be done manually or programmatically. 

[^1]: https://slicer.readthedocs.io/en/latest/user_guide/modules/models.html

_Issue created following offline discussion with @sjh26_

## Describe the solution you'd like

To more easily leverage the model `3D clipping` capabilities, there are few possible path forward:
- add first-class support for `3D clipping` for segmentation representations
- make surface segmentation available (as "read-only"?) MRML model node allowing to re-use existing functionality

**Comment by lassoan** [comment]
We should add slice clipping to segmentations. We haven't done it mostly because the current implementation is not very nice with the hardcoded 3 slice views. If we touch it then adding a capping option would be useful, too.

Adding model nodes could cause so much user confusion. If somebody needs it then it could be added by a couple of lines of a Python script.
