### ISSUE TITLE
incorrect z spacing for single file dicom

### ISSUE THREAD

**Issue by SimonRelu** [Slicer/Slicer#7496]
## Summary

The `SpacingBetweenSlices` and `SliceThickness` tag are not correctly read. Instead, `1` is used as the z spacing.

## Steps to reproduce

See the following dicom: https://drive.google.com/file/d/1gcGC6NgRwyeNV-8Vunm5W8AEZT2HrHii/view?usp=sharing (this is a segmentation mapping of a CBCT)

Opening the dicom in other software like MeVIsLab shows the correct dimensions

## Environment
- Slicer version: Slicer-5.6.1 r32438
- Operating system: Mac 13.1

**Comment by lassoan** [comment]
This instance has several serious flaws. The safest would be to reject it completely, as the developers of the software that has generated it don't know even some of the most important DICOM concepts.

Most serious issues:

1. Slice position information is missing. Therefore, you cannot reconstruct a 3D volume from this. Slice thickness is not the same as slice spacing (slice thicnkess tells how blurred the image is along the slice normal, does not tell the position of each slice). See this post of the main author of the DICOM standard for more information: https://dclunie.blogspot.com/2013/10/how-thick-am-i-sad-story-of-lonely-slice.html

2. This is a standard "CT Image Storage" IOD, which I don't think is allowed to store multiple frames.

DCIODVFY reports the following further problems with the file:

```
Error - Scaled numeric values for same concept are inconsistent - Exposure = 143 and ExposureInuAs = 141410
CTImage
Warning - is only permitted to be empty when actually unknown; should be absent (not empty) if an unpaired body part, and have a value if a paired body part - attribute <Laterality>
Error - A value is required for value 3 in CT Images - attribute <ImageType>
Error - Unrecognized enumerated value <0x8> for value 1 of attribute <Bits Allocated>
Error - Unrecognized enumerated value <0x8> for value 1 of attribute <Bits Stored>
Error - Unrecognized enumerated value <0x7> for value 1 of attribute <High Bit>
Warning - CTDIvol is present but it is uninterpretable without CTDIPhantomTypeCodeSequence, which is absent - attribute <CTDIvol>
Error - Unrecognized enumerated value <0x284> for value 1 of attribute <Number of Frames>
Warning - Attribute is not present in standard DICOM IOD - (0x0018,0x8151) DS X-Ray Tube Current in uA
Warning - Attribute is not present in standard DICOM IOD - (0x0028,0x0008) IS Number of Frames
Error - Attribute with an even group number is not a recognized standard attribute - (0x0666,0x0999)  ?
Warning - Attribute is not present in standard DICOM IOD - (0x0666,0x0999)  ?
Warning - Dicom dataset contains attributes not present in standard DICOM IOD - this is a Standard Extended SOP Class
```

It is hard to tell what is the best way to deal with an invalid image, so I don't say that it is a bug in MeVisLab that it just takes the slice thicnkess and uses it as spacing, but we chose a different approach in Slicer. We don't relax the rules or add special cases in the DICOM image loader to deal with invalid DICOM files. Instead, we keep the image loader clean and standard-compliant, and have a separate "DICOM Patcher" module that attempts to fix some common mistakes. The DICOM Patcher module's "Generate slice position for multi-frame volumes" rule (enabled by default) will generate the missing slice positions, derived from the slice thickness field, which will allow standard-compliant DICOM viewers to reconstruct the 3D image correctly.

I would recommend to contact the developer of the software that created the image and ask them if they have a more recent software version where this issue is fixed. If they are not aware that their images are invalid then you can recommend them to contact David Clunie for advice on how to fix their issues.

---

The only thing I would consider changing in Slicer is to refuse loading of this image and/or display a more specific error message (that the image cannot be loaded/take caution, because slice position information is missing).

**Comment by lassoan** [comment]
I see that "Spacing Between Slices (0018,0088)" tag is specified in the image, which can be used for 3D reconstruction from slices. However, this field cannot just be thrown into a standard CT IOD, but it has to be in an Enhanced CT image IOD, in a ["Pixel measures" sequence](https://dicom.innolitics.com/ciods/enhanced-ct-image/enhanced-ct-image-multi-frame-functional-groups/52009229/00289110/00180088).

What we could do in Slicer is to improve DICOM patcher to use "Spacing between slices" if present (instead of slice thickness).

**Comment by pieper** [comment]
Maybe it's just me, but I find this pretty funny - just adding NumberOfFrames and SpacingBetweenSlices to a CT image is actually a pretty reasonable approach to define a volume in a single instance when all the other tags are constant over the frames.  It avoids all the complexity of per-frame and shared functional groups and multiframe dimensions modules.  The [vendor](https://www.morita.com/group/en/specialists/digital-cone-beam-computed-tomography-in-radiology/7917/) looks legitimate and maybe they gave up on the complexity of the multiframe IODs and just used this as a convenient workaround.  This simple approach might have been more popular than the enhanced multiframes have turned out to  be.

We shouldn't create this kind of non-standard object, but it wouldn't be much work if we wanted to read them natively if it turns out they are common in the field.

**Comment by lassoan** [comment]
> just adding NumberOfFrames and SpacingBetweenSlices to a CT image is actually a pretty reasonable approach to define a volume in a single instance when all the other tags are constant over the frames

I would prefer to use this simple way of storing a 3D volume, because it would make both the scanner/reconstruction software and viewers simpler and faster.

However, letting each vendor simplify the standard their own way would cancel all the advantages of simplicity, because then viewers would need to implement a custom logic for each vendor. For example, Dolphin dental CBCT images use "slice thickness" for specifying spacing between slices - should we accept that as well?

> Maybe it's just me, but I find this pretty funny 

I agree that those functional groups seem way too complex for what they provide, but should be tolerable. Considering the overall effort of building a CBCT image acquisition system, getting regulatory approval, etc. it is unreasonable that vendors pay so little attention to DICOM compliance.

For me, the complexity and inefficiency reaches the "funny" level in functional groups in segmentation objects. I can understand if vendors are reluctant to spend time with understanding and following that part of the DICOM standard.

**Comment by pieper** [comment]
Of course we can't let vendors just make up their own conventions and expect things to be interoperable.  And really, yes, an enhanced multiframe CT is not a complex very object and a serious vendor should take the time to support it.  But the evidence shows that they did not, so we'll learn what we can from that.

**Comment by lassoan** [comment]
We should bring this up with David Clunie at the project week. I don't expect that he will embrace this idea right away, but at least it is worth a try.

**Comment by SimonRelu** [comment]
Hey thank you very much for looking into this and sorry for not responding sooner. I was away for the holidays.

It would be great if you could support dicoms that just have the NumberOfFrames and SpacingBetweenSlices. I was wondering if there is any update on this

**Comment by lassoan** [comment]
> It would be great if you could support dicoms that just have the NumberOfFrames and SpacingBetweenSlices.

We will not support seriously messed up DICOM files, such as the one that you shared.

- Workaround: You can use `DICOM Patcher` module in Slicer to make the image suitable for reading.
- Solution: Let the imaging vendor know that they generate invalid DICOM images. If they don't want to specify position of each slice then they can use an `Enhanced CT image IOD` and put the slice spacing in the appropriate shared functional group as described in the DICOM standard.

We will discuss with David Clunie if the DICOM standard could be simplified to make it easier for vendors to write valid DICOM files. However, a change is quite unlikely, as a new "simplified" slice spacing definition could not replace the current ways of doing it, but it would be an additional option, so it would increase the overall complexity of DICOM standard and its implementations.

I'm closing this issue, as no change in Slicer core is expected related to this.

**Comment by lukepolson** [comment]
@lassoan I'm trying to save 3D reconstructed images in PyTomography such that they can be opened in Slicer. What field should I then use to specify the spacing between Z planes? I was originally assuming "SliceThickness" should do this, but I see here that that isn't the correct attribute. What header should I add to the DICOM file such that it loads the correct z-spacing?

**Comment by lassoan** [comment]
In most cases, you cannot specify a spacing value. Instead, you specify the image geometry by setting the image position patient, image orientation patient, and pixel spacing tags for each image slice. There are many rules for a valid DICOM image, so I would recommend to use an existing valid DICOM image (coming from a clinical imaging device) as template and then verify the validity of the final result by using David Clunie's DCIODVFY tool.

**Comment by lukepolson** [comment]
I see. For the time being, I modified the `ds.SpacingBetweenSlices` value and it seems to load with the correct z-plane spacing in Slicer, giving the correct aspect ratio upon loading. Are you saying that this is insufficient for proper DICOM standard, however?

**Comment by lassoan** [comment]
If you use an enhanced IOD then you can put the spacing field in a shared functional group. DCIODVFY can detect many non-conformances, so if it does not report any errors or warnings then probably your images are OK. These enhanced IODs are nice because they are more modern and they allow storing of a 3D volume in a single file. However, they are not commonly used and still not supported by most software.

If you want to make your images loadable in most DICOM-compatible software, you can use a classic IOD (with each frame stored in a separate file, slice position stored in each file).
