### ISSUE TITLE
Orientation marker is collapsed when shadow visibility is enabled

### ISSUE THREAD

**Issue by lassoan** [Slicer/Slicer#7518]
## Summary

Recently, shadows visibility (using SSAO render pass) has been added to 3D views in Slicer. Unfortunately, enabling shadows visibility breaks display of orientation marker in 3D views: the orientation marker appears transparent or turned inside out.

## Steps to reproduce

1. Show cube orientation marker (using 3D view controller) - the orientation marker shows up correctly

![image](https://github.com/Slicer/Slicer/assets/307929/9b6c432f-bfac-4af1-b670-b8f296da5947)

2. Enable shadow visibility (using 3D view controller) => ERROR: the orientation marker backsides appear (while they should be occluded)

![image](https://github.com/Slicer/Slicer/assets/307929/6a89b7d6-b927-43f4-9254-02f6c5e8e99c)

## Environment
- Slicer version: Slicer-5.7.0-2023-12-31
- Operating system: Windows 11

**Comment by lassoan** [comment]
@sankhesh @LucasGandel do you have an idea of what can cause this?
The orientation marker is rendered in a different layer by a separate renderer (https://github.com/Slicer/Slicer/blob/main/Libs/MRML/DisplayableManager/vtkMRMLOrientationMarkerDisplayableManager.cxx#L220).

**Comment by lassoan** [comment]
If the renderer's `SetUseSSAO(true)` option is used then the problem does not occur. The problem occurs when a rendering pass is set as it is done in [this test](https://gitlab.kitware.com/vtk/vtk/-/blob/v9.3.0/Rendering/OpenGL2/Testing/Cxx/TestSSAOPass.cxx).

@LucasGandel is there a specific reason why the volumetric SSAO features (setting depth format and allow setting Get/SetVolumeOpacityThreshold) are not added to the renderer's built-in SSAO step?

**Comment by LucasGandel** [comment]
> If the renderer's `SetUseSSAO(true)` option is used then the problem does not occur. The problem occurs when a rendering pass is set as it is done in [this test](https://gitlab.kitware.com/vtk/vtk/-/blob/v9.3.0/Rendering/OpenGL2/Testing/Cxx/TestSSAOPass.cxx).
> 
> @LucasGandel is there a specific reason why the volumetric SSAO features (setting depth format and allow setting Get/SetVolumeOpacityThreshold) are not added to the renderer's built-in SSAO step?

My guess is that the problem comes from the delegate pass. Using the renderer's `SetUseSSAO(true)` option results in the SSAO pass having only vtkOpaquePass as delegate (no translucent pass nor volumetric pass), see here: https://gitlab.kitware.com/vtk/vtk/-/blob/master/Rendering/OpenGL2/vtkOpenGLRenderer.cxx?ref_type=heads#L498

SSAO for volumes has not been implemented at the renderer level because it is just extra work (I don't have funding/time for it). The renderer built-in SSAO option is just a convenient wrapper around the SSAO pass. The problem here is rather about the delegate pass that is a vtkRenderStepPass. The right approach is probably to use vtkSequencePass with a chain of vtkOpaquePass and vtkVolumetricPass only, and then fix the translucent cube actor issue if it still happens

**Comment by cpinter** [comment]
In case it helps anythingI have seen the same thing in Slicer 5.4.0 with SSAO in the Lights module turned on.

**Comment by lassoan** [comment]
I experimented with this a lot and have found that if I remove `this->MarkerRenderer->EraseOff();` then the orientation marker appears correctly. I don't really know why this fixes the issue though, so if you have a clean fix that is much better.

I'm also uncertain about this "fix" because there are similar additional layers (for displaying a ruler and color legend) and if I remove `EraseOff` for those then issues come up (point labels of occluded points become visible, which indicates that the Z buffer is cleared). Maybe these layers are different because they display 2D actors.

**Comment by LucasGandel** [comment]
> I experimented with this a lot and have found that if I remove `this->MarkerRenderer->EraseOff();` then the orientation marker appears correctly. I don't really know why this fixes the issue though, so if you have a clean fix that is much better.
> 
> I'm also uncertain about this "fix" because there are similar additional layers (for displaying a ruler and color legend) and if I remove `EraseOff` for those then issues come up (point labels of occluded points become visible, which indicates that the Z buffer is cleared). Maybe these layers are different because they display 2D actors.

This is awesome @lassoan! Thanks to your investigations, I now have a better understanding of the issue.
The cause for the orientation marker being transparent is that the **depth test is disabled** when the marker is rendered.
This happens because the SSAO pass restores the depth test state after rendering, and it received a disabled depth test before rendering. The overlay renderer is rendered after the SSAO pass of the first renderer, so it will also have a disabled depth test.
When Erase is enabled, the renderer will call its `Clear()` function which enables the depth test internally, this explains why removing EraseOff fixes the issue.
The right fix is to provide the SSAO pass with an enabled depth test, so that it restores this correct state after rendering.
`ostate->vtkglEnable(GL_DEPTH_TEST); ` should be implemented [here](https://gitlab.kitware.com/vtk/vtk/-/blob/master/GUISupport/Qt/QVTKOpenGLNativeWidget.cxx#L212), alongside with other Qt state changes that VTK expects.
Changing the Qt OpenGL state to match what VTK expects will fix the issue, but I need to do a bit more investigations before proposing the fix, as it changes the behavior when the main renderer has the EraseOff flag (which is probably something nobody wants but I need to make sure I don't introduce regressions with this fix)
I will update soon.

**Comment by lassoan** [comment]
Perfect, thank you so much, looking forward to the fix!

**Comment by LucasGandel** [comment]
I confirm this was the right fix. MR is here: https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10806

(The weird behavior I was experimenting can be solved with https://gitlab.kitware.com/vtk/vtk/-/merge_requests/10808 but you should not need it unless you enable SSAO in the orientation marker renderer)
