### ISSUE TITLE
Inclusion of class EndoscopyComputePath back in Endoscopy newest version

### ISSUE THREAD

**Issue by maribernardes** [Slicer/Slicer#7519]
## Is your feature request related to a problem? Please describe.

CurveMaker module makes use of EndoscopyComputePath class, which was part of Endoscopy.
However, EndoscopyComputePath has been removed from the most recent versions (I encountered the problem when updating to Slicer 5.6.1)

## Describe the solution you'd like

If possible, I would suggest to include EndoscopyComputePath back

**Comment by lassoan** [comment]
Since introduction of curves in Markups module in Slicer core, CurveMaker extension has become redundant. Instead of investing time into fixing CurveMaker, I would recommend to switch to markup curves, which provide many more features.

If you want to create a tube model from markup points then you can use MarkupsToModel extension.

It would make sense to retire CurveMaker extension - I'll submit an issue there.

**Comment by maribernardes** [comment]
Thanks for the suggestion. I will try markup curves as replacement
