### ISSUE TITLE
SlicerDMRI extension is not updating for 5.6.1

### ISSUE THREAD

**Issue by pieper** [Slicer/Slicer#7531]
## Summary

Even though the repository has been updated [Dec 15, 2023](https://github.com/SlicerDMRI/SlicerDMRI/commits/master/), the DMRI extension offered for 5.6.1 is still from Dec 12, 2023.  The s4ext file points to the master branch of SlicerDMRI for both 5.6 and the master branch of the extension index.  The SlicerPreview versions correctly offer a newer build with the most recent SlicerDMRI.

## Steps to reproduce

Try to install dmri in 5.6.1 and you are offered the older version.

5.6.1:

![image](https://github.com/Slicer/Slicer/assets/126077/83f90e48-0d20-46c4-a7ff-a851f0a1aed8)

Nightly:

![image](https://github.com/Slicer/Slicer/assets/126077/a5da4476-0ad6-4c40-9103-adab87a6c13f)

## Environment

For reference: #7530

Possibly related to: https://github.com/AIM-Harvard/SlicerRadiomics/issues/80, but different because there is no superbuild for SlicerDMRI so the same fix does not apply.

@lassoan do you have any suggestions?

**Comment by lassoan** [comment]
The "published" date is when the extension package was uploaded to Girder. That is a new date for each Slicer version. It is different from last update time. See details of the macOS Slicer-5.6.1 SlicerDMRI package here: https://slicer-packages.kitware.com/#item/657844c683a3201b44d52d8b

Interestingly, the last update is December 30, which is neither the last SlicerDMRI update date (Dec 15) nor the latest extension package date (yesterday).

```
Created on December 12, 2023 at 6:32:22
Updated on December 30, 2023 at 9:23:27
```

The yellow icon on the dashboard is there for all builds, but recent ones cannot be downloaded (file not found on girder):

https://slicer.cdash.org/index.php?project=SlicerStable&begin=2023-12-05&end=2024-01-09&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=DMRI

Since the latest available package corresponds to the latest SlicerDMRI update (Dec 15) I'm not sure if there is anything wrong. It may be valid not to update packages if there was no change.

Maybe you could update something in the SlicerDMRI extension and see if the changes show up in the extensions catalog the next day?

**Comment by pieper** [comment]
> Maybe you could update something in the SlicerDMRI extension and see if the changes show up in the extensions catalog the next day?

Tried this but it didn't result in a new DMRI being offered.

After doing [an update](https://github.com/SlicerDMRI/SlicerDMRI/pull/234) to SlicerDMRI yesterday, a [new package](https://slicer.cdash.org/build/3268427) was built last night, but the older December 12 version of the DMRI extension is still being offered in the Extension manager for SlicerStable (5.6.1).

The package appears to be in girder but it's not being detected somehow.

**Comment by jamesobutler** [comment]
As of https://discourse.slicer.org/t/many-extensions-are-not-getting-updates-for-slicer-stable-release/34343/4, the macOS delivery of SlicerDMRI should be working for Slicer Stable (5.6.1). See https://slicer.cdash.org/builds/3308587.

@pieper can confirm prior to closing this issue.

**Comment by pieper** [comment]
It looks good to me but it would be great if @jhlegarreta or @ljod could doublecheck.

**Comment by ljod** [comment]
Hi I am getting a Dec 30 version of SlicerDMRI on Mac when I install it in Slicer 5.6.1. Is that what we expect? Or do we expect something from Jan 11?

**Comment by ljod** [comment]
Hi again. I see two different dates, Dec 12 in the extension itself and Dec 30 in the Extension manager info webpage thing. I am not sure why this is. See screenshots. This is after uninstalling and reinstalling SlicerDMRI today using Slicer 5.6.1 on Mac. It seems it is not updated. Please advise. 

<img width="831" alt="Screenshot 2024-02-21 at 3 57 21 PM" src="https://github.com/Slicer/Slicer/assets/4721911/caabf770-c7e7-4091-9956-e72865161317">

<img width="906" alt="Screenshot 2024-02-21 at 3 56 36 PM" src="https://github.com/Slicer/Slicer/assets/4721911/9ff932ae-12ba-446c-830e-9bc4cf504fe8">

**Comment by jcfr** [comment]
Thanks for the report, while the extension was successfully build[^1] against the latest Stable build tree, there is any issue uploading the package. 

We are investigating and will report back. 


[^1]: https://slicer.cdash.org/index.php?project=SlicerStable&date=2024-02-21&filtercount=1&showfilters=1&field1=buildname&compare1=63&value1=DMRI

**Comment by jamesobutler** [comment]
When I go to https://extensions.slicer.org/catalog/All/32729/macosx?q=slicerdm, SlicerDMRI for macOS is downloading `32438-macosx-amd64-SlicerDMRI-gitb4357b9-2023-12-15.tar.gz` which seems to match what is at https://slicer-packages.kitware.com/#item/657844c683a3201b44d52d8b. It appears the database entry is what was created on 12-12 and updated on 12-30.
![image](https://github.com/Slicer/Slicer/assets/15837524/3545abc8-2fcf-47c4-b680-117537e76807)

`b4357b9` in the extension package appears to match https://github.com/SlicerDMRI/SlicerDMRI/commit/b4357b934f82c9ced74e0ba0defed7f0a89b792d which is the latest commit for SlicerDMRI.

![image](https://github.com/Slicer/Slicer/assets/15837524/09b950a8-cbe9-4db8-bc57-8bfc5ce81a1b)

**Comment by jcfr** [comment]
After further analysis, I confirm @jamesobutler conclusion.

**Comment by jamesobutler** [comment]
https://slicer.cdash.org/index.php?project=SlicerStable&begin=2023-12-10&end=2023-12-31&filtercount=2&showfilters=1&filtercombine=and&field1=buildname&compare1=63&value1=SlicerDMRI&field2=site&compare2=63&value2=computron

![image](https://github.com/Slicer/Slicer/assets/15837524/25a06906-44b0-4d5f-82ec-82b8f0e4246a)

It appears that the database entry was updated on December 30th instead of December 15th/16th when the latest commit was pushed because there were some build errors that ultimately got resolved.

Whether the extensions manager web page should say the date of the commit that was last built successfully instead of when the database was updated with the new uploaded package is another thing. Maybe it would reduce confusion @jcfr ?

> <img width="831" alt="Screenshot 2024-02-21 at 3 57 21 PM" src="https://github.com/Slicer/Slicer/assets/4721911/caabf770-c7e7-4091-9956-e72865161317">
^ If after install on macOS it is indicating a commit other than https://github.com/SlicerDMRI/SlicerDMRI/commit/b4357b934f82c9ced74e0ba0defed7f0a89b792d, that would still be an open issue to look into.

On Windows it is weird in that it states the commit is https://github.com/SlicerDMRI/SlicerDMRI/commit/a23fcbb02453887f39432832199e650ca43a6baf from https://github.com/SlicerDMRI/SlicerDMRI/pull/234, however that commit was later force-pushed off of the `master` branch there. I'm not sure how the extensions manager is supposed to perform if commits are picked off. Is a new package that is technically an older commit then supposed to get uploaded as the one to use?
![image](https://github.com/Slicer/Slicer/assets/15837524/632e552d-0ea2-4f19-b4d0-25edcedeb1ae)

**Comment by jcfr** [comment]
In the meantime, this is intended to display the revision:
* https://github.com/KitwareMedical/slicer-extensions-webapp/pull/141

**Comment by lassoan** [comment]
Revision is displayed now in the extensions manager, so it should be clear what the content of the package is.
