### ISSUE TITLE
The problem encountered when drawing the target area.

### ISSUE THREAD

**Issue by susuleilei** [Slicer/Slicer#7551]
I want to draw the target area for tumors, but when I draw the first layer, the image overlaps with other layers automatically, and erasing also affects other layers.

**Comment by lassoan** [comment]
Thickness of the disk that is filled when you paint on a slice is set to the slice spacing of the current background volume. Thickness of the segmentation's labelmap volume is set from the first selected source volume. If result of painting in one slice is visible in neighbor slices then it means that you switched to a finer resolution volume during segmentation. So, what you see is completely normal, this is how segmentation is intended to work.

If you want higher resolution (for example because you need to create a segmentation from 3 volumes, each with sparse spacing along one axis) then you can specify the geometry of the segmentation manually as described here: https://slicer.readthedocs.io/en/latest/user_guide/modules/segmenteditor.html#segmentation-is-not-accurate-enough

If you have follow-up questions or need help with other Slicer features then please post it on the Slicer forum - https://discourse.slicer.org, this issue tracker is for managing software issues and enhancements.
