### ISSUE TITLE
Deterministic loading of modules: is it conceivable?

### ISSUE THREAD

**Issue by chir-set** [Slicer/Slicer#7567]
This is a vague idea, posted here for some distant day when it might be considered.

Briefly, load modules in an order per systemd-like instructions:

>     Before=<list of modules>
>     After=<list of modules>

If a module does not specify anything, load as usual.

There's a single rationale: avoid these messages when starting Slicer:

>     Failed to load vtkSlicerCrossSectionAnalysisModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
>     Failed to load vtkSlicerStenosisMeasurement3DModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython

    
This happens when SlicerVMTK is installed, it pulls in ExtraMarkups extension as a dependency. I understand from the messages that vtkSlicerShapeModuleMRMLPython is not yet loaded while it is being required by vtkSlicerCrossSectionAnalysisModuleLogicPython and by vtkSlicerStenosisMeasurement3DModuleLogicPython.

That's too demanding for a single annoying output in the terminal. It's in fact just a vague idea about which I wish to read a few comments.

Thanks and regards.

**Comment by jamesobutler** [comment]
It appears that the CrossSectionAnalysis module defines no other modules as a dependency (https://github.com/vmtk/SlicerExtension-VMTK/blob/1cfe4da260bab49a22ee0a740b87805f348230d8/CrossSectionAnalysis/CrossSectionAnalysis.py#L24) where listed dependent modules are loaded first prior to loading the specified module.

Although SlicerVMTK defines a dependency on ExtraMarkups in its s4ext file, that is only so that ExtraMarkups is automatically installed when installing SlicerVMTK from the extensions manager. It doesn’t specify the relation of modules in terms of loading dependency order.

**Comment by chir-set** [comment]
>It doesn’t specify the relation of modules in terms of loading dependency order.

I added 'ExtraMarkups' as a dependency in the relevant modules and things got worse, *additional* messages are in stdout:

> When loading module  "CrossSectionAnalysis" , the dependency "ExtraMarkups" failed to be loaded.
> void ctkComboBox::setCurrentUserDataAsString(QString) : No item found with user data string  "2"
> When loading module  "GuidedArterySegmentation" , the dependency "ExtraMarkups" failed to be loaded.
> When loading module  "StenosisMeasurement3D" , the dependency "ExtraMarkups" failed to be loaded.

All modules work as expected once Slicer is up.

Thank you for your reply @jamesobutler .

**Comment by jamesobutler** [comment]
From my understanding “ExtraMarkups” is the extension name and not the module names. Where the CrossSectionAnalysis module may have a dependency on the “Shape” or “Label modules. In the module, the dependencies is other modules and not extensions.

**Comment by chir-set** [comment]
> the extension name and not the module names

You are right about this. However, using 'Shape' as module name does not cancel the _original_ annoying stdout messages.

> Failed to load vtkSlicerStenosisMeasurement3DModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
> Failed to load vtkSlicerCrossSectionAnalysisModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
>   Error(s):
>     CLI executable: /home/user/programs/Slicer/slicer.org/Extensions-32703/SlicerVMTK/lib/Slicer-5.7/qt-loadable-modules/vtkvmtk.py
>     The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
> Fail to instantiate module  "vtkvmtk"
> The following modules failed to be instantiated:
>    vtkvmtk
> void ctkComboBox::setCurrentUserDataAsString(QString) : No item found with user data string  "2"
> 

I think that the solution would be to load anything close to core, like additional markups, before loading usual extensions. This would require core developments, time, funding... ...

Thank you for your time.

**Comment by lassoan** [comment]
> Failed to load vtkSlicerStenosisMeasurement3DModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython
Failed to load vtkSlicerCrossSectionAnalysisModuleLogicPython: No module named vtkSlicerShapeModuleMRMLPython

These are due to https://github.com/Slicer/Slicer/issues/7579

> CLI executable: /home/user/programs/Slicer/slicer.org/Extensions-32703/SlicerVMTK/lib/Slicer-5.7/qt-loadable-modules/vtkvmtk.py
The process failed to start. Either the invoked program is missing, or you may have insufficient permissions to invoke the program.
Fail to instantiate module "vtkvmtk"
The following modules failed to be instantiated:
vtkvmtk

This harmless error message is [well known](https://github.com/vmtk/SlicerExtension-VMTK/issues/22) and it is safe to ignore. We can address it as VTK remote module Python wrapping and packaging is improved.

> void ctkComboBox::setCurrentUserDataAsString(QString) : No item found with user data string "2"

You can add a breakpoint into this method to see what is the root cause.

**Comment by chir-set** [comment]
Thank you @lassoan for addressing this with a [PR](https://github.com/Slicer/Slicer/pull/7580).

The vtkvmtk message is indeed [old](https://discourse.slicer.org/t/something-wrong-with-the-new-slicer-after-installed-some-modules/30613) and harmless.

The other one (::setCurrentUserDataAsString) appeared during tinkering, and does not appear otherwise. I'll get deeper into it if necessary.

**Comment by chir-set** [comment]
Since 9c875033, the messages in stdout related to vtkSlicerShapeModuleMRMLPython are indeed gone.

('Fail to instantiate module "vtkvmtk"' still persists and was not the target of the patch.)

Thank you all.

@lassoan @jcfr @jamesobutler
