### ISSUE TITLE
Simple Filters do not work in all installations

### ISSUE THREAD

**Issue by dzenanz** [Slicer/Slicer#7661]
## Summary

Trying to run any filter from `Simple Filters` results in an error:
```
---------------------------
Exception before execution of AbsImageFilter
---------------------------
<class 'RuntimeError'>
---------------------------
OK   
---------------------------
```
content in the log:

```log
myFilter = AbsImageFilter()
myFilter.SetDebug(False)
myFilter.SetNumberOfThreads(24)
myFilter.SetNumberOfWorkUnits(0)
Error ImageIO factory did not return an ImageIOBase: MRMLIDImageIO
```
## Steps to reproduce

1. Download `MRHead` sample data
2. Switch to `Simple Filters` module
3. Click `Apply`
4. The above error appears

## Environment
- Error appears for me in `Slicer 5.6.1 r32438 / 117ce5f` on Windows 11 (23H2 build 22631.3296) fully updated
- Works as expected in versions `5.2.1 r31317 / 77da381` and `5.7.0-2024-03-06 r32752 / 024b340` on the same Windows machine
- Works as expected in `Slicer 5.6.1 r32438 / 117ce5f` on Ubuntu 22.04.4 LTS.
- Error appears in `Slicer 5.6.1 r32438 / 117ce5f` on Ubuntu for @andinet.

**Comment by lassoan** [comment]
This error is typically due to that you (or any of thr extensions ypu installed) installed SimpleITK from PyPI and that overwrote Slicer's SimpleITK. SimpleITK installed from PyPI does not include the in-memory transfer image IO.

We have been avoiding reinstaing SimpleITK and if there is a package then insists on replacing it (e.g., nnunetv2) then we rewrite package dependencies on-the-fly (see TotalSegmentator Slicer extension).

Would it be sufficient to check the SimpleITK version ar startup and display a descriptive error message if it is not correct, to make extension developers aware that they broke some features Slicer?

**Comment by dzenanz** [comment]
> check the SimpleITK version ar startup and display a descriptive error message

I think that would be sufficient. The possible culprit (in this instance) is https://github.com/bowang-lab/MedSAMSlicer.

**Comment by lassoan** [comment]
Fixed by https://github.com/Slicer/Slicer/pull/7699

**Comment by jcfr** [comment]
For future reference, the linked pull request was closed and corresponding changes were directly integrated to `main` as commits 03ff788 and 29f6b91
