### ISSUE TITLE
Loading volume from DICOM series using single file archetype fails to reconstruct image geometry properly

### ISSUE THREAD

**Issue by alund** [Slicer/Slicer#7730]
## Summary

When loading a DICOM series by selecting a single file from a directory containing the full series, choosing "Volume" and then unchecking the "Single File" checkbox, Slicer does not reliably reconstruct the image. In particular, it does not (always) sort the slices correctly. It appears to depend on the files being named in order (or perhaps on the order they are listed by the OS). The incorrect ordering can result in the spacing being calculated incorrectly (using the wrong "first" and "last" slices). If the files are in reverse order, the spacing will be fine but the bounds of the image will be wrong.

## Steps to reproduce
I have attached two zip files containing the same data, but with the files named differently. In one of the .zip files, the files are named according to the instance number. In the other, the files are named randomly.

[sort_and_name_by_instance_number.zip](https://github.com/Slicer/Slicer/files/15236979/sort_and_name_by_instance_number.zip)

[sort_and_name_by_random.zip](https://github.com/Slicer/Slicer/files/15237217/sort_and_name_by_random.zip)

The series was originally a sagittal T1, but I have replaced the pixel values in each slice with a gray scale value corresponding to the instance number. The instance numbers should increase from right-to-left with the right edge near 83 R and the left edge near 96 L. The slice spacing should be 0.8 mm.

When loading from the directory containing files named by instance number and selecting 001.dcm, and then unchecking the "Single File" checkbox, the series is loaded, the grayscale pattern is reproduced and the slice spacing is 0.8 mm. While one edge is near 83 R, the other edge is near 261 R. Basically, the image has been reflected around 83 R.

When loading from the directory containing files named randomly, selecting 00056703.dcm, choosing "Volume" and unchecking the "Single File" checkbox, the resulting volume has 0.49507 mm slice spacing and the slices are clearly mis-ordered, producing striping in the axial and coronal views. The volume bounds are similarly incorrect (62 R to 173R). Other random orderings produce different results. See attached screenshot.

![Screenshot 2024-05-07 at 9 47 01 AM](https://github.com/Slicer/Slicer/assets/68935/12147d7b-49c2-4c4b-b0bf-f41477bad20d)

I looked through the code. `vtkITKArchetypeImageSeriesReader::AssembleVolumeContainingArchetype()` appears to be the method that _should_ order things correctly. I could not figure out by inspection if it was incorrect, not getting called or if something else was reordering things after the files were sorted there.

## Environment
- Slicer version: I have reproduced this in versions 4.11.20200930, 5.4.0, 5.6.0, 5.6.2 and the current 5.7.0 preview. Version 4.10.0 works as expected. 
- Operating system: M1 Mac / Sonoma 14.4

**Comment by pieper** [comment]
Maybe we should add strict warnings, but [the documentation](https://slicer.readthedocs.io/en/latest/user_guide/data_loading_and_saving.html) is explicit that you should use the DICOM module preferentially, and use the generic add data for non-DICOM data.  DICOM is just too complex to be loaded with simple readers and the filenames should never be used to sort DICOM instances.

If I use the DICOM module both datasets you provided are loaded in the same way.

**Comment by jamesobutler** [comment]
> Slicer version: I have reproduced this in versions 4.11.20200930, 5.4.0, 5.6.0, 5.6.2 and the current 5.7.0 preview.

@alund As of Slicer 5.4.0 (by way of https://github.com/Slicer/Slicer/commit/ff1ba1679ae98a6a2e669d79dde1ad8620b60c04) there would've been an option of "DICOM import" in the add data dialog. Was there a reason you specifically did not select this option and instead selected "Volume"? Did you not want to import the dicom data in the Slicer DICOM database? I previously had created some work in https://github.com/Slicer/Slicer/pull/7156 to support loading DICOM image data by using a temporary DICOM database so that one wouldn't have to add it into their Slicer DICOM database.

**Comment by alund** [comment]
> DICOM is just too complex to be loaded with simple readers and the filenames should never be used to sort DICOM instances.

The filenames should not be used, and yet apparently that is what Slicer is doing. Even if it is just relying on the order the directory listed was obtained from the OS, it's still not doing the right thing.

This worked in 4.10.0 and before. There still exists code that _looks_ like it is intended to solve this problem. Importing the DICOM files adds steps to the workflow that do not benefit me, except insofar as they are made necessary because the other way doesn't work. In the case where the files are loaded in reverse order, it's not at all obvious that something is wrong, at least not for a sagittal image where LR symmetry is expected.

**Comment by alund** [comment]
@jamesobutler, as I said in my report, the DICOM import does work. It's just not very convenient for my workflow. I frequently use Slicer to visualize the outputs of our software. Usually that involves NIfTI files, transforms and STL/OBJ meshes. But sometimes I need to check a DICOM image. Still, it's a very "episodic" thing. I don't need Slicer to store that data forever, I just want to add it to the current scene, probably alongside other images and meshes that I am loading at the same time. 

If I load a volume, I can change the name of the node right there, I can choose whether or not to show it, I can choose the color map, I can load other data into the same scene in the same way. 

I can do those things eventually by importing the DICOM, then _finding_ what I just imported (which, to be fair, is easy to find based on time it was added but still involves selecting the patient and then the series), double-click to load the volume, then select the node, edit properties, etc. Maybe I wanted it loaded into the scene but not to be the background image, so now I have to be very careful about the order I do things or do still more steps to fix things up. If I'm regenerating and reloading the same image over and over, that gets old pretty fast.

I appreciate the availability of Slicer. It's a very useful tool. There are other inconveniences, but being able to write Python code to automate the most highly repetitive things is great. I wish I were better at it. Maybe that will be my answer here too.

**Comment by jamesobutler** [comment]
@pieper @lassoan I think the above feedback reveals that Slicer needs to further improve the concept of quickly loading volume data stored in .dcm so that the user can view the image data. This falls under the label of "make-simple-things-simple". The "DICOM import" add data dialog was one step to guide users to use the DICOM module and its best loading logic to load the image data however it is deemed to still be introducing extra click steps to get to the point of viewing the image data. The goal of my #7156 was primarily to load .dcm using the DICOM module logic to get to viewing the image data sooner. Any thoughts of how best to proceed with resurrecting this idea of being able to view image data from .dcm in a quicker manner?

**Comment by lassoan** [comment]
Loading everything from the folder (and all subfolders) from where the file was drag-and-dropped from would be bad for many users, because DICOM folders obtained from clinical imaging system contain mostly irrelevant data objects - scout images, dose reports, repeated acquisitions, secondary captures, reformatted images, etc. It may also contain huge images that users should be carefully consider to attempt to load.

The new visual DICOM browser should help, as it can show thumbnails immediately while it is scanning files (maybe we can improve things by not reading the files sequentially but sampling them so that we come across images from each series faster; and we could also get hints from DICOMDIR file).

If there are privacy concerns then automatic cleaning of the database could be implemented, too. Probably on exit, as modules may still need to access the database to interpret the images and resolve cross-references.
