### ISSUE TITLE
Potential invalid use of `c_str()` in `vtkMRMLNode::GetReferenceRoleFromMRMLAttributeName`

### ISSUE THREAD

**Issue by maddin200** [Slicer/Slicer#7791]
Libs\MRML\Core\vtkMRMLScalarVolumeDisplayNode.cpp line 666
Code:
return nodeReferenceRole.c_str(); // <- c_str may be invalid outside

**Comment by lassoan** [comment]
The code line is actually in vtkMRMLNode.cxx:

https://github.com/Slicer/Slicer/blob/305624e90cdd2867b8064e106f9e9aaaf836834d/Libs/MRML/Core/vtkMRMLNode.cxx#L666

I believe it is safe, because `nodeReferenceRole` is a reference to a string stored in `NodeReferenceMRMLAttributeNames` member variable, therefore the string buffer remains valid when returning from `vtkMRMLNode::GetReferenceRoleFromMRMLAttributeName`.

@pieper @jcfr do you agree? `vtkMRMLNode::GetReferenceRoleFromMRMLAttributeName` is a protected method, so we could easily change it to return `std::string` instead of `const char*`, but there might be tiny performance difference and in general if something is not broken then it may be better not to change it.

**Comment by pieper** [comment]
Yes, I agree, this seems unlikely to cause any issues.
