### ISSUE TITLE
The external python program calls the slicer plug-in, or installs the plug-in in other software.

### ISSUE THREAD

**Issue by ningw-git** [Slicer/Slicer#7887]
I am trying to do secondary development based on 3D slicer, using Python language, and now I have encountered a problem, and I am here to ask for your help. I want to use the plug-in OpenIGTLink that calls slcier externally, can I achieve this function? Or can I install this plug-in into my secondary development software? Can you give me some suggestions or ideas?

**Comment by lassoan** [comment]
Yes, sure, it is all doable. Please post your questions on the [Slicer forum](https://discourse.slicer.org/) in the `Development` category.

**Comment by ningw-git** [comment]
ok,thanks.But no reply for me ,help!!!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Slicer/Slicer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月15日(星期四) 下午5:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Slicer/Slicer] The external python program calls the slicer plug-in, or installs the plug-in in other software. (Issue #7887)





 
Yes, sure, it is all doable. Please post your questions on the Slicer forum in the Development category.

**Comment by lassoan** [comment]
It is August, lots of people are on vacation, so answers may be delayed, or your question may have just fallen through the cracks. If you have already submitted a question to the Slicer forum and there was no response then you can post updates in your topic (describe what you did since you asked the question, provide more details, etc.) once a week. That will bump the topic to the top of the list of posts and shows that your question is still relevant.
