### ISSUE TITLE
DICOMEnhancedUSVolumePlugin does not read or preserve origin and spacing

### ISSUE THREAD

**Issue by jadh4v** [Slicer/Slicer#7929]
## Summary
There are two parts to this problem:
### Steps to reproduce
   ```py
# using DCMTK backend
reader.SetDICOMImageIOApproachToDCMTK()
reader.Update()
imageData = reader.GetOutput()
print('imageData.GetSpacing = ', imageData.GetSpacing())
print('imageData.GetOrigin = ', imageData.GetOrigin())
# output 
# imageData.GetSpacing =  (0.4, 0.4, 1.0)
# imageData.GetOrigin =  (106.2, -0.0, 106.2)

# similarly using GDCM backend: reader.SetDICOMImageIOApproachToGDCM()
# output is
# (1.0, 1.0, 1.0)
# (0.0, 0.0, 0.0)
   ```
### Steps to reproduce
Currently I cannot find a public dataset that belongs to the Enhanced Ultrasound Volume Storage class (SOPClassUID: `1.2.840.10008.5.1.4.1.1.6.2`)
But if you look at the following lines of code (138-140), the script appears to immediately overwrite the origin and spacing before moving that information to any MRML node:
https://github.com/Slicer/Slicer/blob/main/Modules/Scripted/DICOMPlugins/DICOMEnhancedUSVolumePlugin.py#L138-L140
```py
imageData = reader.GetOutput()
imageData.SetSpacing(1.0, 1.0, 1.0)
imageData.SetOrigin(0.0, 0.0, 0.0)
volumeNode.SetIJKToRASMatrix(ijkToRas)
volumeNode.SetAndObserveImageData(imageData)
```

## Environment
- Slicer version: Slicer@e8a49d6659898eb75ed0980367affd70c7715be6 (July 25, 2024)
- Operating system: Windows 11 Pro 23H2 22635.4145

**Comment by lassoan** [comment]
> 1. At least on the datasets I have (private), GDCM doesn't return correct origin and spacing values. DCMTK works correctly.

Pixel spacing is specified in ultrasound for each image region, so the current method of storing a global spacing for the whole image will just not work, regardless of using GDCM or DCMTK.

I would recommend you to use https://github.com/SlicerUltrasound/SlicerUltrasound if you want to train AI tools on ultrasound images.

> DICOM Plugin DICOMEnhancedUSVolumePlugin doesn't seem to preserve origin and spacing of the read image

For decades, VTK could not store image orientation in vtkImageData, therefore we had to store IJKToRASMatrix outside vtkImageData (and set unit spacing and zero origin in the vtkImageData to avoid rendering errors). This is what you still see in the source code, which is correct and how it is intended to work.

We will probably refactor the code to store image direction in vtkImageData in Slicer-6.0.

---

If you implement multi-region ultrasound image import then your contribution would be certainly welcome. But since that would be probably in the Ultrasound extension, I don't think we need to keep an open issue for this in the Slicer issue tracker, so I'm closing this issue now.
