### ISSUE TITLE
LabelMapVolume is loaded instead of ScalarVolume

### ISSUE THREAD

**Issue by rasakereh** [Slicer/Slicer#8006]
## Summary

I have an image file that when is loaded, looks distorted. I noticed that the problem is with the node type it is loaded in. It uses LabelMapNode instead of ScalarVolume.
![image](https://github.com/user-attachments/assets/0de83ae9-e00f-4ce1-91bc-2c7c332c9c17)
By converting it to ScalarVolume, problem goes away but can you make it happen automatically while file is loaded?
![image](https://github.com/user-attachments/assets/0113b7f5-53e4-46d0-9c8a-da900e97a768)

## Steps to reproduce
Use this image file: [https://www.cancerimagingarchive.net/collection/adrenal-acc-ki67-seg/](https://www.cancerimagingarchive.net/collection/adrenal-acc-ki67-seg/)

## Environment
- Slicer version: Slicer-5.4 and Slicer-5.7
- Operating system: Ubuntu 20 / Mac

**Comment by lassoan** [comment]
This behavior is a convenience feature. Since most image file formats do not contain a standard field that tells how to interpret the image content (as scalar or labelmap volume), we allow the user to give hint with appropriate file naming convention. See details in the [documentation](https://slicer.readthedocs.io/en/latest/user_guide/modules/volumes.html#load-image-file-as-labelmap-volume):

> Load image file as labelmap volume ...
...before loading the file, rename it so that it contains `label` or `seg` in its name, for example: something.label.nrrd, something-label.nrrd, or something-seg.nrrd. This makes LabelMap checked by default.

If you do not wish to load that image file as labelmap by default then do not include `-seg` in its filename (or in `Add data` window enable `Show options` and uncheck the `LabelMap`).
