### ISSUE TITLE
SetAndObserveTransformNodeID() on a transform node

### ISSUE THREAD

**Issue by dmitrishastin** [Slicer/Slicer#8040]
Hi, 

My extension uses a basic hierarchy of transform nodes such that there is one parent node (core) and a number of its children. The children are then used to define transforms for individual volumes, bringing them all to some common space. The idea is that if I want to transform all volumes (still aligned) to some third space, I should only have to apply this third space's transform to the core node.

This works through GUI - adding the third transform to the core transform node causes volumes to change orientation in 2D views (both foreground and background). However, scripting it the following way (where `transformCore()` is called each time a checkbox is clicked) does not update the volume orientations:

```
core = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLTransformNode")
core.SetAttribute('ExtensionName.CoreTransformNode', 'True')
third = slicer.mrmlScene.AddNewNodeByClass("vtkMRMLTransformNode")
_ = slicer.util.updateTransformMatrixFromArray(third, -np.eye(4))
third.SetAttribute('ExtensionName.ThirdTransformNode', 'True')

def transformCore(self):
  txNodes = slicer.mrmlScene.GetNodesByClass('vtkMRMLTransformNode')
  for node in list(txNodes):
    attr = node.GetAttributeNames()
    if 'ExtensionName.CoreTransformNode' in attr:
      core = node
    elif 'ExtensionName.ThirdTransformNode' in attr:
      third = node
  if core.GetTransformNodeID() is None:
    core.SetAndObserveTransformNodeID(third.GetID())
  else:
    core.SetAndObserveTransformNodeID(None)

self.ui.checkbox.connect('toggled(bool)', self.transformCore)
```

Having said that, when toggled, it appears that `core` does indeed get `third` as its transform node on first click, this is removed on second click, and so on. It appears that it's just the views that aren't updating.

Is this a bug?
Is there a way to force views to update?

Will be grateful for your help!

**Comment by lassoan** [comment]
The problem is that `-np.exe(4)` matrix is not a valid homogeneous transformation matrix for two reasons:
- The fourth row of the `third` matrix is set to `[0,0,0,-1]`. The last row must be `[0,0,0,1]`.
- The matrix turns the space inside out, i.e., the determinant of the top-left 3x3 submatrix is negative. It must be positive.

This issue tracker is used for managing confirmed issues and feature requests in Slicer core. If you have any further questions, please post it on https://discourse.slicer.org. Include a code snippet that we can copy-paste into the Slicer Python console to reproduce the unexpected behavior (include the part that loads input data, etc.).

**Comment by dmitrishastin** [comment]
Thank you. Apologies - this was just an example - you're right, I should have picked this up. I provide a real transform that works in my code. Just didn't have it handy.
