### ISSUE TITLE
Slicer cannot connect to extension server in company proxy environment.

### ISSUE THREAD

**Issue by ptlzon** [Slicer/Slicer#8070]
## Summary

Hi, thank you for developing a very valuable tool for 3D community.

I am a first time Slicer user and I installed 3D Slicer 5.6.2 to my company PC (behind proxy).
Unfortunately, currently I cannot do anything with Slicer because it says 
"Failed to load extension page using this URL: https://extensions.slicer.org/catalog/All/32448/win"
![image](https://github.com/user-attachments/assets/41f821e4-5f90-4379-9306-212597c2ad16)

The URL can be accessed normally with a browser.
I have set http_proxy and https_proxy environments (windows) and other applications requiring internet connection are working fine.
![image](https://github.com/user-attachments/assets/ae947b20-858d-4848-9352-21fbba742318)

I don't see where to set proxy information in Slicer. How to troubleshoot this?
Thanks a lot.

Sincerely,
Lam

## Steps to reproduce
1. Install Slicer 5.6.2
2. Go to Extension Manager
3. Error message appears.
## Environment
- Slicer version: Slicer-5.6.2
- Operating system: Windows 10

**Comment by lassoan** [comment]
Slicer uses proxies set in your system by default but you can also [manually specify them](https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#extensions-manager-does-not-show-any-extensions).

However, when Slicer cannot connect to the extension server it is usually due to your company using internally generated SSL certificates that is used for intercepting and decrypting all your network traffic. Slicer does not accept these certificates, as they are not provided by a trusted authority.

Quickest workaround is to install extensions without a network connection - see https://slicer.readthedocs.io/en/latest/user_guide/extensions_manager.html#install-extensions-without-network-connection.

You can try to add the custom certificates to `SlicerInstallFolder\share\Slicer-5.7\Slicer.crt`, but if the certificates are replaced frequently (e.g., if your company uses zscaler) then this is just a temporary solution.

The final solution is usually that your IT administrators add the necessary exceptions to the proxy server. See this topic for a more details: https://discourse.slicer.org/t/sandbox-module-cannot-be-downloaded-via-extension-manager-today/33809

**Comment by ptlzon** [comment]
Thanks a lot for the detailed response.

I solved it by installing extensions by downloading them and install within the extension manager.

**Comment by jcfr** [comment]
For reference, in the context of https://github.com/BrownBiomechanics/SlicerAutoscoperM/issues/117, @amymmorton successfully engage with the IT team of their organization to add domains like `slicer.org`, `github.com` (and most likely `kitware.com`)  as exceptions to address what has been described as _corporate Man In the Middle (MITM)_ situation.

While looking into this, I also just found the following references may be relevant:
* https://geekingfrog.com/blog/post/corporate-man-in-the-middle
