### ISSUE TITLE
Slice views: segmentation nodes missing

### ISSUE THREAD

**Issue by chir-set** [Slicer/Slicer#8085]
On Linux, 5.7.0-2024-12-06 r33142 / bf0f921

Hello,

I just noticed that segments are no longer available for displaying their outlines in the controller of slice views.

![no_label_map_slice_views](https://github.com/user-attachments/assets/5d26fc67-31d3-4998-a95f-e5c32fa3214e)

Thank you for looking into this.

**Comment by cpinter** [comment]
You need to have a segmentation in the scene for those selectors to show up

This is from latest:

![image](https://github.com/user-attachments/assets/3ec9ccc2-7aca-496a-9307-0e6baa4d7b6a)

**Comment by chir-set** [comment]
> You need to have a segmentation in the scene for those selectors to show up

As you can see @cpinter  in the picture I posted, there is a segmentation. I have to click on the double upper left arrows for the segmentation widgets to appear, this after loading a saved scene. No fundamental problem then.

Thank you for your reply.

**Comment by cpinter** [comment]
Feel free to reopen. I saw that but didn't think it through enough assuming it was a labelmap (which cannot be because the dropdown shows nothing).

> this after loading a saved scene

Make sure you include exact steps to reproduce if you reopen.

**Comment by jamesobutler** [comment]
Executing the code blocks and viewing their output below seems to indicate that Slicer 5.7.0-2024-12-09 can get into a state where the slice controller is expanded with a segmentation in the scene, but the segmentation selector is not shown. Compared to Slicer 5.6.2 it appears that the latest Slicer preview shows the Slice controller in the expanded state by default rather than in the minimized single row state. This probably leads to the downstream confusion of the slice controller is expanded, but you can't see the segmentation selector until you press the expand button again.
```python
import SampleData
SampleData.SampleDataLogic().downloadMRHead()
slice_widget = slicer.app.layoutManager().sliceWidget("Red")
slice_widget.sliceController().pinButton().click()
```

|Slicer 5.6.2 | Slicer 5.7.0-2024-12-09|
|------------|---------------------------|
|![{CF90F53D-A874-48C2-99F4-46B35251EB20}](https://github.com/user-attachments/assets/a56b900c-7d62-4039-96c7-41861cfa8bfc)|![{4033066A-5AD7-4F5C-883D-98ABA90B23D6}](https://github.com/user-attachments/assets/8e366100-6016-4ed9-b18f-3ffc1515220f)|

```python
slicer.util.selectModule("SegmentEditor")
```
|Slicer 5.6.2 | Slicer 5.7.0-2024-12-09|
|------------|---------------------------|
|![{9917C33D-44A8-4320-B4B3-C56D7D620504}](https://github.com/user-attachments/assets/74423c1b-c62d-48bb-b289-3f8dede21fb4)|![{CBCD59EE-749B-45B4-8510-C0F4BB625C59}](https://github.com/user-attachments/assets/d372b3d0-c409-4d9e-8934-b1d0a126e281)|

```python
slice_widget.sliceController().findChild(ctk.ctkExpandButton, "MoreButton").click()
```
|Slicer 5.6.2 | Slicer 5.7.0-2024-12-09|
|------------|---------------------------|
|![{5E78A103-2B61-470B-9947-00D9D1D01041}](https://github.com/user-attachments/assets/77c985f4-5509-40bf-a845-95918bde0401)|![{4F354CBA-ACEE-44F4-A07D-FECD33060100}](https://github.com/user-attachments/assets/86feb432-6d58-47d8-b31d-32a6417cae53)|

**Comment by jamesobutler** [comment]
@lassoan Did you accidentally change the default checked state for the MoreButton in recent commit https://github.com/Slicer/Slicer/commit/bf0f921a7191415ac18b6e7015039e60b5943f91? Specifically this code here where it is now `false`, but was previously `true`.
https://github.com/Slicer/Slicer/blob/f405cf0efe2f987554d25941cf6d37aa449c3dba/Libs/MRML/Widgets/Resources/UI/qMRMLSliceControllerWidget.ui#L422-L424
